Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-07, with the labels that each got.

#579 feat(eslint-plugin): add rule strict-boolean-expressions
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: 1 approval, enhancement: new plugin rule

#625 feat(eslint-plugin): Add rule no-reference-import
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-triple-slash-reference.md
  packages/eslint-plugin/docs/rules/triple-slash-reference.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-triple-slash-reference.ts
  packages/eslint-plugin/src/rules/triple-slash-reference.ts
  packages/eslint-plugin/tests/rules/no-triple-slash-reference.test.ts
  packages/eslint-plugin/tests/rules/triple-slash-reference.test.ts
Labels: 1 approval, enhancement: new plugin rule

#681 fix(typescript-estree): fix `async` identifier token typed as `Keyword`
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/keyword-variables.src.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: bug

#680 feat(eslint-plugin): [explicit-function-return-type] add handling for usage as arguments
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: enhancement

#675 fix: Correct `@types/json-schema` dependency
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/experimental-utils/package.json
Labels: dependencies

#649 chore(eslint-plugin): add config validation script to CI
  azure-pipelines.yml
  package.json
  packages/eslint-plugin/README.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/tools/log.ts
  packages/eslint-plugin/tools/validate-configs/checkConfigAll.ts
  packages/eslint-plugin/tools/validate-configs/checkConfigRecommended.ts
  packages/eslint-plugin/tools/validate-configs/index.ts
  packages/eslint-plugin/tools/validate-docs/check-for-rule-docs.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-rules.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-structure.ts
Labels: tests

#612 feat(eslint-plugin): add new rule no-misused-promises
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-misused-promises.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/configs/base.json
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: 1 approval, enhancement: new plugin rule

#713 fix(utils): RuleTester should not require a parser
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: bug

#715 docs(eslint-plugin): mention member-delimiter-style in semi
  packages/eslint-plugin/docs/rules/semi.md
Labels: documentation

#712 fix(utils): move `typescript` from peer dep to dev dep
  packages/experimental-utils/package.json
Labels: bug

#674 feat(eslint-plugin): add new rule require-await
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/require-await.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval, enhancement: new plugin rule, package: eslint-plugin

#645 feat: Support eslint@6
  azure-pipelines.yml
  package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/eslint-rules/no-redeclare.test.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
  packages/eslint-plugin/tests/rules/ban-ts-ignore.test.ts
  packages/eslint-plugin/tests/rules/no-triple-slash-reference.test.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
  packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
  packages/eslint-plugin/typings/eslint-ast-util.d.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  packages/parser/package.json
  packages/typescript-estree/tests/ast-alignment/utils.ts
  yarn.lock
Labels: breaking change, dependencies, enhancement

#594 fix(eslint-plugin)!: remove "isTypescriptFile".
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
  packages/eslint-plugin/tests/util.test.ts
Labels: 1 approval, breaking change, bug

#733 feat(eslint-plugin)!: [promise-function-async] make allowAny default true
  packages/eslint-plugin/docs/rules/promise-function-async.md
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: breaking change, enhancement

#654 feat(eslint-plugin)!: [array-type] add "default", "readonly" options
  packages/eslint-plugin/docs/rules/array-type.md
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: 1 approval, breaking change, enhancement: plugin rule option

#725 fix(eslint-plugin): [no-var-requires] error if parent is CallExpression
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/tests/rules/no-var-requires.test.ts
Labels: bug

#739 feat(eslint-plugin)!: remove deprecated rules
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-triple-slash-reference.md
  packages/eslint-plugin/docs/rules/prefer-interface.md
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-triple-slash-reference.ts
  packages/eslint-plugin/src/rules/prefer-interface.ts
  packages/eslint-plugin/tests/rules/no-triple-slash-reference.test.ts
  packages/eslint-plugin/tests/rules/prefer-interface.test.ts
Labels: breaking change, enhancement

#595 feat(eslint-plugin)!: Move opinionated rules from 'eslint-recommended' to 'recommended'
  packages/eslint-plugin/src/configs/eslint-recommended.ts
  packages/eslint-plugin/src/configs/recommended.json
Labels: 1 approval, breaking change, recommended-rules

#581 feat(eslint-plugin): added new rule typedef
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/typedef.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
Labels: enhancement: new plugin rule

#727 docs(eslint-plugin) Add `no-async-without-await` to ROADMAP
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#691 feat(eslint-plugin): [strict-boolean-expressions] add ignoreRhs option
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: 1 approval, enhancement: plugin rule option

#728 feat(eslint-plugin): add support for object props in CallExpressions
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: enhancement

#458 test: setup for real-world performance testing
  tests/performance/README.md
  tests/performance/docker-compose.yml
  tests/performance/fixtures/lint-real-repo/Dockerfile
  tests/performance/fixtures/lint-real-repo/install-local-packages.sh
Labels: tests

#731 feat(eslint-plugin)!: add rule `consistent-type-assertions`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
  packages/eslint-plugin/docs/rules/no-angle-bracket-type-assertion.md
  packages/eslint-plugin/docs/rules/no-object-literal-type-assertion.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/configs/base.json
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-angle-bracket-type-assertion.ts
  packages/eslint-plugin/src/rules/no-object-literal-type-assertion.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
  packages/eslint-plugin/tests/rules/no-angle-bracket-type-assertion.test.ts
  packages/eslint-plugin/tests/rules/no-object-literal-type-assertion.test.ts
  packages/experimental-utils/src/eslint-utils/batchedSingleLineTests.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: breaking change, enhancement: new plugin rule

#685 fix(eslint-plugin): [no-useless-constructor] handle bodyless constructor
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/eslint-plugin/tests/rules/no-useless-constructor.test.ts
Labels: bug

#562 feat(eslint-plugin): added new rule use-default-type-parameter
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-unnecessary-type-arguments.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/indent-new-do-not-use/BinarySearchTree.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
Labels: enhancement: new plugin rule

#760 feat(typescript-estree)!: throw error on file not in project when `project` set
  .prettierignore
  packages/eslint-plugin-tslint/tests/fixture-project/1.ts
  packages/eslint-plugin-tslint/tests/fixture-project/2.ts
  packages/eslint-plugin-tslint/tests/fixture-project/3.ts
  packages/eslint-plugin-tslint/tests/fixture-project/4.ts
  packages/eslint-plugin-tslint/tests/fixture-project/5.ts
  packages/eslint-plugin-tslint/tests/fixture-project/6.ts
  packages/eslint-plugin-tslint/tests/fixture-project/tsconfig.json
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin-tslint/tests/test-project/extra.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/fixtures/file.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-qualifier.test.ts
  packages/parser/README.md
  packages/parser/tests/lib/parser.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/tsconfig-parser.ts
  packages/typescript-estree/tests/fixtures/simpleProject/file.ts
  packages/typescript-estree/tests/fixtures/simpleProject/tsconfig.json
  packages/typescript-estree/tests/lib/parse.ts
  packages/typescript-estree/tests/lib/semanticInfo.ts
  tests/integration/utils/.eslintrc.js
  tests/integration/utils/jsconfig.json
Labels: breaking change

#777 fix(eslint-plugin): [no-explicit-any] Fix ignoreRestArgs for interfaces
  packages/eslint-plugin/docs/rules/no-explicit-any.md
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
Labels: bug

#773 docs(eslint-plugin): Improve ban-types description
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
Labels: documentation

#779 docs(prefer-readonly): add rule name to title
  packages/eslint-plugin/docs/rules/prefer-readonly.md
Labels: documentation
