Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-06, with the labels that each got.

#538 feat(eslint-plugin): [explicit-function-return-type] allowHigherOrderFunctions (#193)
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: 1 approval, enhancement: plugin rule option

#584 fix(experimental-utils): Avoid typescript import at runtime
  packages/experimental-utils/src/index.ts
Labels: bug, dependencies

#591 Add eslint:recommended to a usage example
  packages/eslint-plugin/README.md
Labels: documentation

#576 fix(eslint-plugin): [no-type-alias] Fix parenthesized type handling
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: bug

#536 fix(eslint-plugin): [no-unnecessary-type-assertion] false positive for null assign to undefined
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: bug

#537 fix(eslint-plugin): [no-unnecessary-type-assertion] handle missing declarations
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: bug

#495 feat(eslint-plugin): add new rule no-floating-promises
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: 1 approval, enhancement: new plugin rule

#548 feat(eslint-plugin): [no-explicit-any] ignoreRestArgs
  packages/eslint-plugin/docs/rules/no-explicit-any.md
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
Labels: 1 approval, enhancement: plugin rule option

#543 fix(eslint-plugin): [no-magic-numbers] add support for enums
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval, enhancement: plugin rule option

#553 feat(eslint-plugin): [promise-function-async] Allow any and unknown as return values
  packages/eslint-plugin/docs/rules/promise-function-async.md
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: enhancement: plugin rule option

#626 feat(eslint-plugin): add new rule no-empty-function
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/tests/rules/no-empty-function.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement

#463 feat(eslint-plugin): add `consistent-type-definitions` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/consistent-type-definitions.md
  packages/eslint-plugin/docs/rules/prefer-interface.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-interface.ts
  packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
  packages/eslint-plugin/tools/validate-docs/check-for-rule-docs.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-rules.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-structure.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: 1 approval, enhancement: plugin rule option

#555 feat(eslint-plugin): added new rule prefer-readonly
  packages/eslint-plugin-tslint/src/custom-linter.ts
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/prefer-readonly.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/TokenInfo.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
  packages/typescript-estree/src/convert.ts
Labels: 1 approval, enhancement: new plugin rule

#609 feat(eslint-plugin): [no-explicit-any] Add an optional fixer
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-explicit-any.md
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
Labels: 1 approval

#616 feat(eslint-plugin): [ban-types] Support namespaced type
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: 1 approval, enhancement

#633 fix(eslint-plugin): handle `const;`
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#634 docs(eslint-plugin): Expand docs for array-type
  packages/eslint-plugin/docs/rules/array-type.md
Labels: documentation
