Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-09, with the labels that each got.

#916 chore: support typescript 3.6
  .eslintrc.js
  package.json
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/src/rules/quotes.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/experimental-utils/package.json
  packages/parser/package.json
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/keyword-variables.src.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/convert.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
  yarn.lock
Labels: dependencies

#912 fix(eslint-plugin): [explicit-member-accessibility] fix parameter properties bugs
  packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
Labels: bug

#939 docs(eslint-plugin): document mixed codebase usage for efrt/ema
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
Labels: documentation

#951 docs(readme): Update supported TypeScript version range
  README.md
Labels: documentation

#810 feat(eslint-plugin): add brace-style [extension]
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/brace-style.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/brace-style.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/tests/rules/brace-style.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval, enhancement: new base rule extension

#954 fix(eslint-plugin): [prefer-readonly] add handling for destructuring assignments
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
Labels: bug

#952 fix(eslint-plugin): [efrt] allowExpressions - check functions in class field properties
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: bug

#974 fix(typescript-estree): ImportDeclaration.specifier to Literal
  packages/eslint-plugin/src/rules/triple-slash-reference.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#976 docs(eslint-plugin): fix typo in typedef docs
  packages/eslint-plugin/docs/rules/typedef.md
Labels: documentation

#980 fix(eslint-plugin): [pfa] Allow async getter/setter in classes
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: bug

#975 fix(eslint-plugin): [cons-type-assns] handle namespaced types
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Labels: bug

#988 fix(typescript-estree): parsing error for await in non-async func
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/await-without-async-function.src.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/semantic-or-syntactic-errors.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: bug

#995 docs(typescript-estree): correct typo
  packages/typescript-estree/README.md
Labels: documentation

#998 docs(eslint-plugin): add missing ROADMAP link
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#1007 fix(eslint-plugin): [no-unnec-type-arg] undefined symbol crash
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
Labels: bug

#1008 fix(typescript-estree): correct ClassDeclarationBase type
  packages/eslint-plugin/src/rules/indent.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#1026 fix(typescript-estree): handle optional computed prop w/o type
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/class-with-optional-properties.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: bug
