Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-05, with the labels that each got.

#416 docs: rename no-unused-expression to no-unused-expressions
  packages/eslint-plugin/ROADMAP.md
Labels: awaiting response, documentation

#488 Add eslint-recommended
  packages/eslint-plugin/src/configs/README.md
  packages/eslint-plugin/src/configs/eslint-recommended.ts
  packages/eslint-plugin/src/index.ts
Labels: enhancement, recommended-rules

#373 feat(eslint-plugin): add no-magic-numbers rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval, enhancement: new plugin rule

#499 fix(eslint-plugin): [unbound-method] Work around class prototype bug
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: bug

#502 fix(eslint-plugin): [explicit-function-return-type] Add handling for class properties
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: bug

#465 fix(eslint-plugin): Support more nodes [no-extra-parens]
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/eslint-plugin/typings/ts-eslint.d.ts
  packages/parser/package.json
  packages/typescript-estree/package.json
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#478 feat(eslint-plugin): Contextual non-null [no-unnecessary-type-assertion]
  .eslintrc.json
  packages/eslint-plugin/src/rules/member-naming.ts
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: enhancement

#442 feat(eslint-plugin): no-inferrable-types: Support more primitives
  packages/eslint-plugin/docs/rules/no-inferrable-types.md
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement

#439 feat(eslint-plugin): Begin rewrite of indent rule
  .eslintrc.json
  packages/eslint-plugin/src/rules/indent-new-do-not-use/BinarySearchTree.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/TokenInfo.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/util/applyDefault.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/fixtures/indent/indent-invalid-fixture-1.js
  packages/eslint-plugin/tests/fixtures/indent/indent-valid-fixture-1.js
  packages/eslint-plugin/tests/rules/indent/indent-eslint.test.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
  packages/eslint-plugin/tests/rules/indent/utils.ts
  packages/eslint-plugin/typings/eslint-ast-util.d.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/eslint-plugin/typings/functional-red-black-tree.d.ts
  packages/eslint-plugin/typings/ts-eslint.d.ts
  packages/typescript-estree/src/ts-estree/ast-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement

#305 feat(eslint-plugin): add prefer-regexp-exec rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-regexp-exec.md
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
Labels: 1 approval, enhancement: new plugin rule

#313 feat(eslint-plugin): add config all.json
  .prettierignore
  packages/eslint-plugin/README.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/configs/base.json
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/rules/ban-ts-ignore.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-require-imports.ts
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/configs/all.test.ts
  packages/eslint-plugin/tests/index.test.ts
  packages/eslint-plugin/tests/rules/index.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/eslint-plugin/tools/update-recommended.ts
  packages/eslint-plugin/typings/requireindex.d.ts
  yarn.lock
Labels: enhancement

#526 feat: make utils/TSESLint export typed classes instead of just types
  .eslintrc.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin-tslint/src/index.ts
  packages/eslint-plugin-tslint/src/rules/config.ts
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/eslint-recommended.ts
  packages/eslint-plugin/src/util/getParserServices.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
  packages/eslint-plugin/tests/rules/await-thenable.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/eslint-plugin/tests/rules/prefer-function-type.test.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
  packages/eslint-plugin/tests/rules/unified-signatures.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/experimental-utils/package.json
  packages/experimental-utils/src/ts-eslint/CLIEngine.ts
  packages/experimental-utils/src/ts-eslint/Linter.ts
  packages/experimental-utils/src/ts-eslint/ParserOptions.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
  packages/experimental-utils/tsconfig.build.json
  packages/experimental-utils/typings/eslint.d.ts
  packages/parser/src/parser-options.ts
  packages/parser/tests/lib/basics.ts
  packages/parser/tests/lib/parser.ts
  packages/parser/tests/lib/tsx.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/tsconfig-parser.ts
  yarn.lock
Labels: enhancement

#527 feat(experimental-utils): Add types for eslint-scope
  packages/eslint-plugin/tsconfig.json
  packages/experimental-utils/package.json
  packages/experimental-utils/src/index.ts
  packages/experimental-utils/src/ts-eslint-scope/Definition.ts
  packages/experimental-utils/src/ts-eslint-scope/Options.ts
  packages/experimental-utils/src/ts-eslint-scope/PatternVisitor.ts
  packages/experimental-utils/src/ts-eslint-scope/Reference.ts
  packages/experimental-utils/src/ts-eslint-scope/Referencer.ts
  packages/experimental-utils/src/ts-eslint-scope/Scope.ts
  packages/experimental-utils/src/ts-eslint-scope/ScopeManager.ts
  packages/experimental-utils/src/ts-eslint-scope/Variable.ts
  packages/experimental-utils/src/ts-eslint-scope/analyze.ts
  packages/experimental-utils/src/ts-eslint-scope/index.ts
  packages/experimental-utils/typings/eslint-scope.d.ts
  packages/parser/package.json
  packages/parser/src/analyze-scope.ts
  packages/parser/src/parser.ts
  packages/parser/src/scope/scope-manager.ts
  packages/parser/src/scope/scopes.ts
  packages/parser/typings/eslint-scope.d.ts
  packages/parser/typings/eslint.d.ts
Labels: enhancement

#530 chore: tighter linting
  .eslintrc.js
  .eslintrc.json
  package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/experimental-utils/package.json
  packages/experimental-utils/src/ts-eslint/CLIEngine.ts
  packages/experimental-utils/src/ts-eslint/Linter.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
  packages/parser/package.json
  packages/parser/typings/eslint.d.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/semantic-errors.ts
  packages/typescript-estree/tests/lib/parse.ts
  tests/integration/utils/generate-package-json.js
  yarn.lock
Labels: enhancement

#531 chore: Add documentation validation tool
  .prettierignore
  azure-pipelines.yml
  package.json
  packages/eslint-plugin/README.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/src/rules/ban-ts-ignore.ts
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/src/rules/class-name-casing.ts
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/src/rules/func-call-spacing.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/interface-name-prefix.ts
  packages/eslint-plugin/src/rules/member-naming.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/no-angle-bracket-type-assertion.ts
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/src/rules/no-for-in-array.ts
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/src/rules/no-misused-new.ts
  packages/eslint-plugin/src/rules/no-namespace.ts
  packages/eslint-plugin/src/rules/no-non-null-assertion.ts
  packages/eslint-plugin/src/rules/no-object-literal-type-assertion.ts
  packages/eslint-plugin/src/rules/no-parameter-properties.ts
  packages/eslint-plugin/src/rules/no-require-imports.ts
  packages/eslint-plugin/src/rules/no-this-alias.ts
  packages/eslint-plugin/src/rules/no-triple-slash-reference.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/rules/prefer-function-type.ts
  packages/eslint-plugin/src/rules/prefer-interface.ts
  packages/eslint-plugin/src/rules/prefer-namespace-keyword.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/src/rules/type-annotation-spacing.ts
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/eslint-plugin/tools/validate-docs/check-for-rule-docs.ts
  packages/eslint-plugin/tools/validate-docs/index.ts
  packages/eslint-plugin/tools/validate-docs/log.ts
  packages/eslint-plugin/tools/validate-docs/parse-readme.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-rules.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-structure.ts
  packages/experimental-utils/src/eslint-utils/RuleCreator.ts
  yarn.lock
Labels: enhancement

#551 docs(eslint-plugin): [no-extraneous-class] fix option keys
  packages/eslint-plugin/docs/rules/no-extraneous-class.md
Labels: documentation

#545 docs(experimental-utils): fix table links
  packages/experimental-utils/README.md
Labels: documentation
