Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-10, with the labels that each got.

#1043 fix(eslint-plugin): [class-name-casing] allow unicode letters
  packages/eslint-plugin/src/rules/class-name-casing.ts
  packages/eslint-plugin/tests/rules/class-name-casing.test.ts
Labels: bug

#1021 fix(eslint-plugin): [efrt] support constructor arguments
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: bug

#1047 fix(eslint-plugin): Add missing rule functions
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/parser/src/visitor-keys.ts
  packages/typescript-estree/src/ts-estree/ast-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement

#1023 fix(eslint-plugin): [promise-function-async] Should not report for returned union types containing non-promise
  packages/eslint-plugin/docs/rules/promise-function-async.md
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: bug

#838 docs: add TOC to root README
  README.md
Labels: documentation

#973 fix: support long running "watch" lint sessions
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin-tslint/tsconfig.build.json
  packages/eslint-plugin-tslint/tsconfig.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tsconfig.build.json
  packages/eslint-plugin/tsconfig.json
  packages/experimental-utils/package.json
  packages/experimental-utils/src/ts-eslint/ParserOptions.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  packages/experimental-utils/tsconfig.build.json
  packages/experimental-utils/tsconfig.json
  packages/parser/package.json
  packages/parser/src/parser.ts
  packages/parser/tests/lib/jsx.ts
  packages/parser/tsconfig.build.json
  packages/parser/tsconfig.json
  packages/typescript-estree/package.json
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/tsconfig-parser.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/jsx.ts
  packages/typescript-estree/tests/lib/parse.ts
  packages/typescript-estree/tests/lib/persistentParse.ts
  packages/typescript-estree/tsconfig.build.json
  packages/typescript-estree/tsconfig.json
  tsconfig.eslint.json
  yarn.lock
Labels: bug

#990 chore: declare TypeScript as an optional peerDependency
  packages/eslint-plugin/package.json
  packages/typescript-estree/package.json
Labels: dependencies

#1004 feat(eslint-plugin): Support abstract members in member-ordering rule (#395)
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option

#1088 fix(typescript-estree): handle running out of fs watchers
  packages/typescript-estree/README.md
  packages/typescript-estree/package.json
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/tsconfig-parser.ts
  yarn.lock
Labels: bug

#1072 fix(eslint-plugin): [no-magic-numbers] Support negative numbers
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
Labels: bug

#1106 feat(typescript-estree): support long running lint without watch
  .vscode/launch.json
  packages/eslint-plugin/tests/RuleTester.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/tsconfig-parser.ts
  packages/typescript-estree/tests/fixtures/invalidFileErrors/tsconfig.json
  packages/typescript-estree/tests/lib/parse.ts
  packages/typescript-estree/tests/lib/persistentParse.ts
  packages/typescript-estree/tests/lib/semanticInfo.ts
Labels: enhancement

#1083 fix(typescript-estree): parsing error for vue sfc
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  tests/integration/fixtures/vue-sfc/.eslintrc.yml
  tests/integration/fixtures/vue-sfc/World.vue
  tests/integration/fixtures/vue-sfc/test.js.snap
  tests/integration/fixtures/vue-sfc/test.sh
  tests/integration/fixtures/vue-sfc/tsconfig.json
Labels: bug

#1111 fix(typescript-estree): better handle canonical paths
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/tests/lib/persistentParse.ts
  packages/typescript-estree/tests/lib/semanticInfo.ts
Labels: bug

#1128 fix(typescript-estree): normalize paths to fix cache miss on windows
  packages/typescript-estree/src/create-program/shared.ts
Labels: bug

#1136 feat(typescript-estree): add support for declare class properties
  packages/eslint-plugin/src/rules/indent.ts
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/abstract-class-with-declare-properties.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/class-with-declare-properties.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semanticInfo.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: enhancement

#1141 fix(typescript-estree): correct parenthesized optional chain AST
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-call-with-parens.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-call.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-element-access-with-parens.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-with-parens.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: bug

#1129 fix(typescript-estree): ensure parent pointers are set
  packages/typescript-estree/src/create-program/WatchCompilerHostOfConfigFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
Labels: bug

#1147 docs(eslint-plugin): [no-unnecessary-condition] tweak wording
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
Labels: documentation

#1156 fix(typescript-estree): don't use typescript's synthetic default
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
Labels: bug
