Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-11, with the labels that each got.

#1120 fix(typescript-estree): improve comment parsing code
  packages/typescript-estree/package.json
  packages/typescript-estree/src/convert-comments.ts
  packages/typescript-estree/src/node-utils.ts
Labels: bug

#1179 fix(typescript-estree): hash code to reduce update frequency
  packages/typescript-estree/src/create-program/createWatchProgram.ts
Labels: bug

#1169 feat(parser): handle optional chaining in scope analysis
  packages/eslint-plugin/tests/eslint-rules/no-restricted-globals.test.ts
  packages/eslint-plugin/tests/eslint-rules/no-undef.test.ts
  packages/eslint-plugin/tests/eslint-rules/no-use-before-define.test.ts
  packages/parser/src/analyze-scope.ts
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
Labels: enhancement

#1175 feat(eslint-plugin): [no-unused-expressions] extend for optional chaining
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unused-expressions.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
  packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#565 feat(eslint-plugin): added new rule no-dynamic-delete
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-dynamic-delete.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-dynamic-delete.ts
  packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
Labels: enhancement: new plugin rule

#704 fix(typescript-estree): options range loc being always true
  packages/parser/src/analyze-scope.ts
  packages/parser/src/parser.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/simple-traverse.ts
  packages/typescript-estree/src/visitor-keys.ts
  packages/typescript-estree/tests/lib/__snapshots__/parse.ts.snap
  packages/typescript-estree/tests/lib/parse.ts
  packages/typescript-estree/tests/lib/visitor-keys.ts
Labels: bug

#801 feat(eslint-plugin): added new rule no-untyped-public-signature
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-untyped-public-signature.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
  packages/eslint-plugin/tests/rules/no-untyped-public-signature.test.ts
Labels: enhancement: new plugin rule

#1198 fix(eslint-plugin): [no-type-alias] handle constructor aliases
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: bug

#1202 docs(eslint-plugin): brace-style as a replacement for one-line
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#924 feat(eslint-plugin): add space-before-function-paren [extension]
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/space-before-function-paren.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/space-before-function-paren.ts
  packages/eslint-plugin/tests/rules/space-before-function-paren.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
Labels: 1 approval, enhancement: new base rule extension

#1204 fix(eslint-plugin): [camelcase] handle optional member expr
  packages/eslint-plugin/src/rules/camelcase.ts
  packages/eslint-plugin/tests/rules/camelcase.test.ts
Labels: bug

#953 feat(eslint-plugin): [no-type-alias] handle conditional types
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: enhancement: plugin rule option

#1207 fix(eslint-plugin): [no-unnecessary-cond] fix naked type param
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#1189 fix(eslint-plugin): [indent] fix decorator type
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
Labels: bug

#1208 chore: bump dependencies
  .all-contributorsrc
  CONTRIBUTORS.md
  package.json
  packages/eslint-plugin/docs/rules/array-type.md
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/interface-name-prefix.ts
  packages/eslint-plugin/src/rules/space-before-function-paren.ts
  packages/eslint-plugin/src/rules/triple-slash-reference.ts
  packages/eslint-plugin/tools/validate-docs/parse-readme.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/experimental-utils/src/eslint-utils/deepMerge.ts
  packages/experimental-utils/src/index.ts
  packages/parser/package.json
  packages/typescript-estree/package.json
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/lib/parse.ts
  tools/generate-contributors.ts
  yarn.lock
Labels: dependencies

#1211 fix(eslint-plugin): [indent] handle empty generic declarations
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
Labels: bug

#1096 fix(eslint-plugin): [unified-signatures] crash: cannot read property 'name' of null
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/eslint-plugin/tests/rules/unified-signatures.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#1201 fix(eslint-plugin): [nuta] correctly handle null/undefined separation
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: bug

#1193 fix(eslint-plugin): [require-await] better handle nesting
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
Labels: bug

#1205 fix(typescript-estree): correctly account for trailing slash in includes
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/tests/lib/persistentParse.ts
Labels: bug

#1217 fix(eslint-plugin): [no-unnec-type-arg] throwing on call/new expr
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
Labels: bug

#850 feat(eslint-plugin): add rule restrict-template-expressions
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: 1 approval, enhancement: new plugin rule

#1183 feat(eslint-plugin): add no-extra-non-null-assertion
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-extra-non-null-assertion.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-extra-non-null-assertion.ts
  packages/eslint-plugin/tests/rules/no-extra-non-null-assertion.test.ts
Labels: 1 approval, enhancement: new plugin rule

#1230 docs(eslint-plugin): fix title in no-unused-expressions docs
  packages/eslint-plugin/docs/rules/no-unused-expressions.md
Labels: documentation

#1228 fix(eslint-plugin): [req-await] crash on nonasync promise return
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: bug

#886 feat(eslint-plugin): [no-extran-class] add allowWithDecorator opt
  packages/eslint-plugin/docs/rules/no-extraneous-class.md
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
Labels: 1 approval, enhancement: plugin rule option

#1231 fix(eslint-plugin): [no-untyped-pub-sig] constructor return
  packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
  packages/eslint-plugin/tests/rules/no-untyped-public-signature.test.ts
Labels: bug

#1244 fix(eslint-plugin): [no-dynamic-delete] prevent fixing to identifiers
  packages/eslint-plugin/src/rules/no-dynamic-delete.ts
  packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
Labels: bug

#1245 fix(typescript-estree): fix synthetic default import
  packages/typescript-estree/src/visitor-keys.ts
Labels: bug

#892 feat(eslint-plugin): [restrict-plus-operands] check +=
  packages/eslint-plugin/docs/rules/restrict-plus-operands.md
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
Labels: 1 approval, enhancement: plugin rule option

#1029 feat(eslint-plugin): [no-unnece-cond] Add allowConstantLoopConditions
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: enhancement: plugin rule option

#925 feat(eslint-plugin): [camelcase] add genericType option
  packages/eslint-plugin/docs/rules/camelcase.md
  packages/eslint-plugin/src/rules/camelcase.ts
  packages/eslint-plugin/tests/rules/camelcase.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: plugin rule option

#1251 docs(eslint-plugin): correct typo in configs README
  packages/eslint-plugin/src/configs/README.md
Labels: documentation

#1252 docs(eslint-plugin): fix typo in no-this-alias
  packages/eslint-plugin/docs/rules/no-this-alias.md
Labels: documentation

#1250 feat: suggestion types, suggestions for no-explicit-any
  package.json
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  tests/integration/README.md
  tests/integration/fixtures/markdown/test.js.snap
  tests/integration/fixtures/vue-jsx/test.js.snap
  tests/integration/fixtures/vue-sfc/test.js.snap
  yarn.lock
Labels: enhancement

#1213 feat(eslint-plugin): add rule prefer-optional-chain
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement: new plugin rule

#688 feat(eslint-plugin): add no-unused-vars-experimental
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unused-vars-experimental.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.json
  packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
  packages/eslint-plugin/tools/validate-docs/validate-table-structure.ts
  packages/typescript-estree/src/create-program/shared.ts
Labels: enhancement: new plugin rule

#1050 feat(eslint-plugin): add return-await rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/return-await.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
  tools/generate-contributors.ts
Labels: 1 approval, enhancement: new plugin rule

#1253 feat(eslint-plugin): optional chain support in rules (part 1)
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/func-call-spacing.ts
  packages/eslint-plugin/src/rules/no-array-constructor.ts
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-require-imports.ts
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
  packages/eslint-plugin/tests/rules/func-call-spacing.test.ts
  packages/eslint-plugin/tests/rules/no-array-constructor.test.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
  packages/eslint-plugin/tests/rules/no-require-imports.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
  packages/eslint-plugin/tests/rules/no-var-requires.test.ts
  packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
  packages/eslint-plugin/tests/rules/prefer-includes.test.ts
Labels: enhancement

#1247 feat(eslint-plugin): [no-empty-interface] noEmptyWithSuper fixer
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
Labels: enhancement: plugin rule option

#1069 feat(eslint-plugin): add prefer-nullish-coalescing
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement: new plugin rule

#1264 fix(eslint-plugin): [no-untyped-pub-sig] ignore set return
  packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
  packages/eslint-plugin/tests/rules/no-untyped-public-signature.test.ts
Labels: bug

#1261 fix(eslint-plugin): [prefer-optional-chain] handle more cases
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/src/util/nullThrows.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: bug

#1268 feat(experimental-utils): add isSpaceBetween declaration to SourceCode
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
Labels: enhancement

#1267 feat(eslint-plugin): [no-empty-func] private/protected construct
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/tests/rules/no-empty-function.test.ts
Labels: enhancement: plugin rule option

#1270 fix(eslint-plugin): [return-await] allow Any and Unknown
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug

#1275 fix(eslint-plugin): [strict-bool-expr] allow nullish coalescing
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: bug

#1288 fix(typescript-estree): make FunctionDeclaration.body non-null
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#1272 feat(eslint-plugin): [prefer-null-coal] opt for suggestion fixer
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: enhancement: plugin rule option

#1285 fix(eslint-plugin): [no-unused-expressions] ignore directives
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
  packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#1260 feat(eslint-plugin): [no-non-null-assert] add suggestion fixer
  packages/eslint-plugin/src/rules/no-non-null-assertion.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/no-non-null-assertion.test.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: enhancement: plugin rule option
