Repository typescript-eslint/typescript-eslint, pull requests merged in 2019-12, with the labels that each got.

#1148 feat(eslint-plugin): [no-unnec-cond] support nullish coalescing
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: enhancement

#1295 docs(eslint-plugin): typo in the configs README
  packages/eslint-plugin/src/configs/README.md
Labels: documentation

#1297 docs(eslint-plugin): typo in space-before-function-paren docs
  packages/eslint-plugin/docs/rules/space-before-function-paren.md
Labels: documentation

#1074 test(eslint-plugin): [unified-signatures] add tests for #740
  packages/eslint-plugin/tests/rules/unified-signatures.test.ts
Labels: tests

#1190 feat(eslint-plugin): [member-ordering] add index signature
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option

#1281 fix(eslint-plugin): [brace-style] handle enum declarations
  packages/eslint-plugin/src/rules/brace-style.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/brace-style.test.ts
Labels: bug

#1319 docs(eslint-plugin): ROADMAP note some jsdoc rules
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#1327 chore(parser): mark TS as optional peer dependency
  packages/parser/package.json
Labels: dependencies

#1311 fix(eslint-plugin): [quotes] ignore `backticks` for interface properties
  packages/eslint-plugin/src/rules/quotes.ts
  packages/eslint-plugin/tests/rules/quotes.test.ts
Labels: bug

#1326 fix(eslint-plugin): [prefer-null-coal] fixer w/ mixed logicals
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: bug

#1315 feat(eslint-plugin): [no-unnec-cond] check optional chaining
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: enhancement: plugin rule option

#1332 chore(types): improve typing for getTokenType and convertBodyExpressions
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
Labels: package: typescript-estree

#1336 chore(types): Improve types for getTextForTokenKind
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: package: typescript-estree

#1343 test(typescript-estree): Update alignment tests
  packages/typescript-estree/package.json
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  yarn.lock
Labels: dependencies, package: typescript-estree, tests

#1342 feat(eslint-plugin-tslint): add fixer for config rule
  packages/eslint-plugin-tslint/src/rules/config.ts
  packages/eslint-plugin-tslint/tests/index.spec.ts
  tests/integration/fixtures/typescript-and-tslint-plugins-together/test.js.snap
Labels: package: eslint-plugin-tslint

#1344 docs(parser): fix effect->affect in readme
  packages/parser/README.md
Labels: documentation

#1347 docs: fix typo in getting started doc
  docs/getting-started/linting/README.md
Labels: documentation

#1346 feat(typescript-estree): tighten prop name and destructure types
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/src/rules/member-naming.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement

#1352 docs: add links to the contributing guide everywhere
  README.md
  packages/eslint-plugin-tslint/README.md
  packages/eslint-plugin/README.md
  packages/experimental-utils/README.md
  packages/parser/README.md
  packages/typescript-estree/README.md
Labels: documentation

#1242 feat(eslint-plugin): [no-use-before-define] opt to ignore enum
  packages/eslint-plugin/docs/rules/no-use-before-define.md
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
Labels: enhancement: plugin rule option

#1353 test: use codecov bash uploader instead of js uploader
  azure-pipelines.yml
Labels: tests

#1349 feat(typescript-estree): computed members discriminated unions
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/export-named-enum-computed-number.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/export-named-enum-computed-string.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/export-named-enum-computed-var-ref.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/new-target-in-arrow-function-body.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/semantic-or-syntactic-errors.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: enhancement

#1237 feat(eslint-plugin): add no-extra-semi [extension]
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-extra-semi.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-extra-semi.ts
  packages/eslint-plugin/tests/rules/no-extra-semi.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#1331 feat(eslint-plugin): add no-throw-literal [extension]
  .eslintrc.js
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-throw-literal.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-throw-literal.ts
  packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
Labels: enhancement: new plugin rule

#1355 fix(eslint-plugin): [quotes] ignore backticks for Enum members
  packages/eslint-plugin/src/rules/quotes.ts
  packages/eslint-plugin/tests/rules/quotes.test.ts
Labels: bug

#1348 feat(eslint-plugin): [ban-types] handle empty type literal {}
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: awaiting response, enhancement: plugin rule option

#1360 docs(eslint-plugin): [no-unnec-type-arg] correct doc title
  packages/eslint-plugin/docs/rules/no-unnecessary-type-arguments.md
Labels: documentation

#1367 fix(typescript-estree): correct type of key for base nodes
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug, package: typescript-estree

#1357 feat(eslint-plugin): [pref-str-starts/ends-with] optional chain support
  packages/eslint-plugin/src/rules/no-require-imports.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
  packages/eslint-plugin/typings/eslint-utils.d.ts
Labels: enhancement

#1363 feat(eslint-plugin): more optional chain support in rules
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/require-array-sort-compare.test.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: enhancement

#1368 test(typescript-estree): reenable alignment tests
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
Labels: package: typescript-estree, tests

#1369 fix(eslint-plugin): add isTypeAssertion utility function
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/src/util/astUtils.ts
Labels: bug

#1364 docs: grammar nits in the root README
  README.md
Labels: documentation

#1370 test(typescript-estree): add test cases for uncovered syntax
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/abstract-class-with-abstract-static-constructor.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/interface-with-all-property-types.src.ts
  packages/shared-fixtures/fixtures/typescript/errorRecovery/interface-with-optional-index-signature.src.ts
  packages/shared-fixtures/fixtures/typescript/types/mapped-untypped.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
  packages/typescript-estree/tests/lib/convert.ts
Labels: package: parser, package: typescript-estree, tests

#1371 refactor(typescript-estree): add type checking for deeplyCopy
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
Labels: package: typescript-estree

#1373 feat: add internal eslint plugin for repo-specific lint rules
  .eslintrc.js
  .vscode/launch.json
  packages/eslint-plugin-internal/README.md
  packages/eslint-plugin-internal/jest.config.js
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-internal/src/index.ts
  packages/eslint-plugin-internal/src/rules/index.ts
  packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
  packages/eslint-plugin-internal/src/rules/no-typescript-estree-import.ts
  packages/eslint-plugin-internal/src/util/createRule.ts
  packages/eslint-plugin-internal/src/util/index.ts
  packages/eslint-plugin-internal/tests/RuleTester.ts
  packages/eslint-plugin-internal/tests/rules/no-typescript-default-import.test.ts
  packages/eslint-plugin-internal/tests/rules/no-typescript-estree.test.ts
  packages/eslint-plugin-internal/tsconfig.build.json
  packages/eslint-plugin-internal/tsconfig.json
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/src/rules/no-for-in-array.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/src/util/types.ts
  packages/experimental-utils/package.json
  packages/typescript-estree/src/convert-comments.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/WatchCompilerHostOfConfigFile.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/semantic-or-syntactic-errors.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/lib/convert.ts
  packages/typescript-estree/tests/lib/semanticInfo.ts
  yarn.lock
Labels: enhancement

#1376 fix(eslint-plugin): type assertion in rule no-extra-parens
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
Labels: bug

#1377 fix(parser): allow to visit typeParameters in OptionalCallExpression
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/expressions/optional-call-expression-type-arguments.src.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/visitor-keys.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: bug

#1381 refactor: TypeParameter parsing and no-unnecessary-type-arguments rule
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
  packages/typescript-estree/src/convert.ts
Labels: package: eslint-plugin, package: typescript-estree, tests

#1384 docs(eslint-plugin): [no-throw-literal] wrong link
  packages/eslint-plugin/docs/rules/no-throw-literal.md
Labels: documentation

#1386 chore: migrate markdown-spellcheck to cspell
  .cspell.json
  .spelling
  .vscode/extensions.json
  CONTRIBUTING.md
  package.json
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
  packages/eslint-plugin/docs/rules/member-delimiter-style.md
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/docs/rules/no-unused-vars-experimental.md
  packages/eslint-plugin/docs/rules/prefer-readonly.md
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/src/rules/member-delimiter-style.ts
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/indent/indent-eslint.test.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/experimental-utils/src/eslint-utils/deepMerge.ts
  packages/experimental-utils/src/index.ts
  packages/experimental-utils/src/ts-eslint-scope/Scope.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  packages/parser/src/analyze-scope.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/persistentParse.ts
  yarn.lock
Labels: dependencies, tests

#1385 feat(eslint-plugin): [strict-bool-expr] add allowSafe option
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: enhancement: plugin rule option
