Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-11, with the labels that each got.

#2716 docs(eslint-plugin): [consistent-type-imports] note that it can't be used for decorator metadata
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
Labels: documentation

#2729 fix(eslint-plugin): [no-shadow] ignore global module augmentation
  packages/eslint-plugin/docs/rules/no-shadow.md
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
Labels: bug

#2722 fix(eslint-plugin): [consistent-indexed-object-style] fix wrong autofix behaviour with generics
  packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
  packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Labels: bug

#2605 feat(eslint-plugin): add rule `no-void-expression`
  .eslintrc.js
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-confusing-void-expression.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/tests/rules/no-confusing-void-expression.test.ts
Labels: enhancement: new plugin rule

#2737 fix(eslint-plugin): [no-extra-non-null-assertion] false positive with non-nullable computed key
  packages/eslint-plugin/src/rules/no-extra-non-null-assertion.ts
  packages/eslint-plugin/tests/rules/no-extra-non-null-assertion.test.ts
Labels: bug

#2745 docs(eslint-plugin): Move no-implied-eval & no-throw-literal to Extension Rules
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-invalid-this.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/recommended-requiring-type-checking.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/src/rules/no-throw-literal.ts
Labels: documentation

#2747 fix(eslint-plugin): [array-type] parenthesize ReadonlyArray fix
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: bug

#2748 feat: support TS4.1 features
  .prettierignore
  package.json
  packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
  packages/scope-manager/src/lib/dom.iterable.ts
  packages/scope-manager/src/lib/dom.ts
  packages/scope-manager/src/lib/es2015.iterable.ts
  packages/scope-manager/src/lib/es2020.sharedmemory.ts
  packages/scope-manager/src/lib/es2020.ts
  packages/scope-manager/src/lib/es5.ts
  packages/scope-manager/src/lib/esnext.ts
  packages/scope-manager/src/lib/esnext.weakref.ts
  packages/scope-manager/src/lib/index.ts
  packages/scope-manager/src/lib/webworker.iterable.ts
  packages/scope-manager/src/lib/webworker.ts
  packages/scope-manager/tests/fixtures/type-declaration/literal-type1.ts
  packages/scope-manager/tests/fixtures/type-declaration/literal-type1.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/literal-type2.ts
  packages/scope-manager/tests/fixtures/type-declaration/literal-type2.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/literal-type3.ts
  packages/scope-manager/tests/fixtures/type-declaration/literal-type3.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/mapped-named.ts
  packages/scope-manager/tests/fixtures/type-declaration/mapped-named.ts.shot
  packages/shared-fixtures/fixtures/typescript/types/mapped-named-type.src.ts
  packages/shared-fixtures/fixtures/typescript/types/template-literal-type-1.src.ts
  packages/shared-fixtures/fixtures/typescript/types/template-literal-type-2.src.ts
  packages/shared-fixtures/fixtures/typescript/types/template-literal-type-3.src.ts
  packages/shared-fixtures/fixtures/typescript/types/template-literal-type-4.src.ts
  packages/types/src/ast-node-types.ts
  packages/types/src/index.ts
  packages/types/src/lib.ts
  packages/types/src/ts-estree.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/types/mapped-named-type.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/mapped-readonly-minus.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/mapped-readonly-plus.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/mapped-readonly.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/mapped-untypped.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/mapped.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/template-literal-type-1.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/template-literal-type-2.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/template-literal-type-3.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/template-literal-type-4.src.ts.shot
  packages/visitor-keys/src/visitor-keys.ts
  yarn.lock
Labels: AST, enhancement

#2754 test(typescript-estree): [babel alignment] remove now unnecessary AST transformation for ImportDeclaration
  packages/typescript-estree/tests/ast-alignment/utils.ts
Labels: tests

#2753 fix(eslint-plugin): [no-unsafe-member-access] ignore MemberExpression's whose parents are either TSClassImplements or TSInterfaceHeritage
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
Labels: bug

#2760 feat(typescript-estree): add `parseWithNodeMaps` API
  packages/typescript-estree/README.md
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/parse.test.ts
Labels: enhancement

#2739 fix(eslint-plugin): [consistent-type-definitions] remove fixer when the interface is within a global module declaration
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
Labels: bug

#2773 fix(typescript-estree): parseWithNodeMaps returning empty maps
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/parse.test.ts
Labels: bug

#2772 fix(eslint-plugin): [no-unnecessary-condition] false positive when array predicate returns unknown
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#2758 docs(eslint-plugin): [ban-types] add reference on how to type an empty object
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
Labels: documentation

#2786 fix(eslint-plugin): [prefer-literal-enum-member] allow pure template literal strings
  packages/eslint-plugin/src/rules/prefer-literal-enum-member.ts
  packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
Labels: bug

#2789 fix(typescript-estree): fix type-only regression for consumers not yet on TS 4.1
  package.json
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  yarn.lock
Labels: bug

#2768 feat(eslint-plugin): [no-unused-vars] fork the base rule
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/experimental-utils/src/ast-utils/predicates.ts
  packages/experimental-utils/src/eslint-utils/InferTypesFromRule.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  packages/experimental-utils/src/ts-eslint/Scope.ts
  packages/scope-manager/src/referencer/VisitorBase.ts
  packages/types/src/ts-estree.ts
Labels: enhancement

#2807 feat(eslint-plugin): [naming-convention] split `property` and `method` selectors into more granular `classXXX`, `objectLiteralXXX`, `typeXXX`
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option

#2808 feat(eslint-plugin): [naming-convention] add modifiers `exported`, `global`, and `destructured`
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option

#2806 docs: update supported TS versions to include 4.1
  README.md
Labels: documentation

#2809 fix(scope-manager): fix assertion assignments not being marked as write references
  packages/eslint-plugin/tests/eslint-rules/prefer-const.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/type-assertion/assignment/angle-bracket-assignment.ts
  packages/scope-manager/tests/fixtures/type-assertion/assignment/angle-bracket-assignment.ts.shot
  packages/scope-manager/tests/fixtures/type-assertion/assignment/as-assignment.ts
  packages/scope-manager/tests/fixtures/type-assertion/assignment/as-assignment.ts.shot
  packages/scope-manager/tests/fixtures/type-assertion/assignment/non-null-assignment.ts
  packages/scope-manager/tests/fixtures/type-assertion/assignment/non-null-assignment.ts.shot
Labels: bug

#2810 feat(eslint-plugin): [naming-convention] add modifier `unused`
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option

#2812 feat(eslint-plugin): [naming-convention] add `requireDouble`, `allowDouble`, `allowSingleOrDouble` options for underscores
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option

#2813 feat(eslint-plugin): [naming-convention] add `requiresQuotes` modifier
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/requiresQuoting.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option

#2765 test: fix jest config on windows
  packages/scope-manager/jest.config.js
  packages/types/jest.config.js
  packages/typescript-estree/jest.config.js
  packages/visitor-keys/jest.config.js
Labels: tests

#2778 fix(eslint-plugin): [consistent-type-imports] crash when using both default and namespace in one import
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
Labels: bug

#2788 fix(eslint-plugin): [triple-slash-reference] fix crash with external module reference
  packages/eslint-plugin/src/rules/triple-slash-reference.ts
  packages/eslint-plugin/tests/rules/triple-slash-reference.test.ts
Labels: bug

#2805 fix(eslint-plugin): [explicit-module-boundary-types] ignore functions exported within typed object/array literals
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#2798 fix(eslint-plugin): [consistent-indexed-object-style] convert readonly index signature to readonly record
  packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
  packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Labels: bug

#2796 feat(eslint-plugin): [unbound-method] add support for methods with a `this: void` parameter
  packages/eslint-plugin/docs/rules/unbound-method.md
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: enhancement: plugin rule option

#2816 chore(eslint-plugin): [naming-convention] refactor rule to split it up
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention-utils/enums.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/format.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/index.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/parse-options.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/schema.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/shared.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/types.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: refactor

#2819 fix(typescript-estree): add default value for `parserOptions.projectFolderIgnoreList` and deduplicate resolved projects
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
Labels: bug

#2827 fix(eslint-plugin): [no-use-before-define] allow class references if they're within a class decorator
  .cspell.json
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
Labels: bug

#2829 feat(eslint-plugin): [naming-convention] allow `destructured` modifier for `parameter` selector
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention-utils/schema.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option
