Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-03, with the labels that each got.

#1496 feat(eslint-plugin): additional annotation spacing rules for variables, parameters, properties, return types
  packages/eslint-plugin/docs/rules/type-annotation-spacing.md
  packages/eslint-plugin/src/rules/type-annotation-spacing.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
Labels: enhancement: plugin rule option

#1513 feat(eslint-plugin): add prefer-readonly-parameters
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/isTypeReadonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/eslint-plugin/typings/typescript.d.ts
Labels: enhancement: new plugin rule

#1661 docs(eslint-plugin): [no-base-to-string] fix typo
  packages/eslint-plugin/docs/rules/no-base-to-string.md
Labels: documentation

#1643 feat(eslint-plugin): add rule no-unsafe-member-access
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-unsafe-member-access.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
Labels: enhancement: new plugin rule

#1662 fix(eslint-plugin): [no-unnecessary-condition] fix autofixer for computed properties
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#1644 feat(eslint-plugin): add rule no-unsafe-return
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unsafe-return.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
  packages/eslint-plugin/tests/util/isUnsafeAssignment.test.ts
Labels: blocked by another PR, enhancement: new plugin rule

#1647 feat(eslint-plugin): add rule no-unsafe-call
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unsafe-call.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
Labels: enhancement: new plugin rule

#1664 fix(eslint-plugin): [type-annotation-spacing] handle constructor types
  packages/eslint-plugin/src/rules/type-annotation-spacing.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
Labels: bug

#1672 fix(eslint-plugin): [prefer-readonly-parameter-types] handle recursive types
  packages/eslint-plugin/src/util/isTypeReadonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
Labels: bug

#1702 docs(eslint-plugin): [no-namespace] fix typo
  packages/eslint-plugin/docs/rules/no-namespace.md
Labels: documentation

#1696 chore: bump typescript dependency to 3.8
  package.json
  packages/parser/tests/lib/__snapshots__/jsx.ts.snap
  packages/parser/tests/lib/__snapshots__/tsx.ts.snap
  packages/shared-fixtures/fixtures/jsx/member-expression-private.src.js
  packages/shared-fixtures/fixtures/tsx/generic-jsx-member-expression-private.src.tsx
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/lib/__snapshots__/jsx.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/tsx.ts.snap
  yarn.lock
Labels: dependencies

#1703 fix(eslint-plugin): fix placeholder in `ban-ts-comment`
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Labels: bug

#1680 feat(eslint-plugin): [no-unsafe-call] support tagged templates
  packages/eslint-plugin/docs/rules/no-unsafe-call.md
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
Labels: enhancement

#1683 feat(eslint-plugin): [no-unsafe-member-access] report any typed computed prop access
  packages/eslint-plugin/docs/rules/no-unsafe-member-access.md
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
Labels: enhancement

#1697 feat(typescript-estree): support 3.8 import/export type
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/export-type-as.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/export-type-from-as.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/export-type-from.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/export-type-star-from.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/export-type.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/import-type-default.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/import-type-empty.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/import-type-error.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/import-type-named-as.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/import-type-named.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/import-type-star-as-ns.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/type-alias-declaration-export-function-type.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/type-alias-declaration-export-object-type.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/type-alias-declaration-export.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/type-import-type-with-type-parameters-in-type-reference.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/type-import-type.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semanticInfo.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/tsx.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: enhancement

#1698 feat(typescript-estree): support 3.8 `export * as ns`
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/export-star-as-ns-from.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: enhancement

#1720 docs(eslint-plugin): Typo in no-unsafe-member-access
  packages/eslint-plugin/docs/rules/no-unsafe-member-access.md
Labels: documentation

#1693 fix: unecessary program updates by removing timeout methods
  packages/typescript-estree/src/create-program/createWatchProgram.ts
Labels: bug

#1383 chore: migrate build from azure-pipelines to actions
  .github/workflows/ci.yml
  README.md
Labels: DO NOT MERGE, RFC

#1719 fix(eslint-plugin-tslint): fix tslintConfig memoization key
  packages/eslint-plugin-tslint/src/rules/config.ts
Labels: bug

#1760 chore: standardise issue templates
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
Labels: documentation

#1751 fix(typescript-estree): export * regression from 133f622f
  packages/typescript-estree/src/convert.ts
Labels: 1 approval, bug

#1741 fix(eslint-plugin): [no-unnec-type-assertion] allow const assertions
  packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: 1 approval, bug

#1755 fix(eslint-plugin): fix message of no-base-to-string
  packages/eslint-plugin/src/rules/no-base-to-string.ts
Labels: 1 approval, bug

#1769 fix(eslint-plugin): [quotes] false positive with backtick in import equals statement
  packages/eslint-plugin/src/rules/quotes.ts
  packages/eslint-plugin/tests/rules/quotes.test.ts
Labels: bug

#1534 feat(eslint-plugin): [no-unnecessary-condition] ignore basic array indexing false positives
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: enhancement

#1670 feat(experimental-utils): expose ast utility functions
  .cspell.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/comma-spacing.ts
  packages/eslint-plugin/src/rules/func-call-spacing.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/no-array-constructor.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/src/rules/space-before-function-paren.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/typings/eslint-utils.d.ts
  packages/experimental-utils/README.md
  packages/experimental-utils/package.json
  packages/experimental-utils/src/ast-utils/eslint-utils/PatternMatcher.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/astUtilities.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/index.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/scopeAnalysis.ts
  packages/experimental-utils/src/ast-utils/index.ts
  packages/experimental-utils/src/ast-utils/misc.ts
  packages/experimental-utils/src/ast-utils/predicates.ts
  packages/experimental-utils/src/eslint-utils/RuleCreator.ts
  packages/experimental-utils/src/eslint-utils/applyDefault.ts
  packages/experimental-utils/src/eslint-utils/deepMerge.ts
  packages/experimental-utils/src/eslint-utils/getParserServices.ts
  packages/experimental-utils/src/index.ts
  packages/experimental-utils/src/ts-eslint-scope/Definition.ts
  packages/experimental-utils/src/ts-eslint-scope/Options.ts
  packages/experimental-utils/src/ts-eslint-scope/PatternVisitor.ts
  packages/experimental-utils/src/ts-eslint-scope/Reference.ts
  packages/experimental-utils/src/ts-eslint-scope/Referencer.ts
  packages/experimental-utils/src/ts-eslint-scope/Scope.ts
  packages/experimental-utils/src/ts-eslint-scope/ScopeManager.ts
  packages/experimental-utils/src/ts-eslint-scope/Variable.ts
  packages/experimental-utils/src/ts-eslint/AST.ts
  packages/experimental-utils/src/ts-eslint/Linter.ts
  packages/experimental-utils/src/ts-eslint/ParserOptions.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
  packages/experimental-utils/src/ts-eslint/Scope.ts
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
  packages/experimental-utils/src/ts-estree.ts
  packages/experimental-utils/typings/eslint-utils.d.ts
  yarn.lock
Labels: enhancement, refactor

#1582 feat(eslint-plugin): add `class-literal-property-style` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/class-literal-property-style.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
Labels: 1 approval, enhancement: new plugin rule

#1787 docs: title wording in root readme
  README.md
Labels: documentation

#1791 docs(eslint-plugin): [prefer-readonly-parameter-types] fix invalid example
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
Labels: documentation

#1800 fix(eslint-plugin): [no-unsafe-call] allow import expressions
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
Labels: bug

#1796 fix(eslint-plugin): [no-explicit-any] error with ignoreRestArgs option
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
Labels: bug

#1809 feat(eslint-plugin-tslint): support tslint 6
  package.json
  packages/eslint-plugin-tslint/package.json
  yarn.lock
Labels: dependencies

#1802 feat(typescript-estree): add option to ignore certain folders from glob resolution
  packages/experimental-utils/src/ts-eslint/ParserOptions.ts
  packages/parser/README.md
  packages/typescript-estree/README.md
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/ignoreme/file.ts
  packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/ignoreme/tsconfig.json
  packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/includeme/file.ts
  packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/includeme/tsconfig.json
  packages/typescript-estree/tests/lib/parse.ts
  tsconfig.eslint.json
Labels: enhancement

#1815 fix(eslint-plugin): [no-unsafe-return] error with <TS3.7
  packages/eslint-plugin/src/util/types.ts
Labels: bug

#1801 chore: separate linting checks to their own step
  .cspell.json
  .github/workflows/ci.yml
Labels: repo maintenance

#1816 docs(eslint-plugin): add missing invalid-void link to ROADMAP.md
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#1821 feat(eslint-plugin-internal): add plugin-test-formatting rule
  .prettierrc.json
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-internal/src/rules/index.ts
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tools/generate-configs.ts
Labels: repo maintenance

#1826 fix(eslint-plugin): [no-unsafe-call] fix incorrect selector
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
Labels: bug

#1782 fix(eslint-plugin): [require-await] handle async generators
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
Labels: 1 approval, bug
