Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-12, with the labels that each got.

#2832 docs(eslint-plugin): [no-unnecessary-boolean-literal-compare] add warning message
  packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.md
Labels: documentation

#2833 fix(eslint-plugin): [no-unused-vars] false-positive with class expressions
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Labels: bug

#2836 fix(eslint-plugin): [method-signature-style] fix crash with methods without a return type
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Labels: bug

#2848 fix(eslint-plugin): [no-unused-vars] fix race condition between naming-convention and no-unused-vars
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Labels: bug

#2856 fix(eslint-plugin): [naming-convention] fix wrong member of `method` and `property` meta selectors
  packages/eslint-plugin/src/rules/naming-convention-utils/enums.ts
Labels: bug

#2624 feat(eslint-plugin): add rule `non-nullable-type-assertion-style`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/non-nullable-type-assertion-style.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
Labels: enhancement: new plugin rule

#2881 fix(eslint-plugin): [non-nullable-type-assertion-style] handle const assertion
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
Labels: bug

#2876 docs(eslint-plugin): [no-namespace] correct default and example
  packages/eslint-plugin/docs/rules/no-namespace.md
Labels: documentation

#2845 feat(eslint-plugin): [prom-func-async] add automatic fix
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: enhancement

#2899 docs(parser): clarify `ecmaVersion` usage
  packages/parser/README.md
Labels: documentation

#2901 docs(eslint-plugin): reword misleading strict-boolean-expressions code example
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
Labels: documentation

#2877 fix(eslint-plugin): [naming-convention] fix precedence of method and property meta selectors
  packages/eslint-plugin/src/rules/naming-convention-utils/shared.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: bug
