Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-08, with the labels that each got.

#2348 fix(eslint-plugin): [no-implied-eval] don't report when `Function` is imported
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/tests/fixtures/class.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Labels: bug

#2335 feat(eslint-plugin): [naming-convention] allow specifying an array of selectors
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: enhancement: plugin rule option

#2326 feat(eslint-plugin): add `prefer-enum-initializers` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-enum-initializers.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-enum-initializers.ts
  packages/eslint-plugin/tests/rules/prefer-enum-initializers.test.ts
Labels: enhancement: new plugin rule

#2354 fix(eslint-plugin): [no-throw-literal] support type assertions
  packages/eslint-plugin/src/rules/no-throw-literal.ts
  packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
Labels: bug

#2374 fix(eslint-plugin): [no-shadow] fix false-positive on enum declaration
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
Labels: bug

#2375 fix: correct decorator traversal for AssignmentPattern
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/tests/rules/no-empty-function.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
  packages/types/package.json
  packages/types/src/ast-node-types.ts
  packages/types/src/ts-estree.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/tests/snapshots/typescript/errorRecovery/decorator-on-enum-declaration.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/errorRecovery/decorator-on-function.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/errorRecovery/decorator-on-interface-declaration.src.ts.shot
  packages/visitor-keys/package.json
  packages/visitor-keys/src/visitor-keys.ts
Labels: breaking change, bug

#2378 feat(typescript-estree): support TSv4 labelled tuple members
  .prettierignore
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/scope-manager/src/referencer/TypeVisitor.ts
  packages/scope-manager/tests/fixtures/type-declaration/tuple-labelled-rest.ts
  packages/scope-manager/tests/fixtures/type-declaration/tuple-labelled-rest.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/tuple-labelled.ts
  packages/scope-manager/tests/fixtures/type-declaration/tuple-labelled.ts.shot
  packages/shared-fixtures/fixtures/typescript/types/tuple-named-optional.src.ts
  packages/shared-fixtures/fixtures/typescript/types/tuple-named-rest.src.ts
  packages/shared-fixtures/fixtures/typescript/types/tuple-named-type.src.ts
  packages/shared-fixtures/fixtures/typescript/types/tuple-named.src.ts
  packages/types/src/ast-node-types.ts
  packages/types/src/ts-estree.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/basics/import-type-default.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/import-type-error.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/tuple-named-optional.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/tuple-named-rest.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/tuple-named-type.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/tuple-named.src.ts.shot
  packages/visitor-keys/src/visitor-keys.ts
  yarn.lock
Labels: AST

#2379 docs: document additional allow options in no-empty-function
  packages/eslint-plugin/docs/rules/no-empty-function.md
Labels: documentation

#2380 fix(typescript-estree): correct ChainExpression interaction with parentheses and non-nulls
  packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/no-non-null-asserted-optional-chain.test.ts
  packages/types/src/ts-estree.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-call-with-non-null-assertion.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-call-with-parens.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-element-access-with-non-null-assertion.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-with-non-null-assertion.src.ts.shot
Labels: bug

#2371 feat(eslint-plugin): [no-unsafe-assignment/return] allow assigning any => unknown
  packages/eslint-plugin/docs/rules/no-unsafe-assignment.md
  packages/eslint-plugin/docs/rules/no-unsafe-return.md
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
  packages/eslint-plugin/tests/util/isUnsafeAssignment.test.ts
Labels: enhancement

#2381 chore(eslint-plugin-tslint): reduce files included in npm publish
  packages/eslint-plugin-tslint/package.json
Labels: bug

#2385 fix(eslint-plugin): [no-unnecessary-condition] fix false positive with nullish coalescing
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#2391 fix(eslint-plugin): [prefer-includes] don't auto fix when `test` method's argument type doesn't have an 'includes' method
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/tests/rules/prefer-includes.test.ts
Labels: bug

#2392 docs(eslint-plugin): [type-annotation-spacing] typo
  packages/eslint-plugin/docs/rules/type-annotation-spacing.md
Labels: documentation

#2367 feat(eslint-plugin): add `consistent-type-imports` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
Labels: enhancement: new plugin rule

#2345 feat(eslint-plugin): [no-unnecessary-condition][strict-boolean-expressions] add option to make the rules error on files without `strictNullChecks` turned on
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/fixtures/unstrict/file.ts
  packages/eslint-plugin/tests/fixtures/unstrict/react.tsx
  packages/eslint-plugin/tests/fixtures/unstrict/tsconfig.json
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: breaking change

#2397 chore: update issue templates
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
Labels: repo maintenance

#2404 docs: fix incorrect link to prettier package
  docs/getting-started/linting/FAQ.md
Labels: documentation

#2405 fix(typescript-estree): ts.NamedTupleMember workaround for <TS4.0
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
Labels: bug

#2410 fix(eslint-plugin): [explicit-module-boundary-types] ignore abstract setters
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#2202 feat(eslint-plugin): add `no-implicit-any-catch` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-implicit-any-catch.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-implicit-any-catch.ts
  packages/eslint-plugin/tests/rules/no-implicit-any-catch.test.ts
Labels: 1 approval, enhancement: new plugin rule

#2419 feat(typescript-estree): update allowed TS version range
  README.md
  package.json
  packages/typescript-estree/src/parser.ts
  yarn.lock
Labels: dependencies

#2382 fix(eslint-plugin): [no-unnecessary-condition] better handling for unary negation
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#2418 feat(typescript-estree): switch to globby
  packages/parser/README.md
  packages/typescript-estree/README.md
  packages/typescript-estree/package.json
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  yarn.lock
Labels: breaking change, bug

#2420 fix(scope-manager): correct analysis of abstract class properties
  packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/class/declaration/abstract-property.ts
  packages/scope-manager/tests/fixtures/class/declaration/abstract-property.ts.shot
Labels: bug

#2422 fix(eslint-plugin): [no-unnecessary-condition] correct regression with unary negations
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#2427 docs: adjust prettier snippet
  docs/getting-started/linting/README.md
Labels: documentation

#2445 fix(eslint-plugin): update parser dependency range
  packages/eslint-plugin/package.json
Labels: bug
