Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-04, with the labels that each got.

#1830 fix(eslint-plugin): [no-throw-literal] fix crash caused by getBaseTypes
  packages/eslint-plugin/src/rules/no-throw-literal.ts
  packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
Labels: bug

#1833 fix(typescript-estree): add support for extra file extensions
  packages/typescript-estree/src/create-program/WatchCompilerHostOfConfigFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
Labels: bug

#263 feat(eslint-plugin): sort members alphabetically
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement: new plugin rule

#1711 fix(eslint-plugin): no-explicit-any constructor functions (& more) not ignored by ignoreRestArgs property
  packages/eslint-plugin/docs/rules/no-explicit-any.md
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
Labels: bug

#1840 docs(eslint-plugin): [no-type-alias] fix typo
  packages/eslint-plugin/docs/rules/no-type-alias.md
Labels: documentation

#1842 chore: fix issue template link
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
Labels: repo maintenance

#1685 feat(eslint-plugin): new rule method-signature-style
  .cspell.json
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/method-signature-style.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Labels: 1 approval, enhancement: new plugin rule

#1844 feat(experimental-utils): add types for suggestions from CLIEngine
  packages/experimental-utils/src/ts-eslint/Linter.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement

#1846 feat(experimental-utils): update eslint types to match v6.8
  packages/experimental-utils/src/ts-eslint-scope/ScopeManager.ts
  packages/experimental-utils/src/ts-eslint-scope/analyze.ts
  packages/experimental-utils/src/ts-eslint/CLIEngine.ts
  packages/experimental-utils/src/ts-eslint/Linter.ts
  packages/experimental-utils/src/ts-eslint/ParserOptions.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: enhancement

#1858 docs: Add @typescript-eslint/method-signature-style to the migration guide / roadmap 🎉
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#1860 docs(experimental-utils): fix links to estree pkg
  packages/experimental-utils/README.md
Labels: documentation

#1861 fix(eslint-plugin): [method-signature-style] handle multiline params
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Labels: bug

#1865 fix(eslint-plugin): no-empty-interface autofix
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
Labels: bug

#1694 feat(eslint-plugin): add rule no-unsafe-assignment
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unsafe-assignment.md
  packages/eslint-plugin/docs/rules/no-unsafe-call.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement: new plugin rule

#1881 docs(eslint-plugin): fix typos in no-unsafe-assign
  packages/eslint-plugin/docs/rules/no-unsafe-assignment.md
Labels: documentation

#1880 fix(eslint-plugin): [no-empty-interface] use suggestion fixer for ambient contexts
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
Labels: bug

#1713 feat(eslint-plugin): [consistent-type-assertions] always allow `const` assertions
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Labels: enhancement

#1762 feat(eslint-plugin): [restrict-template-expressions] add option allow `any`
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: enhancement: plugin rule option

#1736 fix(eslint-plugin): [unbound-method] ignore assignments _to_ methods
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: bug

#1763 feat(eslint-plugin): [no-base-to-string] add option to ignore tagged templates
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: enhancement: plugin rule option

#1887 docs(eslint-plugin): cleanup: standardise extension doc style, mark deprecated rules
  packages/eslint-plugin/docs/rules/ban-ts-ignore.md
  packages/eslint-plugin/docs/rules/brace-style.md
  packages/eslint-plugin/docs/rules/camelcase.md
  packages/eslint-plugin/docs/rules/class-name-casing.md
  packages/eslint-plugin/docs/rules/comma-spacing.md
  packages/eslint-plugin/docs/rules/default-param-last.md
  packages/eslint-plugin/docs/rules/func-call-spacing.md
  packages/eslint-plugin/docs/rules/generic-type-naming.md
  packages/eslint-plugin/docs/rules/indent.md
  packages/eslint-plugin/docs/rules/interface-name-prefix.md
  packages/eslint-plugin/docs/rules/member-naming.md
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/docs/rules/no-array-constructor.md
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/docs/rules/no-extra-parens.md
  packages/eslint-plugin/docs/rules/no-extra-semi.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/docs/rules/no-this-alias.md
  packages/eslint-plugin/docs/rules/no-untyped-public-signature.md
  packages/eslint-plugin/docs/rules/no-unused-expressions.md
  packages/eslint-plugin/docs/rules/no-unused-vars.md
  packages/eslint-plugin/docs/rules/no-use-before-define.md
  packages/eslint-plugin/docs/rules/no-useless-constructor.md
  packages/eslint-plugin/docs/rules/prefer-readonly.md
  packages/eslint-plugin/docs/rules/quotes.md
  packages/eslint-plugin/docs/rules/require-await.md
  packages/eslint-plugin/docs/rules/return-await.md
  packages/eslint-plugin/docs/rules/semi.md
  packages/eslint-plugin/docs/rules/space-before-function-paren.md
  packages/eslint-plugin/src/rules/ban-ts-ignore.ts
Labels: documentation

#1778 feat(eslint-plugin): [explicit-module-boundary-types] add option `shouldTrackReferences`
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: enhancement: plugin rule option

#1732 feat(eslint-plugin): [explicit-function-return-type] add option to allow concise arrows that start with void
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: enhancement

#1707 feat(eslint-plugin): add rule `prefer-reduce-type-parameter`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-reduce-type-parameter.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
  packages/eslint-plugin/tests/fixtures/class.ts
  packages/eslint-plugin/tests/rules/prefer-reduce-type-parameter.test.ts
  packages/experimental-utils/src/eslint-utils/deepMerge.ts
Labels: enhancement: new plugin rule

#1728 fix(eslint-plugin): use `isTypeArrayTypeOrUnionOfArrayTypes` util for checking if type is array
  packages/eslint-plugin/src/rules/no-for-in-array.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-for-in-array.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
Labels: bug, refactor

#1706 feat(eslint-plugin): [ban-ts-comment] support `ts-expect-error`
  packages/eslint-plugin/docs/rules/ban-ts-comment.md
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Labels: enhancement: plugin rule option

#1705 feat(eslint-plugin): add rule `prefer-ts-expect-error`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-ts-expect-error.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-ts-expect-error.ts
  packages/eslint-plugin/tests/rules/prefer-ts-expect-error.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement: new plugin rule

#1889 chore: add markdownlint
  .github/workflows/ci.yml
  .markdownlint.json
  .markdownlintignore
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
  docs/getting-started/README.md
  package.json
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/ban-ts-comment.md
  packages/eslint-plugin/docs/rules/class-literal-property-style.md
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/docs/rules/prefer-as-const.md
  packages/parser/README.md
  yarn.lock
Labels: repo maintenance

#1890 fix(eslint-plugin): [unbound-method] false positive on property function initializer
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: bug

#1803 feat(eslint-plugin): [restrict-template-expressions] add support for intersection types
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: enhancement

#1916 fix(eslint-plugin): [no-base-to-string] soft remove `ignoreTaggedTemplateExpressions` option
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: bug

#1739 feat(eslint-plugin): add extension rule `keyword-spacing`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/keyword-spacing.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/keyword-spacing.ts
  packages/eslint-plugin/tests/rules/keyword-spacing.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#1799 feat(eslint-plugin): [no-floating-promise] add option to ignore IIFEs
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: enhancement: plugin rule option

#1814 feat(eslint-plugin): add extension rule `init-declarations`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/init-declarations.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/init-declarations.ts
  packages/eslint-plugin/tests/rules/init-declarations.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#1888 chore: add gh action to lock old issues and PRs
  .github/workflows/lock.yml
Labels: repo maintenance

#1923 docs(eslint-plugin): [explicit-function-return-type] fix typo
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Labels: documentation

#1924 feat(experimental-utils): allow rule options to be a readonly tuple
  packages/experimental-utils/src/eslint-utils/RuleCreator.ts
  packages/experimental-utils/src/eslint-utils/applyDefault.ts
Labels: enhancement, package: utils

#1932 chore(eslint-plugin): correct grammatical mistake
  packages/eslint-plugin/docs/rules/no-extraneous-class.md
Labels: documentation

#1935 chore(eslint-plugin): standardise sentences in rule messages
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/rules/typedef.ts
Labels: repo maintenance

#1847 feat(eslint-plugin): create `no-invalid-void-type` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/no-invalid-void-type.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/tests/rules/no-invalid-void-type.test.ts
Labels: enhancement: new plugin rule

#1867 feat(eslint-plugin): add extension rule `dot-notation`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/tests/rules/dot-notation.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#1920 fix(eslint-plugin): [prefer-string-starts-ends-with] check for negative start index in slice
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
Labels: bug

#1850 fix(eslint-plugin): fix no-base-to-string boolean literal check
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: bug

#1870 feat(eslint-plugin): [member-ordering] add decorators support
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option

#1947 fix(eslint-plugin): [dot-notation] handle missing declarations
  packages/eslint-plugin/src/rules/dot-notation.ts
Labels: bug

#1948 feat(experimental-utils): expose our RuleTester extension
  packages/eslint-plugin-internal/tests/RuleTester.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/experimental-utils/src/eslint-utils/RuleTester.ts
  packages/experimental-utils/src/eslint-utils/index.ts
Labels: enhancement

#1949 feat(eslint-plugin-internal): add rule no-poorly-typed-ts-props
  packages/eslint-plugin-internal/src/rules/index.ts
  packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
  packages/eslint-plugin-internal/tests/fixtures/file.ts
  packages/eslint-plugin-internal/tests/fixtures/tsconfig.json
  packages/eslint-plugin-internal/tests/rules/no-poorly-typed-ts-props.test.ts
Labels: repo maintenance

#1958 chore: fix CI
  .github/workflows/lock.yml
  package.json
Labels: repo maintenance

#1955 chore: turn on `no-poorly-typed-ts-props`
  .eslintrc.js
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/prefer-includes.test.ts
Labels: blocked by another PR, repo maintenance
