Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-05, with the labels that each got.

#1961 docs(eslint-plugin): [naming-convention] correct typo in example
  packages/eslint-plugin/docs/rules/naming-convention.md
Labels: documentation

#1962 fix(eslint-plugin): [return-await] await in a normal function
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug

#1964 fix(eslint-plugin): [unbound-method] false positives for unary expressions
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: bug

#1969 fix(eslint-plugin): no-base-to-string boolean expression detect
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: bug

#1966 fix(eslint-plugin): [method-signature-style] fix overloaded methods to an intersection type
  packages/eslint-plugin/docs/rules/method-signature-style.md
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Labels: bug

#1965 feat(eslint-plugin): [prefer-optional-chain] added option to convert to suggestion fixer
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: enhancement: plugin rule option

#1823 feat(eslint-plugin): new extended rule 'no-invalid-this'
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-invalid-this.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#1970 chore: upgrade to prettier 2.0
  .github/workflows/ci.yml
  .prettierrc.json
  package.json
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/docs/rules/no-explicit-any.md
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/docs/rules/no-implied-eval.md
  packages/eslint-plugin/docs/rules/no-this-alias.md
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/tests/rules/adjacent-overload-signatures.test.ts
  packages/eslint-plugin/tests/rules/default-param-last.test.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
  packages/eslint-plugin/tests/rules/init-declarations.test.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
  packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
  packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
  packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
  packages/eslint-plugin/tests/rules/unified-signatures.test.ts
  packages/parser/src/analyze-scope.ts
  yarn.lock
Labels: repo maintenance

#1992 fix(eslint-plugin): [no-unused-expressions] inherit `messages` from base rule
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
Labels: bug

#1000 feat(eslint-plugin): eslint-recommended: disable no-obj-calls
  packages/eslint-plugin/src/configs/eslint-recommended.ts
Labels: breaking change, recommended-rules

#984 feat(eslint-plugin): eslint-recommended: disable no-func-assign
  packages/eslint-plugin/src/configs/eslint-recommended.ts
Labels: breaking change, recommended-rules

#848 feat(eslint-plugin): [ban-types] rework default options
  .markdownlint.json
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/objectIterators.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
  packages/experimental-utils/src/eslint-utils/applyDefault.ts
  packages/experimental-utils/src/ts-eslint-scope/analyze.ts
  packages/parser/tests/lib/services.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/parse.ts
Labels: breaking change, enhancement

#1163 feat(eslint-plugin): [no-unnecessary-condition] remove option `ignoreRHS`
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: breaking change, enhancement

#1289 fix(typescript-estree): use `TSEmptyBodyFunctionExpression` for body-less nodes
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/parser/src/parser.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: breaking change, bug

#1996 feat(eslint-plugin): update `eslint-recommended` set
  packages/eslint-plugin/src/configs/eslint-recommended.ts
Labels: breaking change, enhancement, recommended-rules

#716 feat(typescript-estree): always return parserServices
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
  packages/eslint-plugin/tests/util/isUnsafeAssignment.test.ts
  packages/experimental-utils/src/eslint-utils/getParserServices.ts
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/__snapshots__/parse.ts.snap
  packages/typescript-estree/tests/lib/convert.ts
  packages/typescript-estree/tests/lib/parse.ts
  packages/typescript-estree/tests/lib/semanticInfo.ts
Labels: breaking change, enhancement

#1997 feat: drop support for node v8
  .github/workflows/ci.yml
  package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/experimental-utils/package.json
  packages/parser/package.json
  packages/typescript-estree/package.json
Labels: breaking change, dependencies

#1429 feat(typescript-estree): align optional fields
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/class-with-optional-computed-method.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Labels: breaking change, bug, package: typescript-estree

#1389 feat(typescript-estree): align nodes with estree 2020
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/parser/tests/lib/__snapshots__/javascript.ts.snap
  packages/shared-fixtures/fixtures/javascript/experimentalDynamicImport/error-dynamic-import-params.src.js
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ast-node-types.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/src/visitor-keys.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
Labels: breaking change, enhancement, package: typescript-estree

#2000 chore: setup automatic RC releases for v3 branch
  .github/workflows/ci.yml
  package.json
Labels: repo maintenance

#1631 feat(eslint-plugin): [strict-boolean-expression] rework options
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: breaking change, enhancement: plugin rule option, refactor

#2001 feat(eslint-plugin): update recommended sets
  .cspell.json
  .eslintrc.js
  docs/getting-started/linting/README.md
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/base.json
  packages/eslint-plugin/src/configs/base.ts
  packages/eslint-plugin/src/configs/eslint-recommended.ts
  packages/eslint-plugin/src/configs/recommended-requiring-type-checking.json
  packages/eslint-plugin/src/configs/recommended-requiring-type-checking.ts
  packages/eslint-plugin/src/configs/recommended.json
  packages/eslint-plugin/src/configs/recommended.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/src/rules/ban-ts-ignore.ts
  packages/eslint-plugin/src/rules/camelcase.ts
  packages/eslint-plugin/src/rules/class-name-casing.ts
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/rules/interface-name-prefix.ts
  packages/eslint-plugin/src/rules/member-delimiter-style.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-extra-non-null-assertion.ts
  packages/eslint-plugin/src/rules/no-extra-semi.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/src/rules/type-annotation-spacing.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
  tools/generate-contributors.ts
Labels: breaking change, recommended-rules

#2002 feat(eslint-plugin): delete deprecated rules
  packages/eslint-plugin/docs/rules/ban-ts-ignore.md
  packages/eslint-plugin/docs/rules/camelcase.md
  packages/eslint-plugin/docs/rules/class-name-casing.md
  packages/eslint-plugin/docs/rules/generic-type-naming.md
  packages/eslint-plugin/docs/rules/interface-name-prefix.md
  packages/eslint-plugin/docs/rules/member-naming.md
  packages/eslint-plugin/docs/rules/no-untyped-public-signature.md
  packages/eslint-plugin/src/rules/ban-ts-ignore.ts
  packages/eslint-plugin/src/rules/camelcase.ts
  packages/eslint-plugin/src/rules/class-name-casing.ts
  packages/eslint-plugin/src/rules/generic-type-naming.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/interface-name-prefix.ts
  packages/eslint-plugin/src/rules/member-naming.ts
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/ban-ts-ignore.test.ts
  packages/eslint-plugin/tests/rules/camelcase.test.ts
  packages/eslint-plugin/tests/rules/class-name-casing.test.ts
  packages/eslint-plugin/tests/rules/generic-type-naming.test.ts
  packages/eslint-plugin/tests/rules/interface-name-prefix.test.ts
  packages/eslint-plugin/tests/rules/member-naming.test.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
  packages/eslint-plugin/tests/rules/no-untyped-public-signature.test.ts
Labels: breaking change, enhancement

#2003 feat(eslint-plugin): [no-floating-promises] ignore void operator by default
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: breaking change, enhancement

#2005 feat(eslint-plugin): [restrict-template-expressions] `allowNumber: true` by default
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: breaking change, enhancement

#1659 feat(eslint-plugin): [no-unnecessary-condition] report when non-nullish is compared to `null`/`undefined`
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: breaking change, enhancement

#1990 fix(eslint-plugin): [no-type-alias] handle readonly types in aliases
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: bug

#1979 fix(eslint-plugin): [no-base-to-string] support boolean in unions
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: bug

#2007 feat: bump dependencies and align AST
  package.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/README.md
  packages/eslint-plugin/tests/docs.test.ts
  packages/experimental-utils/src/json-schema.ts
  packages/parser/tests/lib/__snapshots__/comments.ts.snap
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/export-default-interface.src.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/__snapshots__/comments.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semanticInfo.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/tsx.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
  packages/typescript-estree/tsconfig.build.json
  packages/typescript-estree/tsconfig.json
  packages/typescript-estree/typings/typescript.d.ts
  yarn.lock
Labels: dependencies, enhancement

#2010 fix(experimental-utils): remove accidental dep on json-schema
  packages/experimental-utils/src/json-schema.ts
Labels: bug

#2004 feat: bump minimum required TS version
  .eslintrc.js
  README.md
  package.json
  packages/typescript-estree/README.md
  packages/typescript-estree/src/parser.ts
  yarn.lock
Labels: breaking change, dependencies

#2011 docs: add some more FAQ
  docs/getting-started/linting/FAQ.md
Labels: documentation

#1684 feat(eslint-plugin): add extension rule `lines-between-class-members`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/lines-between-class-members.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/lines-between-class-members.ts
  packages/eslint-plugin/tests/rules/lines-between-class-members.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#2022 feat: upgrade to ESLint v7
  .eslintrc.js
  package.json
  packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
  packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/func-call-spacing.ts
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/space-before-function-paren.ts
  packages/eslint-plugin/tests/eslint-rules/no-restricted-globals.test.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
  packages/eslint-plugin/tests/rules/func-call-spacing.test.ts
  packages/eslint-plugin/tests/rules/keyword-spacing.test.ts
  packages/eslint-plugin/tests/rules/member-delimiter-style.test.ts
  packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
  packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
  packages/eslint-plugin/tests/rules/no-useless-constructor.test.ts
  packages/eslint-plugin/tests/rules/quotes.test.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
  packages/eslint-plugin/tests/rules/semi.test.ts
  packages/eslint-plugin/tests/rules/space-before-function-paren.test.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/experimental-utils/src/eslint-utils/RuleTester.ts
  packages/parser/package.json
  tests/integration/fixtures/markdown/.eslintrc.js
  tests/integration/fixtures/markdown/.eslintrc.yml
  tests/integration/fixtures/markdown/Dockerfile
  tests/integration/fixtures/markdown/test.js.snap
  tests/integration/fixtures/markdown/test.sh
  tests/integration/fixtures/recommended-does-not-require-program/.eslintrc.js
  tests/integration/fixtures/recommended-does-not-require-program/.eslintrc.yml
  tests/integration/fixtures/recommended-does-not-require-program/Dockerfile
  tests/integration/fixtures/recommended-does-not-require-program/test.js.snap
  tests/integration/fixtures/recommended-does-not-require-program/test.sh
  tests/integration/fixtures/typescript-and-tslint-plugins-together/.eslintrc.js
  tests/integration/fixtures/typescript-and-tslint-plugins-together/.eslintrc.yml
  tests/integration/fixtures/typescript-and-tslint-plugins-together/Dockerfile
  tests/integration/fixtures/typescript-and-tslint-plugins-together/test.js.snap
  tests/integration/fixtures/typescript-and-tslint-plugins-together/test.sh
  tests/integration/fixtures/vue-jsx/.eslintrc.js
  tests/integration/fixtures/vue-jsx/.eslintrc.yml
  tests/integration/fixtures/vue-jsx/Dockerfile
  tests/integration/fixtures/vue-jsx/test.js.snap
  tests/integration/fixtures/vue-jsx/test.sh
  tests/integration/fixtures/vue-sfc/.eslintrc.js
  tests/integration/fixtures/vue-sfc/.eslintrc.yml
  tests/integration/fixtures/vue-sfc/Dockerfile
  tests/integration/fixtures/vue-sfc/test.js.snap
  tests/integration/fixtures/vue-sfc/test.sh
  tests/integration/utils/jsconfig.json
  yarn.lock
Labels: dependencies

#2024 chore: provide more granularity in the CI logs
  .github/workflows/ci.yml
Labels: repo maintenance

#2032 docs(eslint-plugin): [explicit-function-return-type] add missing default
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Labels: documentation

#2033 feat(experimental-utils): add `suggestion` property for rule modules
  packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
  packages/eslint-plugin/src/rules/no-non-null-assertion.ts
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement

#2028 fix(typescript-estree): fix handling of range/loc removal
  packages/typescript-estree/src/ast-converter.ts
Labels: bug

#1926 feat(eslint-plugin): [restrict-template-expressions] improve error message
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: enhancement

#1960 feat(eslint-plugin): [no-invalid-void-type] allow union of void and `allowInGenericTypeArguments`
  packages/eslint-plugin/docs/rules/no-invalid-void-type.md
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/tests/rules/no-invalid-void-type.test.ts
Labels: enhancement: plugin rule option

#2040 fix(eslint-plugin): [dot-notation] fix typo in schema
  packages/eslint-plugin/src/rules/dot-notation.ts
Labels: bug

#2043 docs: Adding FAQ entry saying TypeScript should be installed locally
  docs/getting-started/linting/FAQ.md
Labels: documentation

#2036 feat(typescript-estree): handle 3.9's non-null assertion changes
  package.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
  packages/eslint-plugin/tests/rules/no-non-null-asserted-optional-chain.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
  packages/parser/tests/lib/__snapshots__/typescript.ts.snap
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-call-with-non-null-assertion.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-element-access-with-non-null-assertion.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/optional-chain-with-non-null-assertion.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/lib/__snapshots__/convert.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
  packages/typescript-estree/tests/lib/semanticInfo.ts
  yarn.lock
Labels: enhancement

#2052 docs(eslint-plugin): remove `ignoreRHS` from `no-unnecessary-condition`
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
Labels: documentation

#2053 docs(eslint-plugin): remove mention of `eslint-recommended`
  packages/eslint-plugin/README.md
Labels: documentation

#2055 chore: link GH release in changelogs
  CHANGELOG.md
  packages/eslint-plugin-internal/CHANGELOG.md
  packages/eslint-plugin-tslint/CHANGELOG.md
  packages/eslint-plugin/CHANGELOG.md
  packages/experimental-utils/CHANGELOG.md
  packages/parser/CHANGELOG.md
  packages/shared-fixtures/CHANGELOG.md
  packages/typescript-estree/CHANGELOG.md
Labels: documentation

#2059 docs: update supported TS version in readme
  README.md
Labels: documentation

#2067 fix(typescript-estree): handle `BigInt` with `_` numeric separator
  packages/parser/tests/lib/__snapshots__/javascript.ts.snap
  packages/shared-fixtures/fixtures/javascript/bigIntLiterals/numeric-separator.src.js
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
Labels: bug

#2061 docs(eslint-plugin): [explicit-module-boundary-types] fix allowedNames config example
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
Labels: documentation

#2070 docs: various updates based on v3 feedback
  docs/getting-started/linting/FAQ.md
  docs/getting-started/linting/MONOREPO.md
  docs/getting-started/linting/README.md
  docs/getting-started/linting/TYPED_LINTING.md
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/configs/README.md
Labels: documentation

#2071 docs(eslint-plugin): [naming-convention] document ignoring quoted properties
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: documentation

#2080 docs(eslint-plugin): [naming-convention] improve comment text regarding ESLint's camelCase
  packages/eslint-plugin/docs/rules/naming-convention.md
Labels: documentation

#2083 fix(experimental-utils): export `CLIEngine` & `ESLint`
  packages/experimental-utils/src/ts-eslint/index.ts
Labels: bug

#2090 fix(eslint-plugin): [unbound-method] fix crash due to missing `Intl`
  packages/eslint-plugin/src/rules/unbound-method.ts
Labels: bug

#2085 fix(eslint-plugin): [no-throw-literal] handle intersection and union types
  packages/eslint-plugin/src/rules/no-throw-literal.ts
  packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
Labels: bug

#2095 fix(eslint-plugin): [naming-convention] handle no options correctly
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: bug

#2097 docs: broken markdown link in Contributing Guide in main README
  README.md
Labels: documentation

#2103 docs(eslint-plugin): [naming-convention] fix interface-name-prefix example
  packages/eslint-plugin/docs/rules/naming-convention.md
Labels: documentation

#2117 docs: update FAQ and add issue template config
  .github/ISSUE_TEMPLATE/config.yml
  docs/getting-started/linting/FAQ.md
  docs/getting-started/linting/TYPED_LINTING.md
Labels: documentation, repo maintenance

#2124 docs(eslint-plugin): remove `no-void` from roadmap
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#2120 docs: include npm install instructions in getting started
  docs/getting-started/linting/README.md
Labels: documentation

#2130 fix(eslint-plugin): [no-unused-expressions] ignore import expressions
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
  packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
  packages/typescript-estree/src/ts-estree/ts-estree.ts
Labels: bug

#2084 fix(eslint-plugin): [explicit-module-boundary-types] don't check returned functions if parent function has return type
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#2111 fix(eslint-plugin): [no-unnecessary-condition] improve optional chain handling
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#2123 fix(eslint-plugin): [no-unnecessary-condition] handle comparison of any, unknown and loose comparisons with nullish values
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#2099 feat(eslint-plugin): [ban-ts-comments] add "allow-with-description" option
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/ban-ts-comment.md
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Labels: enhancement: plugin rule option

#2133 fix(experimental-utils): downlevel type declarations for versions older than 3.8
  .gitignore
  package.json
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/experimental-utils/package.json
  packages/parser/package.json
  packages/shared-fixtures/package.json
  packages/typescript-estree/package.json
  yarn.lock
Labels: bug

#2135 feat(eslint-plugin): [explicit-module-boundary-types] improve accuracy and coverage
  .vscode/launch.json
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
  packages/experimental-utils/src/ts-eslint/Scope.ts
Labels: bug, enhancement: plugin rule option

#2136 docs: fix typo in npm install command
  docs/getting-started/linting/README.md
Labels: documentation

#2139 fix(eslint-plugin): [no-var-requires] false negative for TSAsExpression and MemberExpression
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/tests/rules/no-var-requires.test.ts
Labels: bug

#2137 feat(eslint-plugin): [ban-types] allow selective disable of default options with `false` value
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: enhancement: plugin rule option
