Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-10, with the labels that each got.

#2609 feat(eslint-plugin): add extension rule `no-duplicate-imports`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-duplicate-imports.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-duplicate-imports.ts
  packages/eslint-plugin/tests/rules/no-duplicate-imports.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#2638 docs(eslint-plugin): [explicit-function-return-type] fixed default `allowConciseArrowFunctionExpressionsStartingWithVoid` option value
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Labels: documentation

#2639 fix(scope-manager): don't create a variable for global augmentation
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/ts-module/global-augmentation.ts
  packages/scope-manager/tests/fixtures/ts-module/global-augmentation.ts.shot
Labels: bug

#2649 docs(typescript-estree): add the link for AST Alignment Tests
  packages/typescript-estree/README.md
Labels: documentation

#2650 docs(typescript-estree): remove defunct Build/Test Commands from README
  packages/typescript-estree/README.md
Labels: documentation

#2623 fix(eslint-plugin): [no-use-before-define] correctly handle typeof type references
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
Labels: bug

#2645 fix(eslint-plugin): [no-throw-literal] false positive with logical expressions
  packages/eslint-plugin/src/rules/no-throw-literal.ts
  packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
Labels: bug

#2653 fix(eslint-plugin): [consistent-type-assertions] check type assertion in jsx props
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Labels: bug

#2656 test(typescript-estree): remove babel-parser plugins that are enabled by default
  packages/typescript-estree/tests/ast-alignment/parse.ts
Labels: tests

#2662 fix(eslint-plugin): [ban-types] allow banning types with specific parameters
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: bug

#2659 fix(eslint-plugin): [no-unused-vars] fix false positives for duplicated names in namespaces
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
Labels: bug

#2644 fix(eslint-plugin): [ban-ts-comment] support block comments
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/ban-ts-comment.md
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Labels: bug

#2674 chore(parser): clean up some unused code
  packages/parser/src/index.ts
  packages/parser/src/parser-options.ts
  packages/parser/tests/lib/services.ts
  packages/parser/tests/tools/test-utils.ts
Labels: refactor

#2669 feat(typescript-estree): add flag EXPERIMENTAL_useSourceOfProjectReferenceRedirect
  .eslintrc.js
  packages/eslint-plugin-internal/tsconfig.json
  packages/eslint-plugin-tslint/tsconfig.build.json
  packages/eslint-plugin-tslint/tsconfig.json
  packages/eslint-plugin/tsconfig.build.json
  packages/eslint-plugin/tsconfig.json
  packages/experimental-utils/tsconfig.json
  packages/parser/tsconfig.build.json
  packages/parser/tsconfig.json
  packages/scope-manager/tsconfig.json
  packages/types/src/parser-options.ts
  packages/typescript-estree/README.md
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tsconfig.build.json
Labels: enhancement

#2671 fix(eslint-plugin): [return-await] do not auto-fix when type is `any`/`unknown`
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug

#2675 fix(eslint-plugin): [naming-convention] check bodyless function parameters
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: bug

#2680 fix(eslint-plugin): [no-unnecessary-type-assertion] correct fixer for vue files
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  tests/integration/fixtures/vue-sfc/.eslintrc.js
  tests/integration/fixtures/vue-sfc/Utility.vue
  tests/integration/fixtures/vue-sfc/test.js.snap
  tests/integration/fixtures/vue-sfc/test.sh
Labels: bug

#2681 fix(eslint-plugin): [lines-between-class-members] fix typo in schema
  packages/eslint-plugin/src/rules/lines-between-class-members.ts
Labels: bug

#2682 fix(eslint-plugin): [no-misused-promises] False negative in LogicalExpression
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: bug

#2685 fix(eslint-plugin): [no-invalid-this] allow "this" in class property definitions
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
Labels: bug

#2684 fix(parser): minor fix regexp, map-filter to reduce
  packages/parser/src/parser.ts
Labels: bug

#2667 fix(eslint-plugin): [array-type] fix issues with readonly option
  packages/eslint-plugin/docs/rules/array-type.md
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: bug

#2622 feat(eslint-plugin): [dot-notation] add `allowProtectedClassPropertyAccess` option
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/tests/rules/dot-notation.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: plugin rule option

#2628 feat(eslint-plugin): [restrict-plus-operands] add intersection type determination logic
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
Labels: enhancement: plugin rule option

#2668 feat(eslint-plugin): [prefer-readonly-parameter-types] add `ignoreInferredTypes` option
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
  packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
Labels: enhancement: plugin rule option

#2678 fix(eslint-plugin): [method-signature-style] don't auto-fix interfaces within namespaces
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Labels: bug

#2593 feat(eslint-plugin): add extension rule `space-infix-ops`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/space-infix-ops.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/space-infix-ops.ts
  packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#2696 fix(eslint-plugin): [prefer-string-starts-ends-with] Check negative indices in the second position for slice
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
Labels: bug

#2708 fix(eslint-plugin): [method-signature-style] correct fixer for overloads in an object literal type
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Labels: bug

#2704 feat(eslint-plugin): [ban-types] support banning `[]`
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: enhancement: plugin rule option

#2516 feat(eslint-plugin): add `no-unnecessary-type-constraint` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unnecessary-type-constraint.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts
Labels: enhancement: new plugin rule
