Repository typescript-eslint/typescript-eslint, pull requests merged in 2020-02, with the labels that each got.

#1557 chore(eslint-plugin): remove redundant code and update tests
  packages/eslint-plugin/src/rules/interface-name-prefix.ts
  packages/eslint-plugin/tests/rules/interface-name-prefix.test.ts
Labels: package: eslint-plugin, tests

#1558 docs(eslint-plugin): corrected typo unbounded-method
  packages/eslint-plugin/docs/rules/unbound-method.md
Labels: documentation

#1559 test(typescript-estree): fix issue in jest config
  packages/typescript-estree/jest.config.js
Labels: tests

#1536 fix(eslint-plugin): [require-await] improve performance
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: bug

#1553 fix(eslint-plugin): [embt] fix allowTypedFunctionExpressions
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#1492 feat(eslint-plugin): add extension [no-dupe-class-members]
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-dupe-class-members.ts
  packages/eslint-plugin/tests/rules/no-dupe-class-members.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#1473 feat(eslint-plugin): [no-float-prom] fixer + msg for ignoreVoid
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: enhancement, package: eslint-plugin

#1516 fix(typescript-estree): persisted parse and module none
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/tests/lib/persistentParse.ts
Labels: bug, package: typescript-estree

#972 feat(eslint-plugin): add switch-exhaustiveness-check rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
Labels: enhancement: new plugin rule

#1526 feat(eslint-plugin): [unbound-method] support bound builtins
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/fixtures/class.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
  packages/eslint-plugin/typings/node.d.ts
Labels: enhancement

#1562 fix(eslint-plugin): [unbound-method] blacklist a few unbound natives
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: bug

#1566 docs(eslint-plugin): [no-dupe-class-members] fix typo
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
Labels: documentation

#1575 fix(typescript-estree): ts returning wrong file with project references
  packages/typescript-estree/src/create-program/createProjectProgram.ts
Labels: bug

#1576 docs(parser): mention that relative paths rely on cwd
  packages/parser/README.md
Labels: documentation

#821 feat(eslint-plugin): [ban-types] allow banning null and undefined
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: enhancement: plugin rule option

#1480 feat(eslint-plugin): [strict-boolean-expressions] refactor, add clearer error messages
  .cspell.json
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: enhancement, refactor

#1611 docs(eslint-plugin): update link to deprecation rule in roadmap
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#1619 fix(typescript-estree): process.stdout can be undefined
  packages/typescript-estree/src/parser.ts
Labels: bug

#1570 fix(eslint-plugin): [typedef] allow array/object destructuring in for/of
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/src/rules/typedef.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
Labels: bug

#1620 fix(eslint-plugin): [no-floating-promises] handle finally callback
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: bug

#1561 feat(eslint-plugin): [require-await] add --fix support
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: enhancement

#1609 docs(eslint-plugin): added missing TSLint 5.20 rules to ROADMAP.md
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#1633 docs(eslint-plugin): [no-parameter-properties] fix a typo
  packages/eslint-plugin/docs/rules/no-parameter-properties.md
Labels: documentation

#1630 fix(eslint-plugin): [embt] ignore JSX callbacks
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#1650 fix(eslint-plugin): [default-param-last] handle param props
  packages/eslint-plugin/docs/rules/default-param-last.md
  packages/eslint-plugin/src/rules/default-param-last.ts
  packages/eslint-plugin/tests/rules/default-param-last.test.ts
Labels: bug

#1379 fix(eslint-plugin): [ban-types] add option extendDefaults
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: bug, default rule options, package: eslint-plugin

#1651 docs(eslint-plugin): [consistent-type-assertion] improve docs
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
Labels: documentation

#1548 feat(eslint-plugin): [explicit-member-accessibility] autofix no-public
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
Labels: enhancement: plugin rule option

#1522 feat(eslint-plugin): add new no-base-to-string rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/src/configs/all.json
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: enhancement: new plugin rule

#1578 feat(eslint-plugin): [typedef] add variable-declaration-ignore-function
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/src/rules/typedef.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
Labels: enhancement: plugin rule option

#1652 fix(eslint-plugin): [no-implied-eval] correct logic for ts3.8
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Labels: bug
