Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-01, with the labels that each got.

#2915 fix(eslint-plugin): [comma-spacing] handle empty type params
  packages/eslint-plugin/src/rules/comma-spacing.ts
  packages/eslint-plugin/tests/rules/comma-spacing.test.ts
Labels: bug

#2913 feat(eslint-plugin): add rule `sort-type-union-intersection-members`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
Labels: enhancement: new plugin rule

#2917 fix(eslint-plugin): support eslint@5
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-redeclare.ts
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: bug

#2919 feat(eslint-plugin): [sort-type-union-intersection-members] add nullish group
  packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.md
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
Labels: awaiting response, enhancement

#2751 feat: add support for decorator metadata in scope analysis and in consistent-type-imports
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/tests/fixtures/tsconfig-withmeta.json
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/parser/src/parser.ts
  packages/scope-manager/README.md
  packages/scope-manager/src/analyze.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/src/referencer/TypeVisitor.ts
  packages/scope-manager/tests/eslint-scope/references.test.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/accessor-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/accessor-deco.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-deco.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-both.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-both.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-inner.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-inner.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-outer.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-outer.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/parameters-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/parameters-deco.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/property-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/property-deco.ts.shot
Labels: enhancement

#2892 feat(eslint-plugin): add `object-curly-spacing` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/object-curly-spacing.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/object-curly-spacing.ts
  packages/eslint-plugin/tests/rules/object-curly-spacing.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: new base rule extension

#2943 fix(scope-manager): fix incorrect handling of class decorators and class method default params
  packages/eslint-plugin/tests/eslint-rules/no-undef.test.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/tests/fixtures/class/declaration/method-param-default.ts
  packages/scope-manager/tests/fixtures/class/declaration/method-param-default.ts.shot
  packages/scope-manager/tests/fixtures/decorators/class-deco-with-object-param.ts
  packages/scope-manager/tests/fixtures/decorators/class-deco-with-object-param.ts.shot
Labels: bug

#2944 fix(eslint-plugin): [sort-type-union-intersection-members] consider `void` as a `nullish`
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
Labels: bug

#2938 test(typescript-estree): update ast-alignment tests
  packages/typescript-estree/package.json
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/persistentParse.test.ts
  yarn.lock
Labels: tests

#2975 fix(scope-manager): correctly reference generic parameters when decorator metadata is enabled
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-return-generic.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-return-generic.ts.shot
Labels: bug

#2976 chore: add issue template for scope-manager
  .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
Labels: repo maintenance
