Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-03, with the labels that each got.

#3118 fix(scope-manager): update libs for typescript 4.2
  packages/scope-manager/src/lib/dom.ts
  packages/scope-manager/src/lib/webworker.ts
Labels: package: scope-manager

#3119 fix(eslint-plugin): [no-unused-vars] don't report nested module declaration
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Labels: bug, package: eslint-plugin

#3125 fix(eslint-plugin): [no-implied-eval] handle conditional expression
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Labels: bug

#3127 fix(typescript-estree): update TS version range
  packages/typescript-estree/src/parser.ts
Labels: bug

#3134 chore: yarn lock after depencency update
  yarn.lock
Labels: repo maintenance

#3139 chore: remove redundant lerna:init script
  .github/workflows/ci.yml
  .github/workflows/manual-release.yml
  package.json
Labels: repo maintenance

#3149 chore: remove husky 4 config
  .huskyrc
Labels: repo maintenance

#3152 docs(eslint-plugin): correct no longer valid references and examples
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/docs/rules/triple-slash-reference.md
Labels: documentation, package: eslint-plugin

#2847 feat(eslint-plugin): [strict-bool-expr] add fixes and suggestions
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: enhancement

#3133 fix(eslint-plugin): [no-unnecessary-type-assertion] handle assignment
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: bug

#3154 docs: fix typo 'allowAsStatement'
  packages/eslint-plugin/docs/rules/no-floating-promises.md
Labels: documentation, package: eslint-plugin

#3160 fix(eslint-plugin): [no-extran-class] allowWithDecorator should ignore other errors
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
Labels: bug

#3164 feat(eslint-plugin): add package type declaration
  packages/eslint-plugin/index.d.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/tsconfig.json
Labels: enhancement

#3178 fix(eslint-plugin): [explicit-module-boundary-types] fixes #2864 related to functions in nested object properties
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#3186 docs: update babel-eslint to @babel/eslint-parser
  README.md
  packages/typescript-estree/tests/ast-alignment/utils.ts
Labels: documentation

#3193 refactor(eslint-plugin): use direct ts type guards instead of tsutils
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/src/rules/return-await.ts
Labels: package: eslint-plugin

#3198 docs(eslint-plugin): [naming-convention] clarify literal regex notation vs. argument to RegExp
  packages/eslint-plugin/docs/rules/naming-convention.md
Labels: documentation, package: eslint-plugin

#3195 refactor(eslint-plugin): [no-floating-promises] update code to use AST instead of ts nodes
  packages/eslint-plugin/src/rules/no-floating-promises.ts
Labels: package: eslint-plugin, refactor

#3163 fix(eslint-plugin): [promise-function-async] bad fixer with computed and literal methods
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: bug

#3176 feat(eslint-plugin): [object-curly-spacing] support MappedType
  packages/eslint-plugin/src/rules/object-curly-spacing.ts
  packages/eslint-plugin/tests/rules/object-curly-spacing.test.ts
Labels: enhancement: plugin rule option

#3203 feat(eslint-plugin): [unbound-method] improve error message
  packages/eslint-plugin/docs/rules/unbound-method.md
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: enhancement

#3177 fix(eslint-plugin): [member-delimiter-style] correct invalid fix for multiline with params on the same line
  packages/eslint-plugin/src/rules/member-delimiter-style.ts
  packages/eslint-plugin/tests/rules/member-delimiter-style.test.ts
Labels: bug

#3232 docs(eslint-plugin): [unbound-method] reference eslint-plugin-jests extension rule
  packages/eslint-plugin/docs/rules/unbound-method.md
Labels: documentation

#3138 feat(eslint-plugin): [type-annotation-spacing] handle space between ? and :
  packages/eslint-plugin/src/rules/type-annotation-spacing.ts
  packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
Labels: enhancement: plugin rule option, package: eslint-plugin

#3231 feat(eslint-plugin): [space-infix-ops] support for class properties and type aliases
  packages/eslint-plugin/src/rules/space-infix-ops.ts
  packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
Labels: enhancement: plugin rule option

#3242 fix(eslint-plugin): [no-type-alias] consider `keyof` as an alias
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: bug

#3243 docs(eslint-plugin): [typedef] fix typo
  packages/eslint-plugin/docs/rules/typedef.md
Labels: documentation
