Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-08, with the labels that each got.

#3483 chore: enabled no-unsafe-member-access internally
  .eslintrc.js
  packages/eslint-plugin/src/util/createRule.ts
  packages/experimental-utils/src/eslint-utils/RuleTester.ts
  packages/parser/src/index.ts
  packages/scope-manager/tests/util/serializers/TSESTreeNode.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/semantic-or-syntactic-errors.ts
  packages/typescript-estree/src/simple-traverse.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/typings/typescript.d.ts
Labels: repo maintenance

#3577 feat(eslint-plugin): Catch unused React import with new JSX transform
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/parser/README.md
  packages/scope-manager/src/analyze.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/types/src/parser-options.ts
Labels: enhancement

#3624 fix(eslint-plugin): [no-implied-eval] permit more expression types
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Labels: bug

#3631 fix(eslint-plugin): [return-await] properly handle fixes for `TSAsExpression`
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug

#3667 chore(experimental-utils): remove commented out `RuleListener`s
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: refactor

#3687 chore: only run CI publish step on official repo
  .github/workflows/ci.yml
Labels: repo maintenance

#3655 fix(typescript-estree): ensure --fix works with singleRun mode
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
Labels: bug, package: typescript-estree

#3734 chore: update NX
  package.json
  yarn.lock
Labels: dependencies

#3768 feat(eslint-plugin): [comma-dangle] align schema with ESLint v8
  packages/eslint-plugin/src/rules/comma-dangle.ts
Labels: enhancement: plugin rule option, breaking change

#3767 chore: bump Node to ESLint 8.0 ranges
  .github/workflows/ci.yml
  package.json
  packages/ast-spec/package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/experimental-utils/package.json
  packages/parser/package.json
  packages/scope-manager/package.json
  packages/types/package.json
  packages/typescript-estree/package.json
  packages/visitor-keys/package.json
Labels: breaking change, dependencies

#3766 feat(experimental-utils): remove `getComments` from `ESLint` `SourceCode` types
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
Labels: breaking change

#2683 chore(eslint-plugin): remove support for eslint 5
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/init-declarations.ts
  packages/eslint-plugin/src/rules/keyword-spacing.ts
  packages/eslint-plugin/src/rules/lines-between-class-members.ts
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/src/rules/no-loop-func.ts
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/eslint-plugin/src/rules/quotes.ts
  packages/eslint-plugin/src/rules/semi.ts
  packages/eslint-plugin/src/rules/space-infix-ops.ts
  packages/parser/package.json
Labels: breaking change, dependencies, hacktoberfest-accepted

#3611 feat(eslint-plugin): [member-ordering] add support for getters and setters
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option, breaking change

#3340 feat: remove `TSParenthesizedType`
  packages/ast-spec/src/ast-node-types.ts
  packages/ast-spec/src/type/TSParenthesizedType/spec.ts
  packages/ast-spec/src/type/spec.ts
  packages/ast-spec/src/unions/Node.ts
  packages/ast-spec/src/unions/TypeNode.ts
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
  packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/snapshots/typescript/types/conditional-infer-nested.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/conditional-infer.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/parenthesized-type.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/tuple-named-optional.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/types/tuple-optional.src.ts.shot
  packages/visitor-keys/src/visitor-keys.ts
Labels: breaking change, AST

#3109 feat(typescript-estree): remove legacy `useJSXTextNode` option
  packages/typescript-estree/README.md
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/typescript-estree/tests/snapshots/comments/jsx-attr-and-text-with-url.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-block-comment.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-generic-with-comment-in-tag.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-tag-comments.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-text-with-multiline-non-comment.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-text-with-url.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-with-greather-than.src.js.shot
  packages/typescript-estree/tests/snapshots/comments/jsx-with-operators.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx-useJSXTextNode/self-closing-tag-inside-tag.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx-useJSXTextNode/test-content.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/attributes.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/element-keyword-name.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/embedded-invalid-js-identifier.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/escape-patterns-unknown.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/escape-patterns-valid.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/escape-patters-multi.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/multiple-blank-spaces.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/namespaced-attribute-and-value-inserted.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/self-closing-tag-inside-tag.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/tag-names-with-multi-dots-multi.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/test-content.src.js.shot
  packages/typescript-estree/tests/snapshots/tsx/react-typed-props.src.tsx.shot
Labels: package: typescript-estree, breaking change

#3776 chore: add auto-canary release for v5
  .github/workflows/ci.yml
Labels: repo maintenance

#3785 chore: update NX
  package.json
  yarn.lock
Labels: dependencies

#3730 feat(typescript-estree): add support for class static blocks
  README.md
  package.json
  packages/ast-spec/src/ast-node-types.ts
  packages/ast-spec/src/element/StaticBlock/spec.ts
  packages/ast-spec/src/element/spec.ts
  packages/ast-spec/src/token/PunctuatorToken/PunctuatorTokenToText.ts
  packages/ast-spec/src/unions/ClassElement.ts
  packages/ast-spec/src/unions/Node.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
  packages/parser/tests/tools/test-utils.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/shared-fixtures/fixtures/typescript/basics/class-static-blocks.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/ast-fixtures.test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/snapshots/jsx/invalid-mismatched-closing-tag.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/invalid-mismatched-dot-tag-name.src.js.shot
  packages/typescript-estree/tests/snapshots/jsx/invalid-mismatched-namespace-tag.src.js.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/class-static-blocks.src.ts.shot
  packages/typescript-estree/tools/test-utils.ts
  packages/visitor-keys/src/visitor-keys.ts
  yarn.lock
Labels: enhancement, AST

#3808 feat: support `PrivateIdentifier`
  packages/ast-spec/src/ast-node-types.ts
  packages/ast-spec/src/base/MethodDefinitionBase.ts
  packages/ast-spec/src/base/PropertyDefinitionBase.ts
  packages/ast-spec/src/element/MethodDefinition/spec.ts
  packages/ast-spec/src/element/PropertyDefinition/spec.ts
  packages/ast-spec/src/element/TSAbstractMethodDefinition/spec.ts
  packages/ast-spec/src/element/TSAbstractPropertyDefinition/spec.ts
  packages/ast-spec/src/expression/MemberExpression/spec.ts
  packages/ast-spec/src/special/PrivateIdentifier/spec.ts
  packages/ast-spec/src/special/spec.ts
  packages/ast-spec/src/unions/Node.ts
  packages/ast-spec/src/unions/PropertyName.ts
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/types.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/adjacent-overload-signatures.test.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/class/declaration/private-identifier.ts
  packages/scope-manager/tests/fixtures/class/declaration/private-identifier.ts.shot
  packages/scope-manager/tests/fixtures/class/expression/private-identifier.ts
  packages/scope-manager/tests/fixtures/class/expression/private-identifier.ts.shot
  packages/shared-fixtures/fixtures/javascript/classes/class-private-identifier-accessor.src.js
  packages/shared-fixtures/fixtures/javascript/classes/class-private-identifier-field.src.js
  packages/shared-fixtures/fixtures/javascript/classes/class-private-identifier-method.src.js
  packages/shared-fixtures/fixtures/typescript/basics/class-private-identifier-field-with-accessibility-error.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/class-private-identifier-field-with-annotation.src.ts
  packages/shared-fixtures/fixtures/typescript/basics/class-private-identifier-readonly-field.src.ts
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/javascript/classes/class-private-identifier-accessor.src.js.shot
  packages/typescript-estree/tests/snapshots/javascript/classes/class-private-identifier-field.src.js.shot
  packages/typescript-estree/tests/snapshots/javascript/classes/class-private-identifier-method.src.js.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/class-private-identifier-field-with-accessibility-error.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/class-private-identifier-field-with-annotation.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/class-private-identifier-readonly-field.src.ts.shot
  packages/visitor-keys/package.json
Labels: breaking change, AST

#3813 fix(eslint-plugin): crash in no-dupe-class-members (v5)
  packages/eslint-plugin/src/rules/no-dupe-class-members.ts
  packages/eslint-plugin/tests/rules/no-dupe-class-members.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: bug

#3812 fix(visitor-keys): add key to StaticBlock
  packages/visitor-keys/src/visitor-keys.ts
Labels: bug, awaiting response

#3809 feat(eslint-plugin): update recommended configs
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/recommended-requiring-type-checking.ts
  packages/eslint-plugin/src/configs/recommended.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/rules/no-implicit-any-catch.ts
  packages/eslint-plugin/src/rules/no-loss-of-precision.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/semantic-or-syntactic-errors.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/ast-alignment/spec.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tools/test-utils.ts
  tests/jest-resolver.js
Labels: enhancement, breaking change, recommended-rules

#3634 feat(experimental-utils): add literal types to `global` option
  packages/experimental-utils/src/ts-eslint/Linter.ts
Labels: bug

#3706 fix(eslint-plugin): [prefer-reduce-type-parameter] handle already existing type params
  packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
  packages/eslint-plugin/tests/rules/prefer-reduce-type-parameter.test.ts
Labels: bug

#3711 fix(eslint-plugin): [dot-notation] false positive with optional chaining
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/tests/rules/dot-notation.test.ts
Labels: bug

#3725 docs(eslint-plugin): fix typo
  packages/eslint-plugin/docs/rules/require-array-sort-compare.md
Labels: documentation

#3731 fix(eslint-plugin): isTypeReadonly error with <TS3.7
  .all-contributorsrc
  packages/eslint-plugin/src/util/isTypeReadonly.ts
Labels: bug

#3818 feat(eslint-plugin): remove `object` from `ban-types`' default types
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
Labels: enhancement: plugin rule option, breaking change
