Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-09, with the labels that each got.

#3418 feat(eslint-plugin): add extension rule `padding-line-between-statements`
  packages/ast-spec/src/unions/LeftHandSideExpression.ts
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/padding-line-between-statements.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
Labels: enhancement: new base rule extension

#3641 feat(eslint-plugin): add `no-meaningless-void-operator` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-meaningless-void-operator.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-meaningless-void-operator.ts
  packages/eslint-plugin/tests/rules/no-meaningless-void-operator.test.ts
Labels: enhancement: new plugin rule

#3677 feat(experimental-utils): extract `isNodeOfType` out of `ast-utils`' `predicates`
  packages/experimental-utils/src/ast-utils/predicates.ts
Labels: enhancement

#3709 feat(eslint-plugin): [restrict-template-expressions] add option to allow RegExp
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: enhancement: plugin rule option

#3733 feat(eslint-plugin): [prefer-readonly-parameter-types] add option treatMethodsAsReadonly
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
  packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
  packages/eslint-plugin/src/util/isTypeReadonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
Labels: enhancement: plugin rule option

#3769 chore(ast-spec): simplify `Literal` types
  packages/ast-spec/src/base/LiteralBase.ts
  packages/ast-spec/src/expression/literal/BigIntLiteral/spec.ts
  packages/ast-spec/src/expression/literal/BooleanLiteral/spec.ts
  packages/ast-spec/src/expression/literal/NullLiteral/spec.ts
  packages/ast-spec/src/expression/literal/NumberLiteral/spec.ts
  packages/ast-spec/src/expression/literal/RegExpLiteral/spec.ts
  packages/ast-spec/src/expression/literal/StringLiteral/spec.ts
Labels: refactor

#3770 fix(ast-spec): remove duplicate union types from `Expression`
  packages/ast-spec/src/unions/Expression.ts
Labels: refactor

#3789 chore(eslint-plugin): fix missing periods in rule messages
  packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/src/rules/no-duplicate-imports.ts
  packages/eslint-plugin/src/rules/no-implicit-any-catch.ts
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/prefer-enum-initializers.ts
  packages/eslint-plugin/src/rules/prefer-return-this-type.ts
Labels: bug

#3799 docs(typescript-estree): fix plural name for parserOptions.programs option
  packages/typescript-estree/README.md
Labels: documentation

#3810 docs(eslint-plugin): fix incorrect quote
  packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md
Labels: documentation

#3830 fix(utils): support immutable arrays in `ReportFixFunction`
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/src/rules/prefer-enum-initializers.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: bug

#3349 feat(eslint-plugin): add `no-non-null-asserted-nullish-coalescing` rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-non-null-asserted-nullish-coalescing.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-non-null-asserted-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/no-non-null-asserted-nullish-coalescing.test.ts
Labels: enhancement: new plugin rule

#3805 fix(eslint-plugin): false-positive/negative with array index in no-unnecessary-condition
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#3833 test(typescript-estree): update `@babel/parser` to 7.15.4
  package.json
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  yarn.lock
Labels: tests, dependencies

#3838 refactor(eslint-plugin): use `ast-utils`' `isConstructor` instead of redeclaring it in `prefer-readonly` rule
  packages/eslint-plugin/src/rules/prefer-readonly.ts
Labels: refactor

#3854 chore: enabled restrict-template-expressions internally
  .eslintrc.js
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/scope-manager/tests/util/serializers/TSESTreeNode.ts
  packages/scope-manager/tests/util/serializers/baseSerializer.ts
Labels: repo maintenance

#3895 chore: bump eslint-plugin-jest for eslint v8 support
  patches/eslint-plugin-jest+24.4.0.patch
  yarn.lock
Labels: dependencies

#3775 feat(eslint-plugin): add new extended rule `no-restricted-imports`
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-restricted-imports.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  yarn.lock
Labels: enhancement: new base rule extension

#3869 fix(eslint-plugin): [padding-line-between-statements] problems within namespaces not being reported
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
Labels: bug

#3884 fix(eslint-plugin): [no-var-requires] report problems within `NewExpression`
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/tests/rules/no-var-requires.test.ts
Labels: bug

#3887 fix(experimental-utils): add missing signature for `isParenthesized`
  packages/experimental-utils/src/ast-utils/eslint-utils/astUtilities.ts
Labels: bug

#3899 fix(eslint-plugin): [consistent-type-definitions] correct fix for `export default`
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
Labels: bug

#3898 docs(eslint-plugin): [no-misused-promises] improve examples
  packages/eslint-plugin/docs/rules/no-misused-promises.md
Labels: documentation

#3873 feat: Support `'latest'` as `ecmaVersion`
  packages/parser/README.md
  packages/parser/src/parser.ts
  packages/parser/tests/lib/parser.ts
  packages/scope-manager/README.md
  packages/scope-manager/src/analyze.ts
  packages/scope-manager/tests/eslint-scope/map-ecma-version.test.ts
  packages/types/src/parser-options.ts
Labels: enhancement

#3865 feat(eslint-plugin): [no-type-alias]: add allowGenerics option
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: enhancement: plugin rule option

#3855 fix(eslint-plugin): [prefer-regexp-exec] respect flags when using `RegExp`
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
Labels: bug, awaiting response

#3852 fix(eslint-plugin): [prefer-return-this-type] handle generics properly in fixer
  packages/eslint-plugin/src/rules/prefer-return-this-type.ts
  packages/eslint-plugin/tests/rules/prefer-return-this-type.test.ts
Labels: bug

#3871 fix(eslint-plugin): [no-require-imports] report only global `require`
  packages/eslint-plugin/src/rules/no-require-imports.ts
  packages/eslint-plugin/tests/rules/no-require-imports.test.ts
Labels: bug

#3868 fix(eslint-plugin): [no-shadow] ignore type-only imports properly
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
Labels: bug

#3916 feat(eslint-plugin-internal): [prefer-ast-types-enum] add `DefinitionType` enum
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
  packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts
  packages/eslint-plugin-internal/tests/rules/no-poorly-typed-ts-props.test.ts
  packages/eslint-plugin-internal/tests/rules/prefer-ast-types-enum.test.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
  packages/scope-manager/src/definition/DefinitionType.ts
  packages/scope-manager/tests/eslint-scope/references.test.ts
Labels: enhancement: plugin rule option

#3839 refactor(eslint-plugin): remove unnecessary `if`-statements in `explicitReturnTypeUtils`
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
Labels: refactor

#3771 feat(ast-spec): bring `Node` objects in line with ESTree
  packages/ast-spec/src/base/NodeOrTokenData.ts
  packages/ast-spec/src/base/Position.ts
  packages/ast-spec/src/base/SourceLocation.ts
  packages/ast-spec/src/index.ts
  packages/eslint-plugin/src/util/getFunctionHeadLoc.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
Labels: bug, breaking change
