Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-05, with the labels that each got.

#3308 feat(experimental-utils): Include `getCwd()` in `RuleContext` type
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement

#3289 chore(experimental-utils): remove useless union types `ast-utils` predicates
  packages/experimental-utils/src/ast-utils/predicates.ts
Labels: refactor

#3390 chore(eslint-plugin): [no-loss-of-precision] fix spelling of `isSeparatedNumeric`
  packages/eslint-plugin/src/rules/no-loss-of-precision.ts
Labels: refactor

#3392 docs(eslint-plugin): update justification for `prefer-regexp-exec`
  packages/eslint-plugin/docs/rules/prefer-regexp-exec.md
Labels: documentation

#3393 fix(eslint-plugin): [no-shadow] fix static class method generics shadowing class generics
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
Labels: bug

#3361 feat(eslint-plugin): [dot-notation] optionally allow square bracket notation where an index signature exists in conjunction with `noPropertyAccessFromIndexSignature`
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/tests/rules/dot-notation.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement: plugin rule option

#3394 fix(eslint-plugin): [no-unsafe-*] special case handling for the empty map constructor with no generics
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/util/types.ts
  packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
  packages/eslint-plugin/tests/util/isUnsafeAssignment.test.ts
Labels: bug

#3397 docs(eslint-plugin): [no-unnecessary-boolean-literal-compare] fix fixer docs
  packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.md
Labels: documentation

#3406 docs: updated no-delete-expression roadmap equivalent to no-dynamic-delete
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#3290 fix(experimental-utils): fix `isAwaitKeyword` predicate
  packages/experimental-utils/src/ast-utils/predicates.ts
Labels: bug

#3407 docs(eslint-plugin): corrected no-unsupported-browser-code in roadmap as unimplemented
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#3426 chore: update typescript to 4.3-rc
  README.md
  package.json
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/__snapshots__/convert.test.ts.snap
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tests/snapshots/jsx/namespace-this-name.src.js.shot
  packages/typescript-estree/tests/snapshots/typescript/errorRecovery/enum-with-keywords.src.ts.shot
  yarn.lock
Labels: dependencies

#3428 test(typescript-estree): fix alignment tests
  packages/typescript-estree/tests/ast-alignment/utils.ts
Labels: tests

#3457 test(typescript-estree): remove transform for TSTypePredicate
  packages/typescript-estree/package.json
  packages/typescript-estree/tests/ast-alignment/utils.ts
  yarn.lock
Labels: tests

#3280 chore: enable no-unsafe-assignment internally
  .eslintrc.js
  packages/eslint-plugin-internal/src/util/createRule.ts
  packages/eslint-plugin-tslint/src/rules/config.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/TokenInfo.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/eslint-plugin/src/util/createRule.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
  packages/experimental-utils/src/eslint-utils/applyDefault.ts
  packages/experimental-utils/src/ts-eslint-scope/index.ts
  packages/experimental-utils/typings/eslint-scope.d.ts
  packages/experimental-utils/typings/eslint-utils.d.ts
  packages/parser/src/index.ts
  packages/scope-manager/src/scope/GlobalScope.ts
  packages/scope-manager/tests/util/serializers/baseSerializer.ts
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/typings/typescript.d.ts
  tests/integration/utils/generate-package-json.js
  tools/generate-contributors.ts
Labels: repo maintenance

#3354 feat(eslint-plugin): [member-ordering] add callback as an ordering type of node
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option

#3459 chore: update to typescript 4.3
  package.json
  yarn.lock
Labels: dependencies

#3360 feat(eslint-plugin): [space-infix-ops] Add support for Union and intersection of type declarations
  packages/eslint-plugin/src/rules/space-infix-ops.ts
  packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
Labels: enhancement: plugin rule option

#3419 chore(experimental-utils): remove useless union types in `ast-utils`
  packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
  packages/experimental-utils/src/ast-utils/misc.ts
Labels: repo maintenance

#3420 chore(experimental-utils): remove useless union types in `ts-eslint`
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/SourceCode.ts
Labels: repo maintenance

#3423 chore(ast-spec): remove useless union type from `LeftHandSideExpression`
  packages/ast-spec/src/unions/LeftHandSideExpression.ts
Labels: repo maintenance

#3424 chore(ast-spec): remove useless union type from `AwaitExpression`'s `argument`
  packages/ast-spec/src/expression/AwaitExpression/spec.ts
Labels: repo maintenance

#3425 chore(ast-spec): remove useless union type from `TSUnaryExpression`
  packages/ast-spec/src/unions/TSUnaryExpression.ts
Labels: repo maintenance

#3422 chore: prettify codebase
  tests/integration/fixtures/vue-jsx/Jsx.vue
  tests/integration/fixtures/vue-jsx/test.js.snap
  tests/integration/fixtures/vue-sfc/Hello.vue
  tests/integration/fixtures/vue-sfc/World.vue
  tests/integration/fixtures/vue-sfc/test.js.snap
  tests/performance/docker-compose.yml
Labels: repo maintenance

#3446 docs(eslint-plugin): [no-this-alias] `allowDestructuring` is `true` by default
  packages/eslint-plugin/docs/rules/no-this-alias.md
Labels: documentation

#3421 chore(eslint-plugin): remove useless union types
  packages/eslint-plugin/src/rules/comma-spacing.ts
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/BinarySearchTree.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/TokenInfo.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/src/rules/object-curly-spacing.ts
Labels: repo maintenance

#3433 fix(eslint-plugin): [no-type-alias] consider type imports as alias types
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: bug

#3468 feat(scope-manager): reduce generated lib file size
  packages/scope-manager/src/lib/base-config.ts
  packages/scope-manager/src/lib/dom.iterable.ts
  packages/scope-manager/src/lib/dom.ts
  packages/scope-manager/src/lib/es2015.collection.ts
  packages/scope-manager/src/lib/es2015.core.ts
  packages/scope-manager/src/lib/es2015.generator.ts
  packages/scope-manager/src/lib/es2015.iterable.ts
  packages/scope-manager/src/lib/es2015.promise.ts
  packages/scope-manager/src/lib/es2015.proxy.ts
  packages/scope-manager/src/lib/es2015.reflect.ts
  packages/scope-manager/src/lib/es2015.symbol.ts
  packages/scope-manager/src/lib/es2015.symbol.wellknown.ts
  packages/scope-manager/src/lib/es2016.array.include.ts
  packages/scope-manager/src/lib/es2017.intl.ts
  packages/scope-manager/src/lib/es2017.object.ts
  packages/scope-manager/src/lib/es2017.sharedmemory.ts
  packages/scope-manager/src/lib/es2017.string.ts
  packages/scope-manager/src/lib/es2017.typedarrays.ts
  packages/scope-manager/src/lib/es2018.asyncgenerator.ts
  packages/scope-manager/src/lib/es2018.asynciterable.ts
  packages/scope-manager/src/lib/es2018.intl.ts
  packages/scope-manager/src/lib/es2018.promise.ts
  packages/scope-manager/src/lib/es2018.regexp.ts
  packages/scope-manager/src/lib/es2019.array.ts
  packages/scope-manager/src/lib/es2019.object.ts
  packages/scope-manager/src/lib/es2019.string.ts
  packages/scope-manager/src/lib/es2019.symbol.ts
  packages/scope-manager/src/lib/es2020.bigint.ts
  packages/scope-manager/src/lib/es2020.intl.ts
  packages/scope-manager/src/lib/es2020.promise.ts
  packages/scope-manager/src/lib/es2020.sharedmemory.ts
  packages/scope-manager/src/lib/es2020.string.ts
  packages/scope-manager/src/lib/es2020.symbol.wellknown.ts
  packages/scope-manager/src/lib/es2021.promise.ts
  packages/scope-manager/src/lib/es2021.string.ts
  packages/scope-manager/src/lib/es2021.weakref.ts
  packages/scope-manager/src/lib/es5.ts
  packages/scope-manager/src/lib/esnext.array.ts
  packages/scope-manager/src/lib/esnext.asynciterable.ts
  packages/scope-manager/src/lib/esnext.bigint.ts
  packages/scope-manager/src/lib/esnext.intl.ts
  packages/scope-manager/src/lib/esnext.promise.ts
  packages/scope-manager/src/lib/esnext.string.ts
  packages/scope-manager/src/lib/esnext.symbol.ts
  packages/scope-manager/src/lib/esnext.weakref.ts
  packages/scope-manager/src/lib/scripthost.ts
  packages/scope-manager/src/lib/webworker.iterable.ts
  packages/scope-manager/src/lib/webworker.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/src/scope/GlobalScope.ts
  packages/scope-manager/src/variable/ImplicitLibVariable.ts
  packages/scope-manager/tools/generate-lib.ts
Labels: enhancement
