Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-04, with the labels that each got.

#3256 feat(eslint-plugin): [no-unsafe-argument] add rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/no-unsafe-argument.md
  packages/eslint-plugin/docs/rules/no-unsafe-return.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
Labels: enhancement: new plugin rule

#3199 feat(eslint-plugin): [no-unsafe-call][no-unsafe-member-access] improve report messages for `this` for `noImplicitThis`
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/util/getThisExpression.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.noImplicitThis.json
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
Labels: enhancement

#3235 fix(eslint-plugin): always ignore assignments in no-unnecessary-type-assertion
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: awaiting response, bug

#3236 fix(eslint-plugin): [strict-boolean-expressions] account for truthy literals
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: awaiting response, bug

#3234 fix(eslint-plugin): [restrict-plus-operands] consider template literal types as strings
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
Labels: bug

#3269 fix(eslint-plugin): [no-unsafe-argument] handle tuple types on rest arguments
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
Labels: bug

#3277 docs(eslint-plugin): switch check marks to `:white_check_mark:` for visibility
  packages/eslint-plugin/README.md
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tools/generate-rules-lists.ts
Labels: documentation

#3207 feat(eslint-plugin): [prefer-regexp-exec] add autofix
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
  packages/eslint-plugin/tests/util/getWrappingFixer.test.ts
Labels: enhancement

#3282 chore: enable restrict-plus-operands internally
  .eslintrc.js
  packages/typescript-estree/tests/ast-alignment/parse.ts
  packages/typescript-estree/tests/ast-alignment/utils.ts
Labels: repo maintenance

#3281 chore: enable `no-unsafe-call` locally
  .eslintrc.js
  package.json
  packages/eslint-plugin-tslint/src/custom-linter.ts
  packages/experimental-utils/src/eslint-utils/RuleTester.ts
  packages/parser/tests/tools/test-utils.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tools/test-utils.ts
  tests/integration/utils/jest-snapshot-resolver.js
  tools/generate-contributors.ts
  tsconfig.eslint.json
  yarn.lock
Labels: repo maintenance
