Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-06, with the labels that each got.

#3475 fix(eslint-plugin): fix doc url generation
  packages/eslint-plugin/src/util/createRule.ts
Labels: bug

#3432 fix(eslint-plugin): [prefer-includes] ignore option chaining before indexOfs
  packages/eslint-plugin/docs/rules/prefer-includes.md
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/tests/rules/prefer-includes.test.ts
Labels: bug

#3484 feat: allow user to provide TS program instance in parser options
  packages/parser/README.md
  packages/parser/src/index.ts
  packages/parser/tests/lib/services.ts
  packages/types/package.json
  packages/types/src/parser-options.ts
  packages/typescript-estree/README.md
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/create-program/useProvidedProgram.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
Labels: enhancement

#3465 chore: add nx monorepo tooling
  .github/workflows/ci.yml
  .github/workflows/generate-contributors.yml
  CONTRIBUTING.md
  nx.json
  package.json
  packages/eslint-plugin/package.json
  workspace.json
  yarn.lock
Labels: repo maintenance

#3512 feat(typescript-estree): add opt-in inference for single runs and create programs for projects up front
  .eslintrc.js
  packages/typescript-estree/README.md
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/useProvidedPrograms.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/persistentParse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
Labels: enhancement

#3497 feat(ast-spec): specify `LogicalExpression`'s `operator` type
  packages/ast-spec/src/expression/LogicalExpression/spec.ts
Labels: enhancement

#3515 feat(eslint-plugin): [prefer-literal-enum-member] add allowBitwiseExpressions option
  packages/eslint-plugin/docs/rules/prefer-literal-enum-member.md
  packages/eslint-plugin/src/rules/prefer-literal-enum-member.ts
  packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
Labels: bug

#3498 fix(eslint-plugin): allow explicit any for no-unsafe-return
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
Labels: bug

#3519 chore(typescript-estree): use `SyntaxKind.LastPunctuation` as upper bound to determine `Punctuator` token type
  packages/typescript-estree/src/node-utils.ts
Labels: repo maintenance

#3496 feat(ast-spec): specify `PunctuatorToken`'s `value` type
  packages/ast-spec/package.json
  packages/ast-spec/src/token/PunctuatorToken/PunctuatorTokenToText.ts
  packages/ast-spec/src/token/PunctuatorToken/spec.ts
  packages/typescript-estree/src/node-utils.ts
Labels: enhancement

#3530 test: update @babel/parser to update ignored fixtures
  package.json
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  yarn.lock
Labels: tests

#3461 fix(experimental-utils): fix `eslint-utils`' negative predicates' return types in `ast-utils`
  packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Labels: repo maintenance

#3462 fix(experimental-utils): fix `eslint-utils`' negative predicates' return types
  packages/experimental-utils/src/ast-utils/predicates.ts
Labels: repo maintenance

#3531 fix(experimental-utils): make keys for `ReferenceTracker` options optional
  packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
Labels: bug

#3532 feat(experimental-utils): expose ReferenceTracker.ESM
  packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
  packages/experimental-utils/typings/eslint-utils.d.ts
Labels: enhancement

#3555 feat(experimental-utils): add `only` property to `RuleTester` types
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: enhancement

#3557 fix(experimental-utils): expand `RuleTester` config properties
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: enhancement

#3550 refactor(experimental-utils): simplify `eslint-utils`' predicate types in `ast-utils`
  packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Labels: repo maintenance

#3478 chore(eslint-plugin): remove lodash from dependencies
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/src/util/escapeRegExp.ts
Labels: repo maintenance

#3434 fix(eslint-plugin): [prefer-regexp-exec] factor in union types
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
Labels: bug

#3556 feat(experimental-utils): use mergable interface for `settings` property
  packages/experimental-utils/src/ts-eslint/Linter.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: awaiting response, enhancement

#3562 chore(ast-spec): move `ImportDeclaration` to `declarations` folder
  packages/ast-spec/src/declaration/ImportDeclaration/spec.ts
  packages/ast-spec/src/declaration/spec.ts
  packages/ast-spec/src/statement/spec.ts
  packages/ast-spec/src/unions/Node.ts
  packages/ast-spec/src/unions/Statement.ts
Labels: repo maintenance

#3529 tests(ast-spec): make `PunctuatorTokenToText` more type-safe
  packages/ast-spec/src/token/PunctuatorToken/PunctuatorTokenToText.ts
  packages/ast-spec/tests/PunctuatorTokenToText.test.ts
Labels: repo maintenance

#3563 refactor(experimental-utils): simplify `eslint-utils`' predicate types in `ast-utils`
  packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Labels: repo maintenance
