Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-12, with the labels that each got.

#4239 feat(eslint-plugin): [no-shadow] support TS4.5 inline import specifiers
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
Labels: enhancement

#4236 feat(eslint-plugin): [consistent-type-exports] support TS4.5 inline export specifiers
  packages/eslint-plugin/docs/rules/consistent-type-exports.md
  packages/eslint-plugin/src/rules/consistent-type-exports.ts
  packages/eslint-plugin/tests/rules/consistent-type-exports.test.ts
Labels: enhancement: plugin rule option

#4237 feat(eslint-plugin): [consistent-type-imports] support TS4.5 inline import specifiers
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
Labels: enhancement

#4252 docs(eslint-plugin): Mention `useUnknownInCatchVariables` in `no-implicit-any-catch`
  packages/eslint-plugin/docs/rules/no-implicit-any-catch.md
Labels: documentation

#4263 docs(website): fix tsconfig.eslint.json instead of .eslintrc.js in code snippet
  docs/linting/MONOREPO.md
Labels: documentation

#4272 fix(typescript-estree): type-only regression for consumers not yet on TS 4.5
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
Labels: bug

#4271 docs: updates to security rules in ROADMAP.md
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#4278 chore: update codecov/codecov-action to v2
  .github/workflows/ci.yml
Labels: repo maintenance

#4242 docs(website): optimize playground config editor
  packages/website/package.json
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/config/ConfigEslint.tsx
  packages/website/src/components/config/ConfigTypeScript.tsx
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/lib/shallowEqual.ts
  packages/website/src/components/modals/Modal.module.css
  packages/website/src/components/modals/Modal.tsx
Labels: documentation

#4277 docs(eslint-plugin): update readme and roadmap links to point to website
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
Labels: documentation

#4243 docs(website): add simple ts ast viewer
  packages/website-eslint/src/linter/linter.js
  packages/website-eslint/src/linter/parser.js
  packages/website-eslint/types/index.d.ts
  packages/website/src/components/ASTViewerESTree.tsx
  packages/website/src/components/ASTViewerTS.tsx
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/ast/ASTViewer.module.css
  packages/website/src/components/ast/ASTViewer.tsx
  packages/website/src/components/ast/Elements.tsx
  packages/website/src/components/ast/HiddenItem.tsx
  packages/website/src/components/ast/ItemGroup.tsx
  packages/website/src/components/ast/PropertyName.tsx
  packages/website/src/components/ast/PropertyValue.tsx
  packages/website/src/components/ast/selection.ts
  packages/website/src/components/ast/types.ts
  packages/website/src/components/ast/utils.ts
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/types.ts
  packages/website/src/components/hooks/useDebouncedToggle.ts
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/inputs/Dropdown.tsx
  packages/website/src/components/inputs/Tooltip.module.css
  packages/website/src/components/inputs/Tooltip.tsx
  packages/website/src/components/lib/shallowEqual.ts
  packages/website/src/components/types.ts
Labels: documentation

#4284 docs(website): update docusaurus to 2.0.0-beta.13
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/css/custom.css
  packages/website/src/pages/styles.module.css
  yarn.lock
Labels: documentation

#4289 docs(website): add community links to footer
  packages/website/docusaurus.config.js
Labels: documentation

#4249 docs(website): fix links between github, rules and docs
  docs/linting/README.md
  docs/linting/TROUBLESHOOTING.md
  docs/linting/TYPED_LINTING.md
  packages/eslint-plugin/docs/rules/README.md
Labels: documentation

#4275 fix(eslint-plugin): [strict-boolean-expression] false positive for truthy boolean
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: bug

#4274 fix(eslint-plugin): `array-type` mark `AST_NODE_TYPES.TSBigIntKeyword` as simple
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: bug, 1 approval

#3844 fix(experimental-utils): support immutable members
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/experimental-utils/src/ts-eslint/RuleTester.ts
Labels: bug, 1 approval

#4313 fix(eslint-plugin): [no-implied-eval] improve performance
  packages/eslint-plugin/src/rules/no-implied-eval.ts
Labels: package: eslint-plugin, performance

#4281 docs(website): use svg loader to load icons
  packages/website/src/components/OptionsSelector.module.css
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/icons/AddIcon.tsx
  packages/website/src/components/icons/ArrowIcon.tsx
  packages/website/src/components/icons/CloseIcon.tsx
  packages/website/src/components/icons/CopyIcon.tsx
  packages/website/src/components/icons/DeleteIcon.tsx
  packages/website/src/components/icons/EditIcon.tsx
  packages/website/src/components/icons/SVGIcon.tsx
  packages/website/src/components/layout/Expander.module.css
  packages/website/src/components/layout/Expander.tsx
  packages/website/src/components/modals/Modal.tsx
  packages/website/src/icons/add.svg
  packages/website/src/icons/arrow.svg
  packages/website/src/icons/close.svg
  packages/website/src/icons/copy.svg
  packages/website/src/icons/delete.svg
  packages/website/src/icons/edit.svg
  packages/website/src/types.d.ts
  packages/website/tsconfig.json
Labels: documentation

#4326 docs: update links to point to correct pages
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
  packages/eslint-plugin/README.md
  packages/parser/README.md
  packages/scope-manager/README.md
  packages/typescript-estree/README.md
Labels: documentation

#4318 fix(eslint-plugin): handle method overloading in `semi`
  packages/eslint-plugin/src/rules/semi.ts
  packages/eslint-plugin/tests/rules/semi.test.ts
Labels: bug, package: eslint-plugin

#4270 fix(eslint-plugin): [padding-line-between-statements] `type` StatementTypes can't differenciate from variable
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
Labels: bug

#4324 docs: align colors of code block
  packages/website/docusaurus.config.js
  packages/website/src/components/ast/ASTViewer.module.css
  packages/website/src/css/custom.css
  packages/website/src/css/prism.css
Labels: documentation

#4207 feat(eslint-plugin): [no-throw-literal] add options to to disallow `any`/`unknown`
  packages/eslint-plugin/docs/rules/no-throw-literal.md
  packages/eslint-plugin/src/rules/no-throw-literal.ts
  packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
Labels: enhancement: plugin rule option

#4260 feat(eslint-plugin): [restrict-plus-operand] add allowAny option
  packages/eslint-plugin/docs/rules/restrict-plus-operands.md
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
Labels: enhancement: plugin rule option

#4319 docs(eslint-plugin): fix typo in example codeFix typo in example code
  packages/eslint-plugin/docs/rules/no-unsafe-argument.md
Labels: package: eslint-plugin, documentation, 1 approval

#4311 chore(experimental-utils): sync peer eslint dependency with eslint-plugin
  packages/experimental-utils/package.json
Labels: dependencies, package: utils

#4325 docs(website): add comma in testing custom rule
  docs/development/CUSTOM_RULES.md
Labels: documentation, 1 approval

#4320 docs(website): fix heading level inconsistencies
  docs/development/architecture/ASTS.md
  packages/eslint-plugin/docs/rules/README.md
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/docs/rules/prefer-readonly.md
  packages/eslint-plugin/docs/rules/unbound-method.md
Labels: documentation, 1 approval

#4323 test(parser): update parser tsx tests to not use eslint
  packages/parser/package.json
  packages/parser/tests/lib/parser.ts
  packages/parser/tests/lib/tsx.ts
  packages/parser/tests/tools/ts-error-serializer.ts
Labels: package: parser, tests

#4334 fix(eslint-plugin): [consistent-type-definitions] correct fixer with declare keyword
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
Labels: bug, package: eslint-plugin

#4312 docs(website): add preview of scope manager to playground
  packages/website-eslint/src/linter/linter.js
  packages/website-eslint/types/index.d.ts
  packages/website/src/components/ASTViewerESTree.tsx
  packages/website/src/components/ASTViewerScope.tsx
  packages/website/src/components/ASTViewerTS.tsx
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.tsx
  packages/website/src/components/ast/ASTViewer.tsx
  packages/website/src/components/ast/Elements.tsx
  packages/website/src/components/ast/HiddenItem.tsx
  packages/website/src/components/ast/ItemGroup.tsx
  packages/website/src/components/ast/PropertyName.tsx
  packages/website/src/components/ast/PropertyValue.tsx
  packages/website/src/components/ast/SimpleItem.tsx
  packages/website/src/components/ast/serializer/serializer.ts
  packages/website/src/components/ast/serializer/serializerESTree.ts
  packages/website/src/components/ast/serializer/serializerScope.ts
  packages/website/src/components/ast/serializer/serializerTS.ts
  packages/website/src/components/ast/types.ts
  packages/website/src/components/ast/utils.ts
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/types.ts
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/types.ts
  packages/website/tsconfig.json
Labels: documentation

#4341 docs(website): use json5 library to parse config in playground
  packages/website/package.json
  packages/website/src/components/config/ConfigEditor.tsx
  yarn.lock
Labels: documentation

#4347 fix(eslint-plugin): [consistent-indexed-object-style] do not report for circular references
  packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
  packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Labels: bug, package: eslint-plugin

#4345 fix(eslint-plugin): [padding-line-between-statements] make function overloading is also processed
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
Labels: bug

#4354 docs(website): correct potential infinite loop in ts ast viewer
  packages/website/src/components/ASTViewerTS.tsx
  packages/website/src/components/ast/ASTViewer.tsx
  packages/website/src/components/ast/Elements.tsx
  packages/website/src/components/ast/SimpleItem.tsx
  packages/website/src/components/ast/serializer/serializer.ts
  packages/website/src/components/ast/serializer/serializerTS.ts
  packages/website/src/components/ast/types.ts
Labels: documentation

#4369 docs(eslint-plugin): change createRule usage to point to website
  packages/eslint-plugin/src/util/createRule.ts
  packages/eslint-plugin/tests/docs.test.ts
Labels: documentation

#4373 docs: explain why there is not a "typescriptLocation" option
  docs/linting/TROUBLESHOOTING.md
Labels: documentation

#4375 docs: mention deep globs in ESLint options in troubleshooting
  docs/linting/TROUBLESHOOTING.md
Labels: documentation

#4376 docs: replace astexplorer.net links with playground
  docs/development/architecture/ASTS.md
  docs/development/architecture/PACKAGES.md
  docs/linting/TROUBLESHOOTING.md
Labels: documentation

#4377 docs(eslint-plugin): mention constructor privacy limitation on no-useless-constructor
  packages/eslint-plugin/docs/rules/no-useless-constructor.md
Labels: documentation

#4374 docs: mention VS Code debugging tasks in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4379 docs: add examples of overrides without type information
  docs/linting/TYPED_LINTING.md
Labels: documentation
