Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-11, with the labels that each got.

#4078 test: rework the integration tests to not use docker
  .eslintrc.js
  .github/workflows/ci.yml
  package.json
  packages/typescript-estree/package.json
  packages/typescript-estree/tests/lib/convert.test.ts
  tests/integration/README.md
  tests/integration/docker-compose.yml
  tests/integration/fixtures/eslint-v6/.eslintrc.js
  tests/integration/fixtures/eslint-v6/Dockerfile
  tests/integration/fixtures/eslint-v6/package.json
  tests/integration/fixtures/eslint-v6/test.sh
  tests/integration/fixtures/markdown/.eslintrc.js
  tests/integration/fixtures/markdown/Dockerfile
  tests/integration/fixtures/markdown/package.json
  tests/integration/fixtures/markdown/test.sh
  tests/integration/fixtures/recommended-does-not-require-program/.eslintrc.js
  tests/integration/fixtures/recommended-does-not-require-program/Dockerfile
  tests/integration/fixtures/recommended-does-not-require-program/package.json
  tests/integration/fixtures/recommended-does-not-require-program/test.sh
  tests/integration/fixtures/typescript-and-tslint-plugins-together/.eslintrc.js
  tests/integration/fixtures/typescript-and-tslint-plugins-together/Dockerfile
  tests/integration/fixtures/typescript-and-tslint-plugins-together/package.json
  tests/integration/fixtures/typescript-and-tslint-plugins-together/test.js.snap
  tests/integration/fixtures/typescript-and-tslint-plugins-together/test.sh
  tests/integration/fixtures/vue-jsx/.eslintrc.js
  tests/integration/fixtures/vue-jsx/Dockerfile
  tests/integration/fixtures/vue-jsx/package.json
  tests/integration/fixtures/vue-jsx/test.sh
  tests/integration/fixtures/vue-sfc/.eslintrc.js
  tests/integration/fixtures/vue-sfc/Dockerfile
  tests/integration/fixtures/vue-sfc/package.json
  tests/integration/fixtures/vue-sfc/test.sh
  tests/integration/integration-test-base.ts
  tests/integration/jest.config.js
  tests/integration/pack-packages.ts
  tests/integration/run-all-tests.sh
  tests/integration/tests/__snapshots__/eslint-v6.test.ts.snap
  tests/integration/tests/__snapshots__/markdown.test.ts.snap
  tests/integration/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
  tests/integration/tests/__snapshots__/typescript-and-tslint-plugins-together.test.ts.snap
  tests/integration/tests/__snapshots__/vue-jsx.test.ts.snap
  tests/integration/tests/__snapshots__/vue-sfc.test.ts.snap
  tests/integration/tests/eslint-v6.test.ts
  tests/integration/tests/markdown.test.ts
  tests/integration/tests/recommended-does-not-require-program.test.ts
  tests/integration/tests/typescript-and-tslint-plugins-together.test.ts
  tests/integration/tests/vue-jsx.test.ts
  tests/integration/tests/vue-sfc.test.ts
  tests/integration/tsconfig.json
  tests/integration/utils/.eslintrc.js
  tests/integration/utils/generate-package-json.js
  tests/integration/utils/jest-snapshot-resolver.js
  tests/integration/utils/jsconfig.json
  tsconfig.eslint.json
  yarn.lock
Labels: tests

#4039 docs(eslint-plugin): Fix `consistent-type-definitions` README with correct usage of type
  packages/eslint-plugin/docs/rules/consistent-type-definitions.md
Labels: documentation

#3977 feat(experimental-utils): extract `isTokenOfTypeWithConditions` out of `ast-utils`' `predicates`
  packages/experimental-utils/src/ast-utils/helpers.ts
  packages/experimental-utils/src/ast-utils/predicates.ts
Labels: enhancement

#3959 feat(eslint-plugin): [no-shadow] exclude external type declaration merging
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
Labels: enhancement

#4046 fix(eslint-plugin): ignore private identifiers in explicit-module-boundary-types
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug

#4043 fix(eslint-plugin): skip seenTypes for unions in isTypeReadonly
  packages/eslint-plugin/src/util/isTypeReadonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
Labels: bug

#4101 chore: bump babel to 7.16.x and update tests
  package.json
  packages/typescript-estree/tests/ast-alignment/utils.ts
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  yarn.lock
Labels: dependencies

#4097 test(eslint-plugin): add optional chaining cases for `await-thenable`
  packages/eslint-plugin/tests/rules/await-thenable.test.ts
Labels: tests

#4096 fix(eslint-plugin): check optional chaining for floating promises
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: bug

#3151 chore: update lerna to 4.0.0
  .eslintignore
  commitlint.config.js
  package.json
  yarn.lock
Labels: DO NOT MERGE, 1 approval, dependencies

#4092 docs(eslint-plugin): [padding-line-between-statements] clarify accepted options
  packages/eslint-plugin/docs/rules/padding-line-between-statements.md
Labels: documentation

#4073 chore: update to typescript 4.5-rc
  README.md
  package.json
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/fixtures/invalidFileErrors/js/included01.js
  packages/typescript-estree/tests/fixtures/invalidFileErrors/js/included02.jsx
  packages/typescript-estree/tests/fixtures/invalidFileErrors/js/notIncluded01.js
  packages/typescript-estree/tests/fixtures/invalidFileErrors/js/notIncluded02.jsx
  packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/included01.ts
  packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/included02.tsx
  packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/notIncluded01.ts
  packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/notIncluded02.tsx
  packages/typescript-estree/tests/fixtures/invalidFileErrors/tsconfig.json
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/parse.test.ts
  yarn.lock
Labels: dependencies

#4116 docs: add missing formatting for cjson and jsonc and correct edit links
  packages/website/docusaurus.config.js
  packages/website/src/prism/language/jsonc.js
  packages/website/src/theme/prism-include-languages.js
Labels: documentation

#4117 fix(eslint-plugin): [explicit-member-accessibility] private fields cannot have accessibility modifiers
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
Labels: bug

#4123 fix: landing page title duplication
  packages/website/docusaurus.config.js
  packages/website/src/pages/index.tsx
Labels: documentation

#4049 fix(eslint-plugin): [no-implied-eval] ignore locally declared functions
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Labels: bug

#4112 docs: audit and revamp of main pages
  .cspell.json
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
  README.md
  docs/getting-started/README.md
  docs/getting-started/linting/ARCHITECTURE.md
  docs/getting-started/linting/MONOREPO.md
  docs/getting-started/linting/README.md
  docs/getting-started/linting/TROUBLESHOOTING.md
  docs/getting-started/linting/TSLINT.md
  docs/getting-started/linting/TYPED_LINTING.md
  packages/eslint-plugin/README.md
  packages/website/sidebars/sidebar.base.js
  packages/website/src/pages/index.tsx
  packages/website/src/pages/styles.module.css
Labels: documentation

#4111 docs: added issue template for docs request
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/documentation-request.yml
Labels: repo maintenance

#4075 feat(typescript-estree): support private fields in-in syntax
  packages/ast-spec/src/base/BinaryExpressionBase.ts
  packages/ast-spec/src/expression/AssignmentExpression/spec.ts
  packages/ast-spec/src/expression/BinaryExpression/spec.ts
  packages/ast-spec/src/expression/LogicalExpression/spec.ts
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/shared-fixtures/fixtures/typescript/basics/private-fields-in-in.src.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/basics/private-fields-in-in.src.ts.shot
Labels: AST

#4135 feat(experimental-utils): add default [] for RuleModule TOptions generic
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement

#4124 docs: fleshed out dedicated Architecture section
  .cspell.json
  README.md
  docs/README.md
  docs/development/CUSTOM_RULES.md
  docs/development/architecture/ASTS.md
  docs/development/architecture/PACKAGES.md
  docs/getting-started/linting/ARCHITECTURE.md
  docs/getting-started/plugin-development/README.md
  docs/linting/MONOREPO.md
  docs/linting/README.md
  docs/linting/TROUBLESHOOTING.md
  docs/linting/TSLINT.md
  docs/linting/TYPED_LINTING.md
  packages/website/docusaurus.config.js
  packages/website/sidebars/sidebar.base.js
Labels: documentation

#4127 docs: added Konamimojisplosion easter egg to website
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/clientModules.js
  packages/website/tsconfig.json
  yarn.lock
Labels: documentation

#4136 feat: add RuleCreator.withoutDocs
  packages/eslint-plugin/tests/docs.test.ts
  packages/experimental-utils/src/eslint-utils/RuleCreator.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
Labels: enhancement

#4140 fix: correct issues with circular imports
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/src/util/isTypeReadonly.ts
  packages/scope-manager/src/referencer/PatternVisitor.ts
Labels: package: eslint-plugin, performance, package: scope-manager

#4114 docs: add landing page for rules
  docs/linting/README.md
  packages/eslint-plugin/docs/rules/README.md
  packages/eslint-plugin/docs/rules/comma-dangle.md
  packages/eslint-plugin/docs/rules/member-delimiter-style.md
  packages/eslint-plugin/docs/rules/no-inferrable-types.md
  packages/eslint-plugin/docs/rules/object-curly-spacing.md
  packages/eslint-plugin/docs/rules/prefer-string-starts-ends-with.md
  packages/eslint-plugin/docs/rules/require-array-sort-compare.md
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tools/generate-rules-lists.ts
  packages/website/docusaurus.config.js
  packages/website/sidebars/sidebar.rules.js
Labels: documentation, awaiting response

#4157 chore: various website improvements
  packages/eslint-plugin/docs/rules/brace-style.md
  packages/eslint-plugin/docs/rules/comma-dangle.md
  packages/eslint-plugin/docs/rules/comma-spacing.md
  packages/eslint-plugin/docs/rules/default-param-last.md
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/docs/rules/func-call-spacing.md
  packages/eslint-plugin/docs/rules/indent.md
  packages/eslint-plugin/docs/rules/init-declarations.md
  packages/eslint-plugin/docs/rules/keyword-spacing.md
  packages/eslint-plugin/docs/rules/lines-between-class-members.md
  packages/eslint-plugin/docs/rules/no-array-constructor.md
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
  packages/eslint-plugin/docs/rules/no-duplicate-imports.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/docs/rules/no-extra-parens.md
  packages/eslint-plugin/docs/rules/no-extra-semi.md
  packages/eslint-plugin/docs/rules/no-implied-eval.md
  packages/eslint-plugin/docs/rules/no-invalid-this.md
  packages/eslint-plugin/docs/rules/no-loop-func.md
  packages/eslint-plugin/docs/rules/no-loss-of-precision.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/docs/rules/no-redeclare.md
  packages/eslint-plugin/docs/rules/no-shadow.md
  packages/eslint-plugin/docs/rules/no-throw-literal.md
  packages/eslint-plugin/docs/rules/no-unused-expressions.md
  packages/eslint-plugin/docs/rules/no-unused-vars.md
  packages/eslint-plugin/docs/rules/no-use-before-define.md
  packages/eslint-plugin/docs/rules/no-useless-constructor.md
  packages/eslint-plugin/docs/rules/object-curly-spacing.md
  packages/eslint-plugin/docs/rules/padding-line-between-statements.md
  packages/eslint-plugin/docs/rules/quotes.md
  packages/eslint-plugin/docs/rules/require-await.md
  packages/eslint-plugin/docs/rules/semi.md
  packages/eslint-plugin/docs/rules/space-before-function-paren.md
  packages/eslint-plugin/docs/rules/space-infix-ops.md
  packages/website/docusaurus.config.js
  packages/website/src/clientModules.js
  packages/website/src/css/custom.css
  packages/website/src/pages/index.tsx
  packages/website/static/img/favicon/site.webmanifest
  packages/website/tsconfig.json
Labels: documentation

#4125 fix(eslint-plugin): [require-await] treat yield* asynciterable as an await
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
Labels: bug

#3896 feat(eslint-plugin): [member-ordering] add option to sort case insensitive
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering-alphabetically-case-insensitive-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering-alphabetically-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option, 1 approval

#4169 test(typescript-estree): remove workaround for import assertions
  package.json
  packages/typescript-estree/tests/ast-alignment/utils.ts
  yarn.lock
Labels: tests

#4167 docs: touchups for a better Lighthouse score
  packages/website/docusaurus.config.js
  packages/website/src/css/custom.css
  packages/website/src/pages/index.tsx
  packages/website/src/pages/styles.module.css
Labels: documentation

#4054 fix(eslint-plugin): [member-ordering] order literal names correctly in
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering-alphabetically-order.test.ts
Labels: bug, awaiting response, 1 approval

#4173 fix(experimental-utils): fix types for eslint-utils
  packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
  packages/experimental-utils/src/ast-utils/eslint-utils/astUtilities.ts
Labels: bug

#4178 fix(visitor-keys): add missing import assertion keys
  packages/visitor-keys/src/visitor-keys.ts
Labels: bug

#4179 chore: update to typescript 4.5
  package.json
  yarn.lock
Labels: dependencies

#4171 chore: rename default branch to 'main'
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.yml
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
  .github/pull_request_template.md
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  docs/development/architecture/PACKAGES.md
  docs/linting/TSLINT.md
  nx.json
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/docs/rules/brace-style.md
  packages/eslint-plugin/docs/rules/comma-dangle.md
  packages/eslint-plugin/docs/rules/comma-spacing.md
  packages/eslint-plugin/docs/rules/default-param-last.md
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/docs/rules/func-call-spacing.md
  packages/eslint-plugin/docs/rules/indent.md
  packages/eslint-plugin/docs/rules/init-declarations.md
  packages/eslint-plugin/docs/rules/keyword-spacing.md
  packages/eslint-plugin/docs/rules/lines-between-class-members.md
  packages/eslint-plugin/docs/rules/no-array-constructor.md
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
  packages/eslint-plugin/docs/rules/no-duplicate-imports.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/docs/rules/no-extra-parens.md
  packages/eslint-plugin/docs/rules/no-extra-semi.md
  packages/eslint-plugin/docs/rules/no-implied-eval.md
  packages/eslint-plugin/docs/rules/no-invalid-this.md
  packages/eslint-plugin/docs/rules/no-loop-func.md
  packages/eslint-plugin/docs/rules/no-loss-of-precision.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/docs/rules/no-redeclare.md
  packages/eslint-plugin/docs/rules/no-shadow.md
  packages/eslint-plugin/docs/rules/no-throw-literal.md
  packages/eslint-plugin/docs/rules/no-unused-expressions.md
  packages/eslint-plugin/docs/rules/no-unused-vars.md
  packages/eslint-plugin/docs/rules/no-use-before-define.md
  packages/eslint-plugin/docs/rules/no-useless-constructor.md
  packages/eslint-plugin/docs/rules/object-curly-spacing.md
  packages/eslint-plugin/docs/rules/padding-line-between-statements.md
  packages/eslint-plugin/docs/rules/quotes.md
  packages/eslint-plugin/docs/rules/require-await.md
  packages/eslint-plugin/docs/rules/semi.md
  packages/eslint-plugin/docs/rules/space-before-function-paren.md
  packages/eslint-plugin/docs/rules/space-infix-ops.md
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/parser/README.md
  packages/typescript-estree/README.md
  packages/typescript-estree/src/parser-options.ts
  packages/website/README.md
  packages/website/docusaurus.config.js
Labels: repo maintenance

#4195 docs: fix links
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
  CONTRIBUTING.md
  packages/eslint-plugin/README.md
  packages/parser/README.md
  packages/scope-manager/README.md
  packages/typescript-estree/README.md
Labels: documentation

#4199 fix(experimental-utils): export RuleCreator interfaces
  packages/experimental-utils/src/eslint-utils/RuleCreator.ts
Labels: bug

#4196 fix(eslint-plugin): [no-duplicate-imports] remove unnecessary type checking for `node.source`
  packages/eslint-plugin/src/rules/no-duplicate-imports.ts
Labels: bug

#4187 docs: added Algolia search to website
  packages/website/docusaurus.config.js
  packages/website/package.json
  yarn.lock
Labels: documentation

#4211 fix(scope-manager): support static class blocks
  packages/scope-manager/src/ScopeManager.ts
  packages/scope-manager/src/scope/ClassStaticBlockScope.ts
  packages/scope-manager/src/scope/Scope.ts
  packages/scope-manager/src/scope/ScopeBase.ts
  packages/scope-manager/src/scope/ScopeType.ts
Labels: bug

#4176 fix(eslint-plugin): [prefer-for-of] do nor error when iterating over this
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
Labels: bug, package: eslint-plugin

#4137 docs: fleshed out experimental-utils usage in Custom Rules docs
  .cspell.json
  docs/development/CUSTOM_RULES.md
Labels: documentation

#4066 feat(eslint-plugin): `array-type` distinguish whether readonly or not
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: enhancement, 1 approval

#4223 fix(eslint-plugin): ignore all whitespaces in comparison
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
Labels: bug, package: eslint-plugin

#4221 fix(eslint-plugin): [no-var-requires] do not report require created from createRequire
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/tests/rules/no-var-requires.test.ts
Labels: bug

#4219 docs: various improvements to documentations
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/docs/rules/class-literal-property-style.md
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/docs/rules/unified-signatures.md
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/remark/tabs.js
  packages/website/src/remark/tabs.license.md
  yarn.lock
Labels: documentation

#4197 chore: enable jsx-a11y, react, and react-hooks ESLint plugins internally
  package.json
  packages/website/.eslintrc.js
  packages/website/package.json
  packages/website/src/pages/index.tsx
  yarn.lock
Labels: repo maintenance

#4240 feat(scope-manager): update lib types
  packages/scope-manager/src/lib/dom.iterable.ts
  packages/scope-manager/src/lib/dom.ts
  packages/scope-manager/src/lib/es2021.intl.ts
  packages/scope-manager/src/lib/es2021.ts
  packages/scope-manager/src/lib/es5.ts
  packages/scope-manager/src/lib/index.ts
  packages/scope-manager/src/lib/webworker.iterable.ts
  packages/scope-manager/src/lib/webworker.ts
  packages/types/src/lib.ts
  packages/typescript-estree/src/parser.ts
Labels: enhancement
