Repository typescript-eslint/typescript-eslint, pull requests merged in 2021-07, with the labels that each got.

#3228 feat(eslint-plugin): [prefer-return-this-type] add a new rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/prefer-return-this-type.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-return-this-type.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/tests/rules/prefer-return-this-type.test.ts
Labels: 1 approval, enhancement: new plugin rule

#3516 feat(typescript-estree): add support for custom module resolution
  packages/parser/README.md
  packages/types/src/parser-options.ts
  packages/typescript-estree/README.md
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/fixtures/moduleResolver/file.ts
  packages/typescript-estree/tests/fixtures/moduleResolver/moduleResolver.js
  packages/typescript-estree/tests/fixtures/moduleResolver/something.ts
  packages/typescript-estree/tests/fixtures/moduleResolver/tsconfig.defaultProgram.json
  packages/typescript-estree/tests/fixtures/moduleResolver/tsconfig.json
  packages/typescript-estree/tests/lib/parse.test.ts
Labels: enhancement

#3471 chore: enable no-unsafe-return internally
  .eslintrc.js
  packages/eslint-plugin/src/rules/no-loss-of-precision.ts
  packages/eslint-plugin/tools/generate-rules-lists.ts
  packages/scope-manager/tests/util/serializers/TSESTreeNode.ts
  packages/typescript-estree/src/convert.ts
  tools/generate-contributors.ts
Labels: repo maintenance

#3564 feat(ast-spec): extract `ExportKind` & `ImportKind`
  packages/ast-spec/src/declaration/ExportAllDeclaration/spec.ts
  packages/ast-spec/src/declaration/ExportAndImportKind.ts
  packages/ast-spec/src/declaration/ExportDefaultDeclaration/spec.ts
  packages/ast-spec/src/declaration/ExportNamedDeclaration/spec.ts
  packages/ast-spec/src/declaration/ImportDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/spec.ts
Labels: refactor

#3569 refactor(experimental-utils): simplify `eslint-utils`' predicate types in `ast-utils` even more
  packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Labels: refactor

#3574 fix(experimental-utils): simplify `eslint-utils`' `findVariable`'s signature in `ast-utils`
  packages/experimental-utils/src/ast-utils/eslint-utils/scopeAnalysis.ts
Labels: bug

#3572 feat(eslint-plugin): [no-redeclare] ignoreDeclarationMerge of enum+namespace
  packages/eslint-plugin/docs/rules/no-redeclare.md
  packages/eslint-plugin/src/rules/no-redeclare.ts
  packages/eslint-plugin/tests/rules/no-redeclare.test.ts
Labels: enhancement: plugin rule option

#3581 fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] incorrect fix when condition is reversed
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
Labels: bug

#3560 feat(ast-spec): make `BaseNode` & `BaseToken` more type-safe
  packages/ast-spec/src/base/BaseNode.ts
  packages/ast-spec/src/base/BaseToken.ts
  packages/ast-spec/src/base/NodeOrTokenData.ts
  packages/ast-spec/src/index.ts
  packages/experimental-utils/src/ts-eslint/Rule.ts
  packages/typescript-estree/src/convert.ts
Labels: enhancement

#3592 docs(eslint-plugin): [no-use-before-define] fix typo and outdated issue
  packages/eslint-plugin/docs/rules/no-use-before-define.md
Labels: documentation

#3598 fix(eslint-plugin): [no-implied-eval] handle bind on nested member expressions
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Labels: bug

#3601 fix(eslint-plugin): [return-await] handle nested functions correctly
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug
