Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-10, with the labels that each got.

#5671 feat(eslint-plugin): allow using void as a default type for a generic argument if allowInGenericTypeArguments is specified
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/tests/rules/no-invalid-void-type.test.ts
Labels: awaiting response

#5712 docs: create .github/SECURITY.md policy
  .github/SECURITY.md
Labels: awaiting response

#5751 chore: unignore typescript and eslint from dependabot
  .github/dependabot.yml
Labels: repo maintenance

#5761 chore: switch from dependabot to Renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: awaiting response

#5750 feat(utils): add dependency constraint filtering for `RuleTester`
  packages/eslint-plugin-internal/jest.config.js
  packages/eslint-plugin/jest.config.js
  packages/utils/package.json
  packages/utils/src/eslint-utils/RuleTester.ts
  packages/utils/src/eslint-utils/batchedSingleLineTests.ts
  packages/utils/src/eslint-utils/index.ts
  packages/utils/src/eslint-utils/rule-tester/RuleTester.ts
  packages/utils/src/eslint-utils/rule-tester/dependencyConstraints.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/utils/tests/eslint-utils/rule-tester/RuleTester.test.ts
Labels: enhancement

#5770 chore: deduplicate after renovate updates
  .github/renovate.json
Labels: repo maintenance

#5801 chore: remove erroneous project reference from parser to utils
  packages/parser/tsconfig.build.json
  packages/parser/tsconfig.json
Labels: repo maintenance

#5800 chore: group renovate updates
  .github/renovate.json
  .github/renovate.json5
  .vscode/extensions.json
Labels: repo maintenance

#5814 chore(website): switch from Cypress to Playwright
  .github/actions/prepare-install/action.yml
  .github/renovate.json5
  .github/workflows/ci.yml
  .gitignore
  packages/website/.eslintrc.js
  packages/website/cypress/integration/index.spec.js
  packages/website/cypress/plugins/index.js
  packages/website/cypress/support/commands.js
  packages/website/cypress/support/index.js
  packages/website/cypress/utils.js
  packages/website/package.json
  packages/website/playwright.config.ts
  packages/website/tests/index.spec.ts
  packages/website/tsconfig.json
  yarn.lock
Labels: 1 approval

#5822 chore: group rollup in renovate updates
  .github/renovate.json5
Labels: repo maintenance

#5823 chore: remove deprecated `set-output` from actions
  .github/actions/prepare-install/action.yml
Labels: repo maintenance

#5840 feat(eslint-plugin): add no-unsafe-declaration-merging
  packages/eslint-plugin/docs/rules/no-unsafe-declaration-merging.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/strict.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-declaration-merging.ts
  packages/eslint-plugin/tests/rules/no-unsafe-declaration-merging.test.ts
Labels: awaiting response

#5850 chore: don't renovate `nx` or `@nrwl/workspace` for now
  .github/renovate.json5
Labels: repo maintenance

#5860 fix(type-utils): prevent stack overflow in `isTypeReadonly`
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: bug

#5762 feat(typescript-estree): clarify docs and error for program project without matching TSConfig
  docs/linting/TROUBLESHOOTING.md
  docs/linting/TYPED_LINTING.md
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/tests/fixtures/invalidFileErrors/tsconfig.extra.json
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
Labels: enhancement

#5834 chore: document and refactor 'extra' to 'parserSettings'
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/create-program/useProvidedPrograms.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parseSettings/inferSingleRun.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/website/src/components/linter/WebLinter.ts
  packages/website/src/components/linter/config.ts
Labels: 1 approval, refactor

#5864 docs: Mention wide globs performance implications in monorepos docs and parser README
  docs/linting/typed-linting/MONOREPOS.md
  packages/parser/README.md
Labels: documentation

#5036 fix(utils): removed `TRuleListener` generic from the `createRule`
  docs/linting/typed-linting/MONOREPOS.md
  packages/parser/README.md
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/create-program/useProvidedPrograms.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parseSettings/inferSingleRun.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/utils/src/eslint-utils/RuleCreator.ts
  packages/utils/src/ts-eslint/CLIEngine.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/website/src/components/FinancialContributors/index.tsx
  packages/website/src/components/linter/WebLinter.ts
  packages/website/src/components/linter/config.ts
Labels: breaking change

#5881 feat(scope-manager): ignore ECMA version
  packages/parser/src/parser.ts
  packages/parser/tests/lib/parser.ts
  packages/scope-manager/README.md
  packages/scope-manager/src/ScopeManager.ts
  packages/scope-manager/src/analyze.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/eslint-scope/get-declared-variables.test.ts
  packages/scope-manager/tests/eslint-scope/implied-strict.test.ts
  packages/scope-manager/tests/eslint-scope/map-ecma-version.test.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/website/src/components/linter/WebLinter.ts
Labels: enhancement, breaking change

#4863 feat: remove semantically invalid properties from TSEnumDeclaration, TSInterfaceDeclaration and TSModuleDeclaration
  packages/ast-spec/src/declaration/TSEnumDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/spec.ts
  packages/ast-spec/src/index.ts
  packages/ast-spec/src/unions/Modifier.ts
  packages/scope-manager/src/referencer/TypeVisitor.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/snapshots/typescript/basics/abstract-interface.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/errorRecovery/enum-with-keywords.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/errorRecovery/interface-implements.src.ts.shot
Labels: breaking change, AST

#5381 fix(eslint-plugin): remove valid-typeof disable in eslint-recommended
  packages/eslint-plugin/src/configs/eslint-recommended.ts
Labels: package: eslint-plugin, breaking change, 1 approval

#5256 feat(utils): remove (ts-)eslint-scope types
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/ts-eslint-scope/Definition.ts
  packages/utils/src/ts-eslint-scope/Options.ts
  packages/utils/src/ts-eslint-scope/PatternVisitor.ts
  packages/utils/src/ts-eslint-scope/README.md
  packages/utils/src/ts-eslint-scope/Reference.ts
  packages/utils/src/ts-eslint-scope/Referencer.ts
  packages/utils/src/ts-eslint-scope/Scope.ts
  packages/utils/src/ts-eslint-scope/ScopeManager.ts
  packages/utils/src/ts-eslint-scope/Variable.ts
  packages/utils/src/ts-eslint-scope/analyze.ts
  packages/utils/src/ts-eslint-scope/index.ts
  yarn.lock
Labels: breaking change, 1 approval

#5399 fix(eslint-plugin): [explicit-module-boundary-types] remove shouldTrackReferences option from schema
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
Labels: breaking change, 1 approval

#5890 feat(typescript-estree): deprecate createDefaultProgram
  packages/parser/README.md
  packages/typescript-estree/README.md
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/website/src/components/linter/config.ts
Labels: enhancement, breaking change, 1 approval

#5274 feat(eslint-plugin): [no-invalid-void-type] better report message for void used as a constituent inside a function return type
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/tests/rules/no-invalid-void-type.test.ts
Labels: enhancement

#5893 fix(typescript-estree): don't allow single-run unless we're in type-aware linting mode
  packages/typescript-estree/src/parseSettings/inferSingleRun.ts
Labels: bug

#5901 fix(eslint-plugin): [no-extra-parens] handle type assertion in extends clause
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
Labels: awaiting response

#5904 docs(eslint-plugin): [consistent-type-imports] make a note about `parserOptions.emitDecoratorMetadata`
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
Labels: documentation

#5896 feat(utils): add `RuleTester` API for top-level dependency constraints
  packages/utils/src/eslint-utils/rule-tester/RuleTester.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/utils/tests/eslint-utils/rule-tester/RuleTester.test.ts
Labels: enhancement

#5906 fix(ast-spec): add TSQualifiedName to TypeNode union
  packages/ast-spec/src/unions/TypeNode.ts
  packages/eslint-plugin/src/rules/sort-type-constituents.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/tests/rules/sort-type-constituents.test.ts
  packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
Labels: bug
