Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-11, with the labels that each got.

#5913 fix(ast-spec): correct misnamed ExportNamedDeclaration AST type
  packages/ast-spec/src/declaration/ExportNamedDeclaration/spec.ts
Labels: bug

#5895 chore(eslint-plugin-internal): [plugin-test-formatting] support random object literal tests
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-case-insensitive-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
Labels: 1 approval, repo maintenance

#5918 feat: drop support for node v12
  package.json
  packages/ast-spec/package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/experimental-utils/package.json
  packages/parser/package.json
  packages/scope-manager/package.json
  packages/type-utils/package.json
  packages/types/package.json
  packages/typescript-estree/package.json
  packages/utils/package.json
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
Labels: breaking change

#5874 docs: add maintainer guide (take two)
  .cspell.json
  .github/replies.yml
  docs/MAINTENANCE.md
  docs/maintenance/ISSUES.md
  docs/maintenance/RELEASES.md
  docs/maintenance/VERSIONING.md
  packages/website/sidebars/sidebar.base.js
Labels: documentation

#5915 feat: bump minimum supported TS version to 4.2.4
  README.md
  package.json
  packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/tests/rules/no-non-null-asserted-optional-chain.test.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/src/version-check.ts
  yarn.lock
Labels: enhancement, breaking change

#5594 feat(eslint-plugin): [prefer-optional-chain] support suggesting `!foo || !foo.bar` as a valid match for the rule
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: enhancement, 1 approval

#5050 feat(eslint-plugin): [consistent-type-imports] support fixing to inline types
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
Labels: enhancement: plugin rule option, awaiting response

#5967 feat(utils): remove obsolete `meta.docs.suggestion` rule type
  packages/utils/src/ts-eslint/Rule.ts
Labels: breaking change

#5902 fix(eslint-plugin): [no-shadow] handle false positives on generics and parameters
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
Labels: bug

#5612 docs(website): help troubleshoot issues with multiple parsers
  docs/linting/TROUBLESHOOTING.md
Labels: awaiting response

#5992 fix(eslint-plugin): [prefer-optional-chain] handle binary expressions in negated or
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: awaiting response

#5234 feat(eslint-plugin): [prefer-nullish-coalescing]: add support for assignment expressions
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: breaking change

#5986 docs(eslint-plugin): [no-shadow] add FAQ about enum members
  packages/eslint-plugin/docs/rules/no-shadow.md
Labels: documentation

#5999 fix(typescript-estree): don't consider a cached program unless it's specified in the current `parserOptions.project` config
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
  packages/typescript-estree/src/create-program/createWatchProgram.ts
Labels: bug

#5916 tests: add dependency constraints to eslint-plugin tests
  packages/eslint-plugin/tests/rules/consistent-type-exports.test.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-case-insensitive-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
  packages/eslint-plugin/tests/rules/no-empty-function.test.ts
  packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
  packages/eslint-plugin/tests/rules/no-redundant-type-constituents.test.ts
  packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
  packages/utils/src/eslint-utils/rule-tester/RuleTester.ts
  packages/utils/tests/eslint-utils/rule-tester/RuleTester.test.ts
Labels: blocked by another PR, tests

#5998 feat(eslint-plugin): [adjacent-overload-signatures] check BlockStatement nodes
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/tests/rules/adjacent-overload-signatures.test.ts
Labels: enhancement, awaiting response

#6059 fix(scope-manager): add support for TS4.9 satisfies expression
  .prettierignore
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/type-assertion/satisfies.ts
  packages/scope-manager/tests/fixtures/type-assertion/satisfies.ts.shot
Labels: bug

#5719 chore(website): add details to Configurations page
  docs/linting/CONFIGURATIONS.md
  docs/linting/CONFIGURATIONS.mdx
  docs/linting/troubleshooting/FORMATTING.md
Labels: documentation

#6073 fix(eslint-plugin): [keyword-spacing] prevent crash on no options
  packages/eslint-plugin/src/rules/keyword-spacing.ts
Labels: bug

#6075 chore: add action to enforce semantic-pr titles
  .github/workflows/semantic-pr-titles.yml
  CONTRIBUTING.md
Labels: repo maintenance

#6076 fix(typescript-estree): stub out `ts.SatisfiesExpression` on old TS versions
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
Labels: bug

#5859 fix(eslint-plugin): [member-ordering] support private fields
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement: plugin rule option, 1 approval

#5252 feat: made BaseNode.parent non-optional
  packages/ast-spec/src/index.ts
  packages/ast-spec/src/special/Program/spec.ts
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/src/rules/consistent-generic-constructors.ts
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/init-declarations.ts
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/src/rules/no-misused-new.ts
  packages/eslint-plugin/src/rules/no-namespace.ts
  packages/eslint-plugin/src/rules/no-redeclare.ts
  packages/eslint-plugin/src/rules/no-redundant-type-constituents.ts
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/src/rules/prefer-function-type.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/prefer-return-this-type.ts
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/src/rules/space-before-function-paren.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/src/rules/typedef.ts
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/src/util/getFunctionHeadLoc.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/scope-manager/src/referencer/VisitorBase.ts
  packages/types/src/ts-estree.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/website/src/components/ASTViewerESTree.tsx
Labels: breaking change, AST

#6043 fix(eslint-plugin): [prefer-readonly] report if a member's property is reassigned
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
Labels: awaiting response

#5965 feat(eslint-plugin): [member-ordering] add a required option for required vs. optional member ordering
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-optionalMembers.test.ts
  packages/eslint-plugin/tests/util/misc.test.ts
Labels: 1 approval

#6123 chore: remove bug tag from pre-filled bug search
  .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
Labels: repo maintenance

#6083 fix(eslint-plugin): [prefer-optional-chain] collect MetaProperty type
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: awaiting response

#6039 chore: added blog article: 'ASTs and TypeScript-ESLint'
  .cspell.json
  docs/development/CUSTOM_RULES.md
  docs/development/architecture/ASTS.md
  netlify.toml
  packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
  packages/website/sidebars/sidebar.base.js
Labels: documentation, 1 approval
