Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-03, with the labels that each got.

#4343 fix(eslint-plugin): [prefer-readonly-parameter-types] handle class sharp private field and member without throwing error
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/src/propertyTypes.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: bug

#4401 fix(eslint-plugin): [return-await] correct autofixer in binary expression
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/util/getOperatorPrecedence.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug

#4582 fix(eslint-plugin): [naming-convention] cover case that requires quotes
  packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts
  packages/eslint-plugin/tests/rules/naming-convention.test.ts
Labels: bug, 1 approval

#4599 test(eslint-plugin): split up naming-convention
  packages/eslint-plugin/tests/rules/naming-convention/cases/accessor.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/class.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/createTestCases.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/default.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/enum.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/enumMember.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/function.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/interface.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/method.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/parameter.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/parameterProperty.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/property.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/typeAlias.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/typeParameter.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/variable.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/naming-convention.test.ts
Labels: tests

#4620 fix(eslint-plugin): [no-misused-promises] factor thenable returning function overload signatures
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: bug

#4584 chore: use swc for tests instead of Babel
  jest.config.base.js
  package.json
  packages/ast-spec/jest.config.js
  packages/eslint-plugin-internal/jest.config.js
  packages/eslint-plugin-tslint/jest.config.js
  packages/eslint-plugin/jest.config.js
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/src/rules/prefer-function-type.ts
  packages/experimental-utils/jest.config.js
  packages/parser/jest.config.js
  packages/scope-manager/jest.config.js
  packages/type-utils/jest.config.js
  packages/types/jest.config.js
  packages/typescript-estree/jest.config.js
  packages/typescript-estree/package.json
  packages/utils/jest.config.js
  packages/visitor-keys/jest.config.js
  tests/integration/jest.config.js
  tsconfig.eslint.json
  yarn.lock
Labels: tests

#4623 feat(eslint-plugin): [no-misused-promises] add granular options within `checksVoidReturns`
  packages/eslint-plugin/docs/rules/no-misused-promises.md
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: enhancement: plugin rule option

#4362 tests: add cypress-axe test for homepage
  .github/workflows/ci.yml
  .gitignore
  packages/website/cypress.json
  packages/website/cypress/integration/index.spec.js
  packages/website/cypress/plugins/index.js
  packages/website/cypress/support/commands.js
  packages/website/cypress/support/index.js
  packages/website/cypress/utils.js
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/css/custom.css
  packages/website/src/pages/index.tsx
  yarn.lock
Labels: documentation, tests

#4626 chore: update workflow actions
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/generate-contributors.yml
  .github/workflows/update-sponsors.yml
Labels: repo maintenance

#4639 docs: remove node_modules from .eslintignore
  docs/linting/README.md
Labels: 1 approval

#4651 chore: remove naming convention todo from eslintrc
  .eslintrc.js
Labels: repo maintenance

#4649 docs(eslint-plugin): clarified no-floating-promises and no-misused-promises
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/README.md
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/docs/rules/no-misused-promises.md
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
Labels: documentation

#4654 chore: switch update-sponsors to create a PR, not a commit
  .github/workflows/update-sponsors.yml
Labels: repo maintenance

#4670 chore: change update-sponsors.yml to weekly
  .github/workflows/update-sponsors.yml
Labels: repo maintenance

#4646 feat(parser): add `parserOptions.emitDecoratorMetadata`
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/parser/README.md
  packages/parser/src/parser.ts
  packages/types/src/parser-options.ts
Labels: enhancement

#4535 fix(scope-manager): incorrect reference for this within a jsx identifier
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/jsx/this-jsxidentifier.tsx
  packages/scope-manager/tests/fixtures/jsx/this-jsxidentifier.tsx.shot
Labels: bug

#4656 fix(utils): RuleTester: Only call afterAll if defined
  packages/utils/src/eslint-utils/RuleTester.ts
Labels: bug

#4685 fix(eslint-plugin): [consistent-type-assertions] enforce assertionStyle for `const` assertions
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Labels: bug

#4430 feat(eslint-plugin): [prefer-optional-chain] support logical with empty object
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: enhancement

#4707 fix: code container hiding navigation menu
  packages/website/src/components/Playground.module.css
Labels: awaiting response

#4718 feat(eslint-plugin): [no-this-alias] report on assignment expressions
  packages/eslint-plugin/src/rules/no-this-alias.ts
  packages/eslint-plugin/tests/rules/no-this-alias.test.ts
Labels: enhancement, 1 approval

#4603 feat(eslint-plugin): [no-shadow] ignoreOnInitialization option
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: enhancement

#4768 docs(website): add missing typescript options to playground
  packages/website/src/components/config/ConfigTypeScript.tsx
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/tsConfigOptions.json
Labels: package: website

#4770 fix(website): do not update lib target on every config change
  packages/website/src/components/editor/LoadedEditor.tsx
Labels: package: website

#4771 fix(website): correct dark mode color regression
  packages/website/src/css/custom.css
Labels: package: website
