Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-12, with the labels that each got.

#6112 chore(eslint-plugin): remove deprecated rules for v6
  packages/eslint-plugin/docs/rules/no-duplicate-imports.md
  packages/eslint-plugin/docs/rules/no-implicit-any-catch.md
  packages/eslint-plugin/docs/rules/no-parameter-properties.md
  packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-duplicate-imports.ts
  packages/eslint-plugin/src/rules/no-implicit-any-catch.ts
  packages/eslint-plugin/src/rules/no-parameter-properties.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/src/util/getESLintCoreRule.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/no-duplicate-imports.test.ts
  packages/eslint-plugin/tests/rules/no-implicit-any-catch.test.ts
  packages/eslint-plugin/tests/rules/no-parameter-properties.test.ts
  packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: awaiting response

#5943 feat(eslint-plugin): [no-floating-promises] add suggestion fixer to add an 'await'
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: enhancement

#6257 fix(ast-spec): correct some incorrect ast types
  packages/ast-spec/src/expression/ArrayExpression/spec.ts
  packages/ast-spec/src/expression/MemberExpression/spec.ts
  packages/ast-spec/src/unions/ObjectLiteralElement.ts
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
Labels: bug

#6281 feat(eslint-plugin): specify which method is unbound and added test case
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
Labels: awaiting response
