Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-05, with the labels that each got.

#4873 docs: overhauled member-ordering docs and types
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
Labels: documentation

#4880 fix(ast-spec): correct `AwaitExpression.argument` type
  packages/ast-spec/src/expression/AwaitExpression/spec.ts
Labels: bug, awaiting response

#4898 fix(eslint-plugin): [no-restricted-imports] allow type import as long as there's one matching pattern
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
Labels: bug

#4896 feat(utils): update eslint types
  packages/utils/src/ts-eslint/ESLint.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/utils/src/ts-eslint/SourceCode.ts
Labels: enhancement

#4901 fix(eslint-plugin): [no-unnecessary-type-constraint] change to suggestion fix, fix multiple trailing comma failures
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/README.md
  packages/eslint-plugin/docs/rules/no-unnecessary-type-constraint.md
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts
Labels: bug

#4897 chore: replace issue templates with issue forms
  .github/ISSUE_TEMPLATE/1-bug-report-plugin.yaml
  .github/ISSUE_TEMPLATE/2-enhancement-rule-option.yaml
  .github/ISSUE_TEMPLATE/3-enhancement-new-rule.yaml
  .github/ISSUE_TEMPLATE/4-enhancement-new-base-rule-extension.yaml
  .github/ISSUE_TEMPLATE/5-documentation-request.yml
  .github/ISSUE_TEMPLATE/6-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/7-enhancement-other.yaml
  .github/ISSUE_TEMPLATE/8-bug-report-complex.yaml
  .github/ISSUE_TEMPLATE/README.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/documentation-request.yml
  .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
  .github/ISSUE_TEMPLATE/eslint-plugin-typescript.yml
  .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
  .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
  .github/ISSUE_TEMPLATE/typescript-eslint-type-utils.md
  .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
  .github/ISSUE_TEMPLATE/typescript-estree.md
Labels: repo maintenance

#4909 docs: improve linting getting started guide
  .markdownlint.json
  docs/linting/README.md
Labels: documentation

#4927 docs(eslint-plugin): [parameter-properties] improve docs
  packages/eslint-plugin/docs/rules/parameter-properties.md
Labels: documentation

#4955 chore: update "fallback" issue template so it points at the issue chooser
  .github/ISSUE_TEMPLATE.md
Labels: repo maintenance

#4952 chore: bump dependencies
  .github/workflows/ci.yml
  .nxignore
  package.json
  packages/ast-spec/package.json
  packages/ast-spec/tests/util/parsers/typescript-estree-import.ts
  packages/ast-spec/tests/util/parsers/typescript-estree.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/naming-convention-utils/format.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
  packages/parser/package.json
  packages/scope-manager/README.md
  packages/type-utils/package.json
  packages/typescript-estree/package.json
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
  packages/website/package.json
  tests/integration/tests/__snapshots__/markdown.test.ts.snap
  tests/integration/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
  tests/integration/tests/__snapshots__/typescript-and-tslint-plugins-together.test.ts.snap
  tests/integration/tests/__snapshots__/vue-jsx.test.ts.snap
  tests/integration/tests/__snapshots__/vue-sfc.test.ts.snap
  yarn.lock
Labels: repo maintenance

#4926 test: correct execution of test and dev scripts on Windows machines
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/ast-fixtures.test.ts
Labels: tests, repo maintenance

#4968 chore: bump primary node version for CI
  .github/workflows/ci.yml
Labels: repo maintenance

#4971 fix(eslint-plugin): [array-type] in fixer add missing parens for constructor types #4756
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: bug, package: eslint-plugin

#4970 feat(eslint-plugin): Add BigInt object type to default ban-types list
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/src/rules/ban-types.ts
Labels: enhancement

#4960 chore: bump docusaurus, use docusaurus/preset-classic
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/clientModules.js
  packages/website/src/css/custom.css
  packages/website/src/css/prism.css
  packages/website/src/theme/prism-include-languages.js
  yarn.lock
Labels: repo maintenance

#4958 fix(eslint-plugin): [typedef] stop enforcing rule for assignment expressions
  packages/eslint-plugin/src/rules/typedef.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
Labels: bug

#4923 feat(eslint-plugin): [no-empty-function] new allow option overrideMethods
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/tests/rules/no-empty-function.test.ts
Labels: enhancement: plugin rule option

#4830 feat(typescript-estree): `extends` constraints for `infer`
  packages/shared-fixtures/fixtures/typescript/types/conditional-infer-with-constraint.src.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/types/conditional-infer-with-constraint.src.ts.shot
Labels: AST

#4959 chore: improve CI by making it a workflow graph
  .github/actions/prepare-build/action.yml
  .github/actions/prepare-install/action.yml
  .github/workflows/ci.yml
  jest.config.base.js
  jest.preset.js
  packages/ast-spec/jest.config.js
  packages/eslint-plugin-internal/jest.config.js
  packages/eslint-plugin-tslint/jest.config.js
  packages/eslint-plugin/jest.config.js
  packages/scope-manager/jest.config.js
  packages/type-utils/jest.config.js
  packages/types/jest.config.js
  packages/utils/jest.config.js
  packages/visitor-keys/jest.config.js
Labels: repo maintenance

#4938 feat: [4.7] support instantiation expressions
  packages/ast-spec/src/ast-node-types.ts
  packages/ast-spec/src/expression/TSInstantiationExpression/spec.ts
  packages/ast-spec/src/expression/spec.ts
  packages/ast-spec/src/unions/Expression.ts
  packages/ast-spec/src/unions/Node.ts
  packages/shared-fixtures/fixtures/typescript/expressions/instantiation-expression.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/basics/instantiation-expression.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/expressions/instantiation-expression.src.ts.shot
  packages/visitor-keys/src/visitor-keys.ts
Labels: enhancement, AST

#5023 fix(eslint-plugin): [member-delimiter-style] autofixer result is not as expected with option `delimiter: 'none'`
  packages/eslint-plugin/src/rules/member-delimiter-style.ts
  packages/eslint-plugin/tests/rules/member-delimiter-style.test.ts
Labels: bug

#5025 fix(ast-spec): add `SpreadElement` to `ArrayExpression.elements`
  packages/ast-spec/src/expression/ArrayExpression/spec.ts
Labels: bug

#5035 chore: fix lock workflow after update
  .github/workflows/lock.yml
Labels: repo maintenance

#5039 docs(eslint-plugin): add triple-slash-reference options schema and defaults
  packages/eslint-plugin/docs/rules/triple-slash-reference.md
Labels: documentation

#4974 fix(eslint-plugin): [prefer-readonly] correct issue with anonymus functions
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
Labels: bug, package: eslint-plugin

#4916 chore(website): update report as issue to use new issue forms
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.tsx
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/lib/markdown.ts
Labels: enhancement, package: website

#5027 feat: [4.7] support new extensions
  .cspell.json
  .lintstagedrc
  docs/linting/README.md
  docs/linting/TROUBLESHOOTING.md
  package.json
  packages/ast-spec/package.json
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/README.md
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/eslint-recommended.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/util.test.ts
  packages/experimental-utils/package.json
  packages/parser/README.md
  packages/parser/package.json
  packages/parser/src/parser.ts
  packages/scope-manager/package.json
  packages/type-utils/package.json
  packages/types/package.json
  packages/typescript-estree/README.md
  packages/typescript-estree/package.json
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/getScriptKind.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/utils/package.json
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
  packages/website/package.json
Labels: enhancement

#5034 chore(website): rewrite WebLinter to typescript and fix support for ts 4.7
  packages/utils/src/ts-eslint/Linter.ts
  packages/website-eslint/src/linter/CompilerHost.js
  packages/website-eslint/src/linter/linter.js
  packages/website-eslint/src/linter/parser.js
  packages/website-eslint/types/index.d.ts
  packages/website/src/components/ASTViewerESTree.tsx
  packages/website/src/components/Playground.tsx
  packages/website/src/components/ast/serializer/serializerESTree.ts
  packages/website/src/components/ast/serializer/serializerScope.ts
  packages/website/src/components/ast/serializer/serializerTS.ts
  packages/website/src/components/config/ConfigEslint.tsx
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/createProvideCodeActions.ts
  packages/website/src/components/editor/loadSandbox.ts
  packages/website/src/components/editor/types.ts
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/linter/CompilerHost.ts
  packages/website/src/components/linter/WebLinter.ts
  packages/website/src/components/linter/config.ts
  packages/website/src/components/linter/lintCode.ts
  packages/website/src/components/linter/utils.ts
  packages/website/src/components/types.ts
Labels: enhancement, package: website

#5038 chore: fix generate contributors action
  .all-contributorsrc
  CONTRIBUTORS.md
  package.json
  tools/generate-contributors.ts
  yarn.lock
Labels: 1 approval, repo maintenance

#5053 feat(eslint-plugin): [no-misused-promises] warn when spreading promises
  packages/eslint-plugin/docs/rules/no-misused-promises.md
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: enhancement

#5078 chore: add website as an "other" package for issue forms
  .github/ISSUE_TEMPLATE/6-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/7-enhancement-other.yaml
Labels: repo maintenance

#5026 feat(eslint-plugin): [ban-ts-comment] add descriptionFormat option
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Labels: enhancement: plugin rule option

#5073 chore: use prettier to format generated sponsors.json
  packages/website/data/sponsors.json
  tools/generate-sponsors.ts
Labels: repo maintenance

#5041 feat(eslint-plugin): [space-infix-ops] missing error report for conditional types
  packages/eslint-plugin/src/rules/space-infix-ops.ts
  packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
Labels: enhancement, package: eslint-plugin

#5080 chore(website): pass user defined compilerOptions to linter
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/config.ts
  packages/website/src/components/editor/useSandboxServices.ts
Labels: bug, package: website

#5082 feat: bump dependency ranges to TypeScript 4.7
  package.json
  packages/typescript-estree/src/parser.ts
  yarn.lock
Labels: enhancement, dependencies

#5086 test: fix Cypress test flakes
  .github/actions/prepare-install/action.yml
  .github/workflows/ci.yml
Labels: repo maintenance

#5092 fix(eslint-plugin): [no-type-alias] handle Template Literal Types
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Labels: 1 approval

#5088 chore(website): update config editor and add tabs to playground
  packages/website/src/components/ASTViewerESTree.tsx
  packages/website/src/components/ASTViewerScope.tsx
  packages/website/src/components/ASTViewerTS.tsx
  packages/website/src/components/EditorTabs.tsx
  packages/website/src/components/ErrorsViewer.tsx
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/config/ConfigEslint.tsx
  packages/website/src/components/config/ConfigTypeScript.tsx
  packages/website/src/components/config/utils.ts
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/config.ts
  packages/website/src/components/editor/createProvideCodeActions.ts
  packages/website/src/components/editor/types.ts
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/lib/markdown.ts
  packages/website/src/components/linter/WebLinter.ts
  packages/website/src/components/linter/lintCode.ts
  packages/website/src/components/linter/utils.ts
  packages/website/src/components/modals/Modal.module.css
  packages/website/src/components/types.ts
Labels: package: website

#4981 chore: removed commitlint
  .eslintignore
  .husky/commit-msg
  commitlint.config.js
  package.json
  yarn.lock
Labels: repo maintenance

#5113 fix(eslint-plugin): [space-infix-ops] correct PropertyDefinition with typeAnnotation
  packages/eslint-plugin/src/rules/space-infix-ops.ts
  packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
Labels: bug, package: eslint-plugin
