Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-09, with the labels that each got.

#5582 fix(typescript-estree): don't double add decorators to a parameter property's parameter
  packages/shared-fixtures/fixtures/typescript/decorators/class-decorators/class-parameter-property.src.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/decorators/class-decorators/class-parameter-property.src.ts.shot
Labels: bug

#5580 fix(scope-manager): correct handling for class static blocks
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/tests/fixtures/class/declaration/static-external-ref.ts
  packages/scope-manager/tests/fixtures/class/declaration/static-external-ref.ts.shot
  packages/scope-manager/tests/fixtures/class/declaration/static-with-constructor.ts
  packages/scope-manager/tests/fixtures/class/declaration/static-with-constructor.ts.shot
Labels: bug

#5608 feat(docs): always expanding collapsible sidebar menus under docs
  packages/website/sidebars/sidebar.base.js
  packages/website/sidebars/sidebar.rules.js
Labels: awaiting response

#5539 fix(eslint-plugin): [strict-boolean-expressions] check all conditions in a logical operator chain
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: bug, awaiting response

#5611 docs: [no-parameter-properties] fix broken link
  packages/eslint-plugin/docs/rules/no-parameter-properties.md
Labels: awaiting response

#5625 chore(eslint-plugin): remove unused indent fork
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/indent-new-do-not-use/BinarySearchTree.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/TokenInfo.ts
  packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
  packages/eslint-plugin/tests/rules/indent/indent-eslint.test.ts
  packages/eslint-plugin/typings/functional-red-black-tree.d.ts
Labels: repo maintenance

#5660 chore: bump jest packages to v29
  package.json
  packages/parser/tests/lib/__snapshots__/services.ts.snap
  packages/scope-manager/tests/types/variable-definition.test.ts
  packages/typescript-estree/tests/lib/__snapshots__/convert.test.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semanticInfo.test.ts.snap
  packages/typescript-estree/tests/lib/parse.test.ts
  patches/typescript+4.8.3.patch
  tests/integration/tests/__snapshots__/eslint-v6.test.ts.snap
  tests/integration/tests/__snapshots__/markdown.test.ts.snap
  tests/integration/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
  tests/integration/tests/__snapshots__/typescript-and-tslint-plugins-together.test.ts.snap
  tests/integration/tests/__snapshots__/vue-jsx.test.ts.snap
  tests/integration/tests/__snapshots__/vue-sfc.test.ts.snap
  yarn.lock
Labels: RFC, dependencies

#5616 chore(website): uncollapse Rules sidebar by default again
  packages/website/sidebars/sidebar.rules.js
Labels: package: website

#5661 chore(deps): stub out unnecessary swc packages
  package.json
  yarn.lock
Labels: dependencies

#5593 chore(website): add 'Automated Rule Docs with Docusaurs and Remark' post
  .cspell.json
  .markdownlint.json
  packages/website/blog/2022-09-18-automated-rule-docs-with-docusaurus-and-remark.md
  packages/website/blog/ast-explorer-remark.png
  packages/website/docusaurusConfig.ts
  packages/website/plugins/generated-rule-docs.ts
Labels: package: website

#5667 chore(website): make playground code editor horizontally resizable
  packages/website/package.json
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/SplitPane/ConditionalSplitPane.tsx
  packages/website/src/components/SplitPane/SplitPane.module.css
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/hooks/useMediaQuery.ts
  patches/react-split-pane+0.1.92.patch
  yarn.lock
Labels: awaiting response, website: playground

#5682 docs: add description of resolution order of parserOptions.project
  docs/linting/typed-linting/MONOREPOS.md
Labels: awaiting response

#5663 chore(website): Enable react-hooks exhaustive deps rules
  packages/website/.eslintrc.js
  packages/website/src/components/ASTViewerTS.tsx
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.tsx
  packages/website/src/components/ast/Elements.tsx
  packages/website/src/components/ast/PropertyName.tsx
  packages/website/src/components/ast/SimpleItem.tsx
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/config/ConfigEslint.tsx
  packages/website/src/components/config/ConfigTypeScript.tsx
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/hooks/useDebouncedToggle.ts
  packages/website/src/components/inputs/Checkbox.tsx
  packages/website/src/components/modals/Modal.tsx
Labels: awaiting response
