Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-08, with the labels that each got.

#5413 feat(eslint-plugin): [prefer-as-const] adds support for class properties
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/tests/rules/prefer-as-const.test.ts
Labels: awaiting response

#5417 feat(eslint-plugin): [member-ordering] support static blocks
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering-alphabetically-case-insensitive-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering-alphabetically-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: awaiting response

#5402 chore(website): lower formatting rules in sidebar
  packages/website/sidebars/sidebar.rules.js
Labels: repo maintenance

#5380 chore: simplify prettier include lists
  .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
  .github/ISSUE_TEMPLATE/02-enhancement-rule-option.yaml
  .github/ISSUE_TEMPLATE/03-enhancement-new-rule.yaml
  .github/ISSUE_TEMPLATE/04-enhancement-new-base-rule-extension.yaml
  .github/ISSUE_TEMPLATE/05-documentation-request.yml
  .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
  .github/ISSUE_TEMPLATE/08-bug-report-complex.yaml
  .github/ISSUE_TEMPLATE/09-config-change.yaml
  .github/ISSUE_TEMPLATE/10-repo-maintenance.yaml
  .github/actions/prepare-build/action.yml
  .github/actions/prepare-install/action.yml
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/lock.yml
  .prettierignore
  package.json
Labels: repo maintenance

#5428 fix(eslint-plugin): [no-extra-parens] handle await with type assertion
  packages/eslint-plugin/src/rules/no-extra-parens.ts
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
Labels: awaiting response

#5453 fix: missing placeholders in violation messages for `no-unnecessary-type-constraint` and `no-unsafe-argument` (and enable `eslint-plugin/recommended` rules internally)
  .eslintrc.js
  packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-duplicate-enum-values.ts
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-implicit-any-catch.ts
  packages/eslint-plugin/src/rules/no-meaningless-void-operator.ts
  packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
  packages/eslint-plugin/src/rules/no-non-null-assertion.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/no-useless-empty-export.ts
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/src/rules/object-curly-spacing.ts
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/src/rules/prefer-enum-initializers.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
  packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
  packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts
  packages/eslint-plugin/tests/rules/prefer-as-const.test.ts
  packages/eslint-plugin/tests/rules/prefer-function-type.test.ts
Labels: awaiting response

#5422 fix(ast-spec): NewExpression argument can be SpreadElement now
  packages/ast-spec/src/expression/NewExpression/spec.ts
Labels: 1 approval

#5379 chore(eslint-plugin): stop linting rule output formatting in tests
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin-internal/tests/rules/no-poorly-typed-ts-props.test.ts
  packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
  packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
  packages/eslint-plugin/tests/rules/consistent-generic-constructors.test.ts
  packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
  packages/eslint-plugin/tests/rules/consistent-type-exports.test.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
  packages/eslint-plugin/tests/rules/no-confusing-void-expression.test.ts
  packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
  packages/eslint-plugin/tests/rules/no-extra-non-null-assertion.test.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/rules/no-implicit-any-catch.test.ts
  packages/eslint-plugin/tests/rules/no-meaningless-void-operator.test.ts
  packages/eslint-plugin/tests/rules/no-non-null-asserted-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/rules/no-non-null-asserted-optional-chain.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
  packages/eslint-plugin/tests/rules/prefer-enum-initializers.test.ts
  packages/eslint-plugin/tests/rules/prefer-function-type.test.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
  packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
Labels: repo maintenance

#5493 chore: update eslint-plugin-eslint-plugin to 5.0.5
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/src/rules/no-explicit-any.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  yarn.lock
Labels: dependencies

#5491 chore: bump Prettier to 2.7
  .prettierignore
  package.json
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments1.ts
  tests/integration/fixtures/vue-sfc/Hello.vue
  tests/integration/tests/__snapshots__/vue-sfc.test.ts.snap
  yarn.lock
Labels: repo maintenance

#5419 feat(types): add unbound property in parser options
  packages/types/src/parser-options.ts
Labels: enhancement

#5506 chore: remove opencollective sponsors from the root readme
  README.md
Labels: documentation

#5266 feat(eslint-plugin): [prefer-optional-chain] support suggesting `!foo || !foo.bar` as a valid match for the rule
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
  packages/typescript-estree/src/convert.ts
  packages/utils/src/eslint-utils/getParserServices.ts
  packages/website/src/components/RulesTable/index.tsx
Labels: enhancement: plugin rule option, 1 approval

#5512 chore: test node v14 on ci.yml
  .github/workflows/ci.yml
Labels: repo maintenance

#5516 chore(website): generated rule Resources with source links
  packages/website/plugins/generated-rule-docs.ts
Labels: documentation, package: website

#5377 chore: bump Docusaurus to 2.0
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/fixture.ts
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/assertion/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/website/package.json
  packages/website/src/components/ErrorsViewer.tsx
  packages/website/src/pages/play.tsx
  packages/website/src/theme/CodeBlock/Content/String.tsx
  packages/website/tsconfig.json
  yarn.lock
Labels: dependencies

#5492 feat(eslint-plugin): [explicit-member-accessibility] suggest adding explicit accessibility specifiers
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
Labels: enhancement, awaiting response

#4545 chore(utils): use `Extract` generic for `ast-utils`' `predicates`' helper functions
  packages/ast-spec/src/token/spec.ts
  packages/ast-spec/src/type/TSAbstractKeyword/spec.ts
  packages/ast-spec/src/type/TSAsyncKeyword/spec.ts
  packages/ast-spec/src/type/TSDeclareKeyword/spec.ts
  packages/ast-spec/src/type/TSExportKeyword/spec.ts
  packages/ast-spec/src/type/TSIntrinsicKeyword/spec.ts
  packages/ast-spec/src/type/TSPrivateKeyword/spec.ts
  packages/ast-spec/src/type/TSProtectedKeyword/spec.ts
  packages/ast-spec/src/type/TSPublicKeyword/spec.ts
  packages/ast-spec/src/type/TSReadonlyKeyword/spec.ts
  packages/ast-spec/src/type/TSStaticKeyword/spec.ts
  packages/ast-spec/src/type/spec.ts
  packages/ast-spec/src/unions/Modifier.ts
  packages/ast-spec/src/unions/Node.ts
  packages/ast-spec/src/unions/TypeNode.ts
  packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
  packages/utils/src/ast-utils/helpers.ts
Labels: awaiting response, refactor

#5558 test: add fixtures for exported classes with decorators
  packages/shared-fixtures/fixtures/typescript/decorators/class-decorators/export-default-class-decorator.src.ts
  packages/shared-fixtures/fixtures/typescript/decorators/class-decorators/export-named-class-decorator.src.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/snapshots/typescript/decorators/class-decorators/export-default-class-decorator.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/decorators/class-decorators/export-named-class-decorator.src.ts.shot
Labels: tests

#5564 fix(eslint-plugin): revert #5266
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Labels: bug

#5574 fix(typescript-estree): fix decorator regression for pre TS4.8
  package.json
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/getModifiers.ts
  patches/typescript+4.8.2.patch
  yarn.lock
Labels: bug

#5575 chore(website): fix playground
  packages/website-eslint/rollup.config.js
  packages/website-eslint/src/mock/globby.js
  packages/website-eslint/src/mock/is-glob.js
  packages/website-eslint/src/mock/semver.js
Labels: bug
