Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-01, with the labels that each got.

#4381 chore: added missing implicit dependency on types to eslint-plugin
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-estree/project.json
Labels: repo maintenance

#4393 docs: fix typo in license section in README.md
  README.md
Labels: documentation

#4415 feat(type-utils): make isTypeReadonly's options param optional
  packages/type-utils/src/isTypeReadonly.ts
Labels: enhancement

#4371 docs: re-ran generate-sponsors and expanded homepage listing
  package.json
  packages/website/data/sponsors.json
  packages/website/src/components/FinancialContributors.module.css
  packages/website/src/components/FinancialContributors.tsx
  packages/website/src/pages/index.tsx
  packages/website/src/pages/styles.module.css
  tools/generate-contributors.ts
  tools/generate-sponsors.ts
  tools/generate-website-dts.ts
  yarn.lock
Labels: documentation

#4425 docs(type-utils): remove duplicate line from issue template
  .github/ISSUE_TEMPLATE/typescript-eslint-type-utils.md
Labels: repo maintenance

#4411 fix(eslint-plugin): [no-magic-numbers] handle bigint in class props
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
Labels: bug

#4416 test(type-utils): add basic tests for isTypeReadonly
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: tests

#4332 refactor(eslint-plugin): [restrict-plus-operands] add better error messages
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
Labels: repo maintenance

#4453 test(type-utils): fix incorrect utils import
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: tests

#4250 fix(eslint-plugin): [explicit-function-return-type] support AllowTypedFunctionExpression within AllowHigherOrderFunction
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: bug

#4448 fix(eslint-plugin): [no-invalid-this] crash when used with eslint 8.7.0
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: bug

#4417 fix(type-utils): check IndexSignature internals when checking isTypeReadonly
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: bug

#4419 fix(type-utils): union types always being marked as readonly
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: bug

#4458 fix(eslint-plugin): [no-extra-semi] false negatives when used with eslint 8.3.0
  package.json
  packages/eslint-plugin/src/rules/no-extra-semi.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
  yarn.lock
Labels: bug

#4421 fix(type-utils): isTypeReadonly now handles conditional types
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: bug

#4429 fix(type-utils): intersection types involving readonly arrays are now handled in most cases
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
Labels: bug

#4464 docs: Add missing comma in CUSTOM_RULES.md
  docs/development/CUSTOM_RULES.md
Labels: documentation

#4372 chore(website): added cron job to update sponsors data daily
  .github/workflows/update-sponsors.yml
Labels: repo maintenance
