Repository typescript-eslint/typescript-eslint, pull requests merged in 2022-07, with the labels that each got.

#5283 docs(eslint-plugin): [ban-ts-comment] include descriptionFormat
  packages/eslint-plugin/docs/rules/ban-ts-comment.md
Labels: documentation

#5280 fix(eslint-plugin): [consistent-indexed-object-style] fix record mode fixer for generics with a default value
  packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
  packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Labels: bug

#5331 fix(scope-manager): allow visiting of constraint in infer type
  .prettierignore
  packages/scope-manager/src/referencer/TypeVisitor.ts
  packages/scope-manager/tests/fixtures/type-declaration/infer-type-constraint.ts
  packages/scope-manager/tests/fixtures/type-declaration/infer-type-constraint.ts.shot
Labels: bug, package: scope-manager

#5320 docs(eslint-plugin): [comma-dangle] fix incorrect section heading
  packages/eslint-plugin/docs/rules/comma-dangle.md
Labels: documentation

#5342 fix(eslint-plugin): [no-inferrable] fix optional param to valid code
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
Labels: bug

#5288 feat(eslint-plugin): [consistent-generic-ctors] check class field declaration
  packages/eslint-plugin/src/rules/consistent-generic-constructors.ts
  packages/eslint-plugin/tests/rules/consistent-generic-constructors.test.ts
Labels: enhancement

#5311 fix(eslint-plugin): [typedef] Support nested array destructuring with type annotation
  packages/eslint-plugin/src/rules/typedef.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
Labels: bug

#5248 chore(website): streamlined Getting Started docs
  .cspell.json
  _redirects
  docs/README.md
  docs/development/architecture/PACKAGES.md
  docs/linting/CONFIGURATIONS.md
  docs/linting/MONOREPO.md
  docs/linting/README.md
  docs/linting/TROUBLESHOOTING.md
  docs/linting/TYPED_LINTING.md
  docs/linting/troubleshooting/TSLINT.md
  docs/linting/typed-linting/MONOREPOS.md
  packages/eslint-plugin/README.md
  packages/eslint-plugin/ROADMAP.md
  packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md
  packages/eslint-plugin/src/configs/README.md
  packages/parser/README.md
  packages/website/docusaurusConfig.ts
  packages/website/sidebars/sidebar.base.js
Labels: package: website

#5341 chore(website): add current version of typescript to playground dropdown
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/inputs/Dropdown.tsx
Labels: bug, package: website, website: playground

#5355 fix(scope-manager): handle typeParameters of TSInstantiationExpression
  .prettierignore
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments1.ts
  packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments1.ts.shot
  packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments2.ts
  packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments2.ts.shot
Labels: bug

#4965 feat(eslint-plugin): [prefer-nullish-coalescing] add ignoreTernaryTests option
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/isNodeEqual.ts
  packages/eslint-plugin/src/util/isNullLiteral.ts
  packages/eslint-plugin/src/util/isUndefinedIdentifier.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/util/isNodeEqual.test.ts
Labels: enhancement: plugin rule option

#5313 docs(website): increase 'get started' button contrast
  packages/website/src/pages/index.tsx
  packages/website/src/pages/styles.module.css
Labels: package: website
