Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-07, with the labels that each got.

#6397 feat(eslint-plugin): [prefer-optional-chain] handle cases where the first operands are unrelated to the rest of the chain and add type info
  packages/ast-spec/src/expression/BinaryExpression/BinaryOperatorToText.ts
  packages/ast-spec/src/expression/BinaryExpression/spec.ts
  packages/ast-spec/tests/BinaryOperatorToText.type-test.ts
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/configs/stylistic.ts
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/PreferOptionalChainOptions.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/compareNodes.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/util/getOperatorPrecedence.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/base-cases.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
  packages/eslint-plugin/tests/schema-snapshots/prefer-optional-chain.shot
  packages/scope-manager/src/referencer/VisitorBase.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/simple-traverse.ts
  packages/utils/src/eslint-utils/getParserServices.ts
  packages/visitor-keys/src/visitor-keys.ts
Labels: enhancement: new plugin rule, breaking change

#6487 feat(eslint-plugin): [prefer-nullish-coalescing] add `ignorePrimitives` option
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: enhancement: plugin rule option

#6938 fix(eslint-plugin): [comma-spacing] allow no space after trailing comma in objects and arrays
  packages/eslint-plugin/src/rules/comma-spacing.ts
  packages/eslint-plugin/tests/rules/comma-spacing.test.ts
Labels: bug, formatting

#6947 fix(eslint-plugin): fix schemas across several rules and add schema tests
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/src/rules/parameter-properties.ts
  packages/eslint-plugin/tests/areOptionsValid.test.ts
  packages/eslint-plugin/tests/areOptionsValid.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
  packages/eslint-plugin/tests/schema-snapshots/parameter-properties.shot
  packages/eslint-plugin/tests/schemas.test.ts
  packages/integration-tests/tools/integration-test-base.ts
  packages/rule-schema-to-typescript-types/package.json
  packages/rule-schema-to-typescript-types/src/generateArrayType.ts
  packages/rule-schema-to-typescript-types/src/generateObjectType.ts
  packages/rule-schema-to-typescript-types/src/generateType.ts
  packages/rule-schema-to-typescript-types/src/index.ts
  packages/utils/src/index.ts
  packages/utils/src/ts-utils/index.ts
  packages/utils/src/ts-utils/isArray.ts
  yarn.lock
Labels: bug, awaiting response, 1 approval

#7191 chore: bump dependency versions
  .prettierignore
  package.json
  packages/ast-spec/package.json
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/external-module-ref-string/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/external-module-ref-string/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-assignment/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-assignment/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-equal-declaration/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-equal-declaration/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-equal-type-declaration/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-equal-type-declaration/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-export-equal-declaration/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-export-equal-declaration/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-export-equal-type-declaration/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/import-export-equal-type-declaration/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/tests/fixtures.test.ts
  packages/ast-spec/tests/util/parsers/babel.ts
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/docs/rules/camelcase.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/tests/rules/quotes.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-extra-parens.shot
  packages/eslint-plugin/tests/schema-snapshots/semi.shot
  packages/integration-tests/fixtures/typescript-and-tslint-plugins-together/.eslintrc.js
  packages/integration-tests/package.json
  packages/integration-tests/tests/__snapshots__/typescript-and-tslint-plugins-together.test.ts.snap
  packages/integration-tests/tests/__snapshots__/vue-sfc.test.ts.snap
  packages/parser/tests/lib/services.ts
  packages/repo-tools/package.json
  packages/repo-tools/src/postinstall.mts
  packages/rule-tester/package.json
  packages/scope-manager/tests/fixtures.test.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/utils/package.json
  packages/website/package.json
  patches/@microsoft+api-extractor+7.36.1.patch
  patches/eslint+8.39.0.patch
  yarn.lock
Labels: dependencies

#7172 docs: add warnOnUnsupportedTypeScript warning message
  docs/packages/Parser.mdx
Labels: awaiting response

#7215 fix(eslint-plugin): include the rules types in the package
  packages/eslint-plugin/package.json
Labels: bug

#7205 chore: update some website dependencies
  package.json
  packages/ast-spec/tsconfig.json
  packages/website-eslint/package.json
  packages/website-eslint/src/index.js
  packages/website-eslint/tsconfig.json
  packages/website/package.json
  packages/website/src/components/ESQueryFilter.tsx
  packages/website/src/components/ErrorsViewer.tsx
  packages/website/src/components/FinancialContributors/Sponsor.tsx
  packages/website/src/components/FinancialContributors/Sponsors/index.tsx
  packages/website/src/components/FinancialContributors/Sponsors/styles.module.css
  packages/website/src/components/FinancialContributors/index.tsx
  packages/website/src/components/FinancialContributors/styles.module.css
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/RulesTable/index.tsx
  packages/website/src/components/SplitPane/ConditionalSplitPane.tsx
  packages/website/src/components/ast/ASTViewer.tsx
  packages/website/src/components/ast/DataRenderer.tsx
  packages/website/src/components/ast/HiddenItem.tsx
  packages/website/src/components/ast/PropertyName.tsx
  packages/website/src/components/ast/PropertyValue.tsx
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/config/ConfigEslint.tsx
  packages/website/src/components/config/ConfigTypeScript.tsx
  packages/website/src/components/inputs/Checkbox.tsx
  packages/website/src/components/inputs/CopyButton.tsx
  packages/website/src/components/inputs/Dropdown.tsx
  packages/website/src/components/inputs/Text.tsx
  packages/website/src/components/inputs/Tooltip.tsx
  packages/website/src/components/layout/ActionLabel.tsx
  packages/website/src/components/layout/AlertBlock.tsx
  packages/website/src/components/layout/EditorTabs.tsx
  packages/website/src/components/layout/Expander.tsx
  packages/website/src/components/layout/InputLabel.tsx
  packages/website/src/components/layout/Loader.tsx
  packages/website/src/pages/index.tsx
  packages/website/src/pages/play.tsx
  packages/website/src/theme/CodeBlock/Content/String.tsx
  packages/website/src/theme/MDXComponents/Feature.tsx
  packages/website/src/vendor/sandbox.d.ts
  packages/website/src/vendor/typescript-vfs.d.ts
  yarn.lock
Labels: dependencies

#6881 fix(eslint-plugin): [no-floating-promises] false negative calling .then with second argument undefined
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-floating-promises.shot
Labels: bug, awaiting response

#6754 feat(typescript-estree): add EXPERIMENTAL_useProjectService option to use TypeScript project service
  .github/workflows/ci.yml
  .vscode/launch.json
  docs/packages/TypeScript_ESTree.mdx
  packages/eslint-plugin-tslint/src/rules/config.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
  packages/parser/tests/lib/parser.ts
  packages/rule-tester/tests/RuleTester.test.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/clear-caches.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/create-program/useProvidedPrograms.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/__snapshots__/semanticInfo.test.ts.snap
  packages/typescript-estree/tests/lib/createProjectService.test.ts
  packages/typescript-estree/tests/lib/parse.project-true.test.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/persistentParse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/website/src/components/linter/config.ts
Labels: enhancement, 1 approval

#6873 fix(eslint-plugin): [no-unused-vars] check if any variable definition is exported
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Labels: bug

#6795 fix(eslint-plugin): [no-unnecessary-type-constraint] correctly fix in cts/mts files
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts
Labels: bug, 1 approval

#6724 fix(utils): accept null as default option in `applyDefault`
  packages/utils/src/eslint-utils/deepMerge.ts
  packages/utils/tests/eslint-utils/applyDefault.test.ts
Labels: bug, 1 approval

#7184 chore(website): fix website sidebar version padding issued
  packages/website/docusaurusConfig.ts
  packages/website/src/css/custom.css
Labels: 1 approval

#7225 fix(eslint-plugin): [prefer-nullish-coalescing] handle case when type of left side is null or undefined
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: bug

#7074 fix(eslint-plugin): [no-unsafe-enum-comparison] exempt bit shift operators
  packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Labels: bug

#7122 docs: move header section to main
  packages/website/src/pages/index.tsx
Labels: documentation, awaiting response, package: website

#6864 fix(eslint-plugin): [member-ordering] account for repeated names
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: bug, 1 approval

#7104 docs: add Local Linking guide
  docs/contributing/local-development/Local_Linking.mdx
  packages/website/sidebars/sidebar.base.js
Labels: documentation, 1 approval

#7266 fix(eslint-plugin): use a default export for the rules type
  packages/eslint-plugin/rules.d.ts
Labels: bug

#7267 fix(typescript-estree): fix TSNode type error on old ts versions
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
Labels: bug

#7340 chore: enabled no-else-return internally
  .eslintrc.js
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/key-spacing.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/rules/type-annotation-spacing.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/type-utils/src/predicates.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parseSettings/ExpiringCache.ts
Labels: repo maintenance

#7345 docs: remove unnecessary Examples headings from extension rule docs
  packages/eslint-plugin/docs/rules/block-spacing.md
  packages/eslint-plugin/docs/rules/brace-style.md
  packages/eslint-plugin/docs/rules/class-methods-use-this.md
  packages/eslint-plugin/docs/rules/comma-dangle.md
  packages/eslint-plugin/docs/rules/comma-spacing.md
  packages/eslint-plugin/docs/rules/default-param-last.md
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/docs/rules/func-call-spacing.md
  packages/eslint-plugin/docs/rules/indent.md
  packages/eslint-plugin/docs/rules/init-declarations.md
  packages/eslint-plugin/docs/rules/key-spacing.md
  packages/eslint-plugin/docs/rules/keyword-spacing.md
  packages/eslint-plugin/docs/rules/lines-around-comment.md
  packages/eslint-plugin/docs/rules/lines-between-class-members.md
  packages/eslint-plugin/docs/rules/no-array-constructor.md
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
  packages/eslint-plugin/docs/rules/no-duplicate-type-constituents.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/docs/rules/no-extra-parens.md
  packages/eslint-plugin/docs/rules/no-extra-semi.md
  packages/eslint-plugin/docs/rules/no-invalid-this.md
  packages/eslint-plugin/docs/rules/no-loop-func.md
  packages/eslint-plugin/docs/rules/no-loss-of-precision.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/docs/rules/no-redeclare.md
  packages/eslint-plugin/docs/rules/no-restricted-imports.md
  packages/eslint-plugin/docs/rules/no-shadow.md
  packages/eslint-plugin/docs/rules/no-unused-expressions.md
  packages/eslint-plugin/docs/rules/no-unused-vars.md
  packages/eslint-plugin/docs/rules/no-use-before-define.md
  packages/eslint-plugin/docs/rules/no-useless-constructor.md
  packages/eslint-plugin/docs/rules/object-curly-spacing.md
  packages/eslint-plugin/docs/rules/padding-line-between-statements.md
  packages/eslint-plugin/docs/rules/quotes.md
  packages/eslint-plugin/docs/rules/require-await.md
  packages/eslint-plugin/docs/rules/semi.md
  packages/eslint-plugin/docs/rules/space-before-blocks.md
  packages/eslint-plugin/docs/rules/space-before-function-paren.md
Labels: documentation

#7288 fix(eslint-plugin): [no-inferrable-types] apply also for parameter properties
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
Labels: bug

#7356 docs: mention lack of issue claiming system
  docs/contributing/Issues.mdx
Labels: documentation

#7343 docs: remove duplicated package versions description
  docs/users/Dependency_Versions.mdx
  docs/users/Releases.mdx
  docs/users/Versioning.mdx
Labels: awaiting response

#7334 fix(scope-manager): correct decorators(.length) check in ClassVisitor for methods
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-inner.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-outer.ts.shot
Labels: bug

#7352 docs: mention EXPERIMENTAL_useProjectService in parser package docs
  docs/packages/Parser.mdx
Labels: documentation

#7357 docs: add 'include an emoji' note in contributing guides
  docs/contributing/Issues.mdx
  docs/contributing/Pull_Requests.mdx
Labels: documentation

#7314 docs: include 'Contains' notes in recommended configs docs
  docs/linting/Configurations.mdx
Labels: documentation
