Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-09, with the labels that each got.

#7518 chore(website): reuse svgs from docusaurus
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/inputs/CopyButton.tsx
  packages/website/src/components/inputs/Text.module.css
  packages/website/src/components/inputs/Text.tsx
  packages/website/src/icons/check.svg
  packages/website/src/icons/close.svg
  packages/website/src/icons/copy.svg
  packages/website/src/icons/delete.svg
  packages/website/src/icons/search.svg
Labels: website: playground

#7602 chore(ast-spec): exclude tsx fixtures from type-check
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/fixture.tsx
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/tests/fixtures.test.ts
  packages/ast-spec/tsconfig.json
Labels: repo maintenance

#7606 docs: explain globals in `RuleTester` for Mocha and Vitest
  docs/packages/Rule_Tester.mdx
Labels: documentation

#7557 chore(website): correct schema autocompletion in playground
  packages/website/src/components/lib/jsonSchema.ts
Labels: website: playground

#7560 fix(eslint-plugin): [no-restricted-imports] disallow side effect imports when allowTypeImports is enabled
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
Labels: bug

#7437 feat(eslint-plugin): [await-thenable] added suggestion fixer
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/tests/rules/await-thenable.test.ts
Labels: 1 approval

#7415 docs: added Babel to Dependency Version Upgrades
  docs/maintenance/Dependency_Version_Upgrades.mdx
Labels: documentation, 1 approval

#6843 chore(website): [playground] add types tab to playground
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/types.ts
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/linter/types.ts
  packages/website/src/components/options.ts
  packages/website/src/components/typeDetails/SimplifiedTreeView.tsx
  packages/website/src/components/typeDetails/TypeInfo.tsx
  packages/website/src/components/typeDetails/TypesDetails.tsx
  packages/website/src/components/types.ts
Labels: 1 approval, website: playground

#7612 chore: group jest versions in renovate config
  .github/renovate.json5
Labels: repo maintenance

#7285 docs: improve phrasing around package dist path updates
  packages/website/blog/2023-07-09-announcing-typescript-eslint-v6.md
Labels: awaiting response

#7372 docs(eslint-plugin): add warning about superfluous rules with typescript
  .markdownlint.json
  packages/eslint-plugin/docs/rules/no-dupe-class-members.md
  packages/eslint-plugin/docs/rules/no-invalid-this.md
  packages/eslint-plugin/docs/rules/no-redeclare.md
  packages/website/src/components/TypeScriptOverlap/index.tsx
Labels: 1 approval

#7368 docs: blog post on parserOptions.project = true
  packages/website/blog/2023-09-18-parser-options-project-true.md
Labels: documentation, 1 approval
