Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-10, with the labels that each got.

#7645 chore: add discord and stackoverflow as links to issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: 1 approval, repo maintenance

#7117 feat(eslint-plugin): add new extended rule `prefer-destructuring`
  packages/eslint-plugin/docs/rules/prefer-destructuring.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-destructuring.ts
  packages/eslint-plugin/src/util/getESLintCoreRule.ts
  packages/eslint-plugin/tests/rules/prefer-destructuring.test.ts
  packages/eslint-plugin/tests/schema-snapshots/prefer-destructuring.shot
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval, enhancement: new base rule extension

#6870 fix(type-utils): treat custom type roots as external
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/type-utils/typings/typescript.d.ts
Labels: bug

#7269 feat(eslint-plugin): [naming-convention] add support for default and namespace imports
  packages/eslint-plugin/docs/rules/naming-convention.md
  packages/eslint-plugin/src/rules/naming-convention-utils/enums.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/schema.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention/naming-convention.test.ts
  packages/eslint-plugin/tests/schema-snapshots/naming-convention.shot
Labels: enhancement: plugin rule option, 1 approval

#7754 fix(rule-tester): fix `parser` fallback logic
  packages/rule-tester/src/RuleTester.ts
Labels: bug

#7708 fix(eslint-plugin): [no-unsafe-return] allow returning anything if explicitly returning any
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
Labels: 1 approval

#7440 docs: warn against progressive type enhancement in rules
  docs/developers/Custom_Rules.mdx
Labels: documentation, 1 approval

#7339 chore: enabled most of strict-type-checked internally
  .eslintrc.js
  packages/ast-spec/tests/ast-node-types.type-test.ts
  packages/eslint-plugin/src/rules/default-param-last.ts
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/enums.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/parse-options.ts
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/src/rules/no-namespace.ts
  packages/eslint-plugin/src/rules/no-non-null-asserted-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/no-redeclare.ts
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/src/util/getOperatorPrecedence.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/src/TestFramework.ts
  packages/rule-tester/tests/RuleTester.test.ts
  packages/scope-manager/src/definition/DefinitionBase.ts
  packages/scope-manager/tests/util/getSpecificNode.ts
  packages/scope-manager/tests/util/serializers/DefinitionBase.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/parseSettings/ExpiringCache.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/utils/src/eslint-utils/getParserServices.ts
  packages/utils/src/json-schema.ts
  packages/utils/src/ts-eslint/SourceCode.ts
  packages/website-eslint/src/mock/eslint.js
  packages/website/plugins/generated-rule-docs.ts
  packages/website/src/hooks/useHistorySelector.ts
Labels: 1 approval, repo maintenance

#7691 feat(eslint-plugin): [no-unsafe-enum-comparison] add switch suggestion
  packages/eslint-plugin/src/rules/enum-utils/shared.ts
  packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Labels: 1 approval

#7482 docs(website): add Open in Playground button to code examples
  packages/eslint-plugin/docs/rules/array-type.md
  packages/eslint-plugin/docs/rules/ban-ts-comment.md
  packages/eslint-plugin/docs/rules/class-literal-property-style.md
  packages/eslint-plugin/docs/rules/class-methods-use-this.md
  packages/eslint-plugin/docs/rules/consistent-generic-constructors.md
  packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
  packages/eslint-plugin/docs/rules/consistent-type-definitions.md
  packages/eslint-plugin/docs/rules/consistent-type-exports.md
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
  packages/eslint-plugin/docs/rules/dot-notation.md
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
  packages/eslint-plugin/docs/rules/lines-between-class-members.md
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/docs/rules/method-signature-style.md
  packages/eslint-plugin/docs/rules/no-array-constructor.md
  packages/eslint-plugin/docs/rules/no-base-to-string.md
  packages/eslint-plugin/docs/rules/no-confusing-void-expression.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/docs/rules/no-explicit-any.md
  packages/eslint-plugin/docs/rules/no-extraneous-class.md
  packages/eslint-plugin/docs/rules/no-floating-promises.md
  packages/eslint-plugin/docs/rules/no-inferrable-types.md
  packages/eslint-plugin/docs/rules/no-invalid-void-type.md
  packages/eslint-plugin/docs/rules/no-magic-numbers.md
  packages/eslint-plugin/docs/rules/no-misused-promises.md
  packages/eslint-plugin/docs/rules/no-namespace.md
  packages/eslint-plugin/docs/rules/no-redeclare.md
  packages/eslint-plugin/docs/rules/no-restricted-imports.md
  packages/eslint-plugin/docs/rules/no-shadow.md
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.md
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
  packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md
  packages/eslint-plugin/docs/rules/no-unsafe-argument.md
  packages/eslint-plugin/docs/rules/no-unsafe-assignment.md
  packages/eslint-plugin/docs/rules/no-unsafe-return.md
  packages/eslint-plugin/docs/rules/no-use-before-define.md
  packages/eslint-plugin/docs/rules/parameter-properties.md
  packages/eslint-plugin/docs/rules/prefer-literal-enum-member.md
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
  packages/eslint-plugin/docs/rules/prefer-readonly.md
  packages/eslint-plugin/docs/rules/require-array-sort-compare.md
  packages/eslint-plugin/docs/rules/restrict-plus-operands.md
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/docs/rules/return-await.md
  packages/eslint-plugin/docs/rules/triple-slash-reference.md
  packages/eslint-plugin/docs/rules/type-annotation-spacing.md
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/docs/rules/unbound-method.md
  packages/eslint-plugin/docs/rules/unified-signatures.md
  packages/website/plugins/generated-rule-docs.ts
  packages/website/src/theme/CodeBlock/Content/String.tsx
  packages/website/src/theme/CodeBlock/Content/styles.module.css
  packages/website/src/theme/MDXComponents/TryInPlayground.module.css
  packages/website/src/theme/MDXComponents/TryInPlayground.tsx
Labels: documentation, 1 approval, package: website
