Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-06, with the labels that each got.

#6370 chore: add workflow to automatically run prettier when renovate updates it
  .github/workflows/prettier-update.yml
Labels: awaiting response, repo maintenance

#6781 fix(type-utils): file variant of TypeOrValueSpecifier uses canonical filenames instead of lowercasing
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
  packages/typescript-estree/src/index.ts
Labels: bug, 1 approval

#6723 fix: fix illegal decorator check
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-enum-declaration/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-enum-declaration/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-function/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-function/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-interface-declaration/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-interface-declaration/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-variable/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-variable/snapshots/3-Alignment-Error.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/scope-manager/tests/eslint-scope/references.test.ts
  packages/scope-manager/tests/fixtures/decorators/accessor.ts
  packages/scope-manager/tests/fixtures/decorators/accessor.ts.shot
  packages/scope-manager/tests/fixtures/decorators/parameter.ts
  packages/scope-manager/tests/fixtures/decorators/parameter.ts.shot
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/getModifiers.ts
  packages/typescript-estree/src/node-utils.ts
Labels: package: typescript-estree

#7082 docs: fix broken links v6 docs
  docs/linting/Configurations.mdx
Labels: documentation

#7033 docs: reorganise release/version docs
  docs/Architecture.mdx
  docs/Developers.mdx
  docs/Getting_Started.mdx
  docs/Maintenance.mdx
  docs/Packages.mdx
  docs/Users.mdx
  docs/contributing/Discussions.mdx
  docs/contributing/Local_Development.mdx
  docs/developers/Custom_Rules.mdx
  docs/linting/Configurations.mdx
  docs/linting/Troubleshooting.mdx
  docs/linting/Typed_Linting.mdx
  docs/linting/troubleshooting/Performance.mdx
  docs/linting/troubleshooting/TSLint.mdx
  docs/maintenance/Dependency_Version_Upgrades.mdx
  docs/maintenance/Issues.mdx
  docs/maintenance/Major_Release_Steps.mdx
  docs/maintenance/issues/Rule_Deprecations.mdx
  docs/packages/ESLint_Plugin.mdx
  docs/packages/ESLint_Plugin_TSLint.mdx
  docs/packages/Parser.mdx
  docs/packages/Scope_Manager.mdx
  docs/packages/TypeScript_ESTree.mdx
  docs/packages/Utils.mdx
  docs/users/Dependency_Versions.mdx
  docs/users/Releases.mdx
  docs/users/Versioning.mdx
  netlify.toml
  packages/eslint-plugin-tslint/README.md
  packages/parser/README.md
  packages/scope-manager/README.md
  packages/typescript-estree/README.md
  packages/utils/README.md
  packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
  packages/website/package.json
  packages/website/sidebars/sidebar.base.js
  packages/website/tsconfig.json
Labels: documentation

#7120 feat(typescript-estree): remove parseWithNodeMaps
  docs/architecture/TypeScript_ESTree.mdx
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/parse.test.ts
Labels: breaking change, 1 approval
