Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-02, with the labels that each got.

#6356 feat(eslint-plugin): [no-floating-promises] error on logical expression
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: enhancement, awaiting response, 1 approval

#5885 fix(typescript-estree): wrap import = declaration in an export node
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/entity-name-many/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/entity-name-many/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/entity-name-one/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/entity-name-one/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/external-module-ref-string/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/external-module-ref-string/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/spec.ts
  packages/ast-spec/src/unions/ExportDeclaration.ts
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
  packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
  packages/typescript-estree/tests/snapshots/typescript/basics/import-equal-declaration.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/import-equal-type-declaration.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/import-export-equal-declaration.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/import-export-equal-type-declaration.src.ts.shot
Labels: breaking change

#6096 feat(eslint-plugin): [strict-boolean-expressions] add allow nullable enum to strict boolean expressions
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: enhancement: plugin rule option, awaiting response

#6444 fix(eslint-plugin): [no-import-type-side-effects] correctly ignore zero-specifier imports
  packages/eslint-plugin/src/rules/no-import-type-side-effects.ts
  packages/eslint-plugin/tests/rules/no-import-type-side-effects.test.ts
Labels: bug

#6317 chore(website): link every rule doc to the playground with default config
  packages/website/plugins/generated-rule-docs.ts
  packages/website/src/theme/MDXComponents/TryInPlayground.module.css
  packages/website/src/theme/MDXComponents/TryInPlayground.tsx
  packages/website/src/theme/MDXComponents/index.tsx
Labels: awaiting response

#6443 feat: add `.kind` to `TSModuleDeclaration`
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/namespace/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/namespace/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/global/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/global/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-declare-no-body/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-declare-no-body/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-id-identifier/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-id-identifier/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-id-literal/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-id-literal/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-id-qualified-name/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-id-qualified-name/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-id-identifier/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-id-identifier/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-id-qualified-name/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-id-qualified-name/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/spec.ts
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/directive-in-module/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/directive-in-module/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/directive-in-namespace/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/directive-in-namespace/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/declare/fixtures/module/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/declare/fixtures/module/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/declare/fixtures/namespace/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/declare/fixtures/namespace/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/ambient-module-declaration-with-import/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/ambient-module-declaration-with-import/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/declare-namespace-with-exported-function/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/declare-namespace-with-exported-function/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/global-module-declaration/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/global-module-declaration/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/module-with-default-exports/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/module-with-default-exports/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/nested-internal-module/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/nested-internal-module/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/shorthand-ambient-module-declaration/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/namespaces-and-modules/fixtures/shorthand-ambient-module-declaration/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/snapshots/typescript/basics/directive-in-module.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/basics/directive-in-namespace.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/declare/module.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/declare/namespace.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/ambient-module-declaration-with-import.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/declare-namespace-with-exported-function.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/global-module-declaration.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/module-with-default-exports.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/nested-internal-module.src.ts.shot
  packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/shorthand-ambient-module-declaration.src.ts.shot
Labels: AST

#6105 feat(eslint-plugin): [explicit-function-return-type] add allowFunctionsWithoutTypeParameters option
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: enhancement: plugin rule option

#6412 fix(eslint-plugin): fix key-spacing when type starts on next line
  packages/eslint-plugin/src/rules/key-spacing.ts
  packages/eslint-plugin/tests/rules/key-spacing.test.ts
Labels: bug

#6084 feat(typescript-estree): allow specifying project: true
  docs/architecture/Parser.mdx
  docs/architecture/TypeScript-ESTree.mdx
  docs/linting/Typed_Linting.mdx
  docs/linting/typed-linting/Monorepos.mdx
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/parseSettings/ExpiringCache.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/fixtures/projectTrue/nested/deep/included.ts
  packages/typescript-estree/tests/fixtures/projectTrue/nested/included.ts
  packages/typescript-estree/tests/fixtures/projectTrue/nested/tsconfig.json
  packages/typescript-estree/tests/fixtures/projectTrue/notIncluded.ts
  packages/typescript-estree/tests/lib/createParseSettings.test.ts
  packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
  packages/typescript-estree/tests/lib/parse.project-true.test.ts
  packages/website/src/components/linter/config.ts
Labels: enhancement

#6445 chore: add merge_group trigger to run ci on the merge queue
  .github/workflows/ci.yml
Labels: repo maintenance

#6432 fix(eslint-plugin): [no-unnecessary-condition] account for optional chaining on potentially void values
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#6237 feat(eslint-plugin): [explicit-function-return-type] add allowIIFEs option
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: enhancement: plugin rule option, awaiting response

#6452 fix(eslint-plugin): [no-unnecessary-condition] fix false positive when checking indexed access types
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: bug

#6195 feat(eslint-plugin): [block-spacing] extending base rule for TS related blocks
  packages/eslint-plugin/docs/rules/block-spacing.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/block-spacing.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/util/getESLintCoreRule.ts
  packages/eslint-plugin/tests/rules/block-spacing.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: triage, 1 approval

#6459 feat: bump ts-api-utils to v0.0.21
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/src/rules/no-dynamic-delete.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/no-meaningless-void-operator.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-redundant-type-constituents.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/rules/unbound-method.ts
  packages/type-utils/package.json
  packages/type-utils/src/containsAllTypesByName.ts
  packages/type-utils/src/getContextualType.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/src/isUnsafeAssignment.ts
  packages/type-utils/src/predicates.ts
  packages/type-utils/src/typeFlagUtils.ts
  packages/typescript-estree/package.json
  packages/typescript-estree/src/convert-comments.ts
  yarn.lock
Labels: dependencies

#6468 feat: remove `experimental-utils`
  .github/workflows/semantic-pr-titles.yml
  .vscode/launch.json
  packages/experimental-utils/CHANGELOG.md
  packages/experimental-utils/LICENSE
  packages/experimental-utils/README.md
  packages/experimental-utils/jest.config.js
  packages/experimental-utils/package.json
  packages/experimental-utils/project.json
  packages/experimental-utils/src/index.ts
  packages/experimental-utils/tests/consoleWarning.test.ts
  packages/experimental-utils/tsconfig.build.json
  packages/experimental-utils/tsconfig.json
Labels: breaking change

#6243 fix(ast-spec): remove more invalid properties
  packages/ast-spec/src/base/MethodDefinitionBase.ts
  packages/ast-spec/src/element/TSIndexSignature/spec.ts
  packages/ast-spec/src/element/TSMethodSignature/spec.ts
  packages/ast-spec/src/element/TSPropertySignature/spec.ts
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/class-with-export-parameter-properties/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/class-with-export-parameter-properties/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-index-signature-export/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-index-signature-export/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-method-export/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-method-export/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-property-export/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-property-export/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-property-with-default-value/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/interface-property-with-default-value/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/object-assertion-not-allowed/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/object-assertion-not-allowed/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/object-optional-not-allowed/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/object-optional-not-allowed/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/parameter/TSParameterProperty/spec.ts
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/typescript-estree/src/convert.ts
  packages/visitor-keys/src/visitor-keys.ts
Labels: bug, breaking change, 1 approval

#6470 feat(eslint-plugin): add config that disables type-aware linting
  docs/linting/Configurations.mdx
  docs/linting/Typed_Linting.mdx
  package.json
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
  packages/typescript-estree/src/parseSettings/resolveProjectList.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
Labels: enhancement

#6471 chore: update downlevel-dts config to target TS4.2
  .gitignore
  package.json
  packages/ast-spec/package.json
  packages/parser/package.json
  packages/scope-manager/package.json
  packages/scope-manager/project.json
  packages/type-utils/package.json
  packages/types/package.json
  packages/typescript-estree/package.json
  packages/utils/package.json
  packages/visitor-keys/package.json
  yarn.lock
Labels: repo maintenance

#6472 feat: bump ts-api-utils to v0.0.22
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/type-utils/package.json
  packages/type-utils/src/getContextualType.ts
  packages/typescript-estree/package.json
  yarn.lock
Labels: dependencies

#6460 docs(website): fix typed rules heading link in custom rule docs
  docs/Custom_Rules.mdx
Labels: awaiting response

#6102 feat(eslint-plugin): [no-mixed-enums] add rule
  packages/eslint-plugin/docs/rules/no-mixed-enums.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/strict.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-mixed-enums.ts
  packages/eslint-plugin/tests/rules/no-mixed-enums.test.ts
Labels: enhancement: new plugin rule

#6484 feat(eslint-plugin): [consistent-generic-constructors] handle default parameters
  packages/eslint-plugin/src/rules/consistent-generic-constructors.ts
  packages/eslint-plugin/tests/rules/consistent-generic-constructors.test.ts
Labels: 1 approval

#6476 feat(typescript-estree): expose a wrapper cache clearing function for advanced usecases
  .gitignore
  packages/typescript-estree/src/clear-caches.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/resolveProjectList.ts
Labels: enhancement

#6330 feat(eslint-plugin): [promise-function-async] check for promises in implicit return types
  packages/eslint-plugin/docs/rules/promise-function-async.md
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
  packages/type-utils/src/containsAllTypesByName.ts
Labels: enhancement

#6458 feat: add package.json exports for public packages
  .github/workflows/ci.yml
  package.json
  packages/ast-spec/tests/util/parsers/typescript-estree-import.ts
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin-tslint/tests/tsconfig.json
  packages/eslint-plugin-tslint/tsconfig.build.json
  packages/eslint-plugin/index.d.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/rules.d.ts
  packages/eslint-plugin/src/rules/prefer-ts-expect-error.ts
  packages/eslint-plugin/src/util/astUtils.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/configs.test.ts
  packages/eslint-plugin/tests/fixtures/consistent-type-exports.ts
  packages/eslint-plugin/tests/fixtures/mixed-enums-decl.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.json
  packages/eslint-plugin/tests/rules/consistent-type-exports.test.ts
  packages/eslint-plugin/tests/rules/no-mixed-enums.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
  packages/eslint-plugin/tools/generate-breaking-changes.mts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/eslint-plugin/tsconfig.build.json
  packages/eslint-plugin/tsconfig.json
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/parser/package.json
  packages/parser/tests/lib/parser.ts
  packages/parser/tests/tools/ts-error-serializer.ts
  packages/repo-tools/jest.config.js
  packages/scope-manager/package.json
  packages/type-utils/package.json
  packages/types/package.json
  packages/typescript-estree/package.json
  packages/typescript-estree/src/index.ts
  packages/utils/package.json
  packages/utils/src/eslint-utils/rule-tester/RuleTester.ts
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
  packages/website-eslint/rollup.config.js
  packages/website-eslint/src/linter/linter.js
  packages/website-eslint/types/index.d.ts
  packages/website/plugins/generated-rule-docs.ts
  packages/website/rulesMeta.ts
  packages/website/src/components/editor/config.ts
  packages/website/src/components/editor/loadSandbox.ts
  packages/website/src/components/linter/CompilerHost.ts
  packages/website/src/components/linter/WebLinter.ts
  packages/website/src/components/linter/config.ts
  packages/website/tests/index.spec.ts
  patches/eslint+8.34.0.patch
  patches/ts-api-utils+0.0.21.patch
  tools/dummypkg/README.md
  tools/dummypkg/index.d.ts
  tools/dummypkg/index.js
  tools/dummypkg/package.json
  tsconfig.base.json
  yarn.lock
Labels: breaking change, repo maintenance
