Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-08, with the labels that each got.

#7331 feat(eslint-plugin): [prefer-nullish-coalescing] allow `ignorePrimitives` option to be `true`
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/schema-snapshots/prefer-nullish-coalescing.shot
Labels: enhancement

#7247 chore: run website tests locally on forks in CI
  .github/workflows/ci.yml
Labels: 1 approval

#7289 fix(eslint-plugin): [non-nullable-type-assertion-style] consider operator precedence when fixing
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
Labels: bug

#7394 fix(eslint-plugin): [strict-boolean-expressions] replace dangerous fixer with suggestions
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: awaiting response

#7416 chore: add pr-review-requested.yml workflow
  .github/workflows/pr-review-requested.yml
Labels: repo maintenance

#7410 fix(typescript-estree): support `declare` and `export` modifiers for nested namespace declaration
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-once-declare/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/module-nested-twice-declare/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-declare/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export-declare/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-once-export/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-declare/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export-declare/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/fixture.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSModuleDeclaration/fixtures/namespace-nested-twice-export/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
Labels: bug

#7406 fix(utils): add to JSONSchema4Type missing Array and Object
  packages/utils/src/json-schema.ts
Labels: bug, awaiting response

#7391 docs: add note on common misconceptions about type narrowing
  .cspell.json
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
Labels: 1 approval

#7474 fix(utils): [ts-eslint] small type fixes
  packages/utils/src/ts-eslint/ESLint.ts
Labels: bug

#6162 chore: upgrade to yarn 3
  .github/actions/prepare-install/action.yml
  .github/workflows/nx-migrate.yml
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  docs/contributing/Local_Development.mdx
  netlify.toml
  nx.json
  package.json
  packages/ast-spec/package.json
  packages/eslint-plugin-internal/package.json
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin/package.json
  packages/integration-tests/project.json
  packages/integration-tests/tools/integration-test-base.ts
  packages/parser/package.json
  packages/repo-tools/package.json
  packages/repo-tools/project.json
  packages/repo-tools/src/postinstall.mts
  packages/rule-schema-to-typescript-types/package.json
  packages/rule-schema-to-typescript-types/project.json
  packages/scope-manager/package.json
  packages/type-utils/package.json
  packages/types/package.json
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-estree/package.json
  packages/utils/package.json
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
  packages/website-eslint/project.json
  packages/website/package.json
  yarn.lock
Labels: 1 approval, repo maintenance

#7479 feat: support Explicit Resource Management syntax for TS 5.2
  .prettierignore
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/declare-with-using/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/declare-with-using/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/declare-with-using/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/declare-with-using/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-value-in-using/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-value-in-using/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-value-in-using/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-value-in-using/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/object-binding-patterns-in-using/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/object-binding-patterns-in-using/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/object-binding-patterns-in-using/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/object-binding-patterns-in-using/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-multiple-declarations/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/await-using-with-value/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-multiple-declarations/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/using-with-value/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/VariableDeclaration/spec.ts
  packages/ast-spec/src/special/VariableDeclarator/spec.ts
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/fixture.ts
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/statement/ForOfStatement/fixtures/using-decralation/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/statement/ForOfStatement/spec.ts
  packages/ast-spec/src/unions/ForInitialiser.ts
  packages/ast-spec/src/unions/ForOfInitialiser.ts
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/ast-spec/tests/util/parsers/babel.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
Labels: enhancement

#7535 feat: bump supported TS version to 5.2
  package.json
  packages/scope-manager/tools/generate-lib.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/website/src/vendor/sandbox.d.ts
  packages/website/src/vendor/typescript-vfs.d.ts
  yarn.lock
Labels: dependencies, New TypeScript Version

#7330 docs: add info for no-extra-semi
  packages/eslint-plugin/docs/rules/no-extra-semi.md
Labels: documentation

#6885 fix(eslint-plugin): [consistent-type-assertions] wrap object return value with parentheses
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/src/util/getOperatorPrecedence.ts
  packages/eslint-plugin/src/util/getWrappedCode.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
  packages/eslint-plugin/tests/util/getWrappedCode.test.ts
  packages/eslint-plugin/tests/util/getWrappingFixer.test.ts
Labels: bug, 1 approval
