Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-11, with the labels that each got.

#7854 fix(eslint-plugin): [no-unused-vars] handle logical assignment
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Labels: 1 approval

#7553 fix(eslint-plugin): [explicit-function-return-type] support JSX attributes in `allowTypedFunctionExpressions`
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Labels: bug

#7739 feat(typescript-estree): skip `isTTY` version check if user passes `loggerFn` on unsupported TypeScript version warning
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/tests/lib/warn-on-unsupported-ts.test.ts
Labels: 1 approval

#7883 fix(eslint-plugin): [no-unnecessary-qualifier] handle nested namespace id
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-qualifier.test.ts
Labels: bug

#7878 chore: replace nohoist configuration with hoisting limits
  package.json
Labels: repo maintenance

#7835 chore(typescript-estree): fixed no-unnecessary-condition complaints
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/getModifiers.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parseSettings/inferSingleRun.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/typescript-estree/tools/test-utils.ts
Labels: 1 approval, repo maintenance

#7846 chore: add a11y-alt-text-check bot
  .github/workflows/a11y-alt-bot.yml
Labels: repo maintenance

#7273 feat: add types for flat config files
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin/index.d.ts
  packages/eslint-plugin/tools/generate-configs.ts
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/src/types/RuleTesterConfig.ts
  packages/rule-tester/src/types/ValidTestCase.ts
  packages/rule-tester/src/utils/validationHelpers.ts
  packages/scope-manager/src/ScopeManager.ts
  packages/scope-manager/src/analyze.ts
  packages/types/src/parser-options.ts
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/ESLint.ts
  packages/utils/src/ts-eslint/Linter.ts
  packages/utils/src/ts-eslint/Parser.ts
  packages/utils/src/ts-eslint/Processor.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/utils/src/ts-eslint/SourceCode.ts
  packages/utils/src/ts-eslint/index.ts
  packages/website/src/components/linter/config.ts
  packages/website/src/components/linter/createLinter.ts
  packages/website/src/components/linter/createParser.ts
  packages/website/src/components/linter/types.ts
Labels: enhancement, 1 approval

#7390 feat: add `no-unsafe-unary-minus` rule
  packages/eslint-plugin/docs/rules/no-unsafe-unary-minus.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-unary-minus.ts
  packages/eslint-plugin/tests/rules/no-unsafe-unary-minus.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unsafe-unary-minus.shot
Labels: enhancement: new plugin rule, awaiting response

#7551 feat(utils): add ESLint `CodePath` selector types
  packages/eslint-plugin/typings/eslint-rules.d.ts
  packages/utils/src/ts-eslint/Rule.ts
Labels: enhancement, 1 approval

#7898 feat(eslint-plugin): no-unsafe-enum-comparison handles switch cases
  packages/eslint-plugin/docs/rules/no-unsafe-enum-comparison.md
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Labels: 1 approval

#7834 chore: fix miscellaneous no-unnecessary-condition violations
  packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
  packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts
  packages/eslint-plugin-tslint/src/rules/config.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/rule-schema-to-typescript-types/src/generateArrayType.ts
  packages/rule-tester/src/utils/config-validator.ts
  packages/rule-tester/src/utils/getRuleOptionsSchema.ts
  packages/rule-tester/src/utils/interpolate.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/src/referencer/PatternVisitor.ts
  packages/scope-manager/src/referencer/TypeVisitor.ts
  packages/scope-manager/src/scope/GlobalScope.ts
  packages/scope-manager/src/scope/ScopeBase.ts
  packages/scope-manager/tests/types/reference-type.test.ts
  packages/type-utils/src/getContextualType.ts
  packages/type-utils/src/getSourceFileOfNode.ts
  packages/type-utils/src/getTypeArguments.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/src/predicates.ts
Labels: 1 approval, repo maintenance

#7672 chore(website): [playground] improve mobile design
  .yarn/patches/react-split-pane-npm-0.1.92-93dbf51dff.patch
  packages/website/package.json
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/SplitPane/ConditionalSplitPane.tsx
  packages/website/src/components/SplitPane/SplitPane.module.css
  packages/website/src/components/typeDetails/TypesDetails.tsx
  patches/typescript+5.2.1-rc.patch
  yarn.lock
Labels: 1 approval, website: playground

#7933 fix(utils): add missing fields to flat config types
  .cspell.json
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/Linter.ts
Labels: bug

#7885 chore: shorten issue template naming
  .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
  .github/ISSUE_TEMPLATE/02-enhancement-rule-option.yaml
  .github/ISSUE_TEMPLATE/03-enhancement-new-rule.yaml
  .github/ISSUE_TEMPLATE/04-enhancement-new-base-rule-extension.yaml
  .github/ISSUE_TEMPLATE/05-documentation-request.yml
  .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
  .github/ISSUE_TEMPLATE/08-bug-report-complex.yaml
  .github/ISSUE_TEMPLATE/09-config-change.yaml
  .github/ISSUE_TEMPLATE/10-repo-maintenance.yaml
Labels: awaiting response, 1 approval, repo maintenance

#7806 fix(eslint-plugin): [switch-exhaustiveness-check] enum members with new line or single quotes are not being fixed correctly
  packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
Labels: bug, 1 approval

#7705 fix(eslint-plugin): [class-methods-use-this] detect a problematic case for private/protected members if `ignoreClassesThatImplementAnInterface` is set
  packages/eslint-plugin/docs/rules/class-methods-use-this.md
  packages/eslint-plugin/src/rules/class-methods-use-this.ts
  packages/eslint-plugin/tests/rules/class-methods-use-this/class-methods-use-this.test.ts
  packages/eslint-plugin/tests/schema-snapshots/class-methods-use-this.shot
Labels: 1 approval

#7695 chore: add windows ci
  .github/workflows/ci.yml
  packages/rule-tester/tests/RuleTester.test.ts
  packages/typescript-estree/tests/lib/describeFilePath.test.ts
Labels: stale

#7923 feat: update TypeScript to 5.3-rc
  .yarn/patches/typescript-npm-5.3.1-rc-6c4278ffd3.patch
  .yarn/patches/typescript-npm-5.4.0-dev.20231117-78a04a34c5.patch
  docs/maintenance/Dependency_Version_Upgrades.mdx
  package.json
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  yarn.lock
Labels: 1 approval, dependencies

#7880 feat(eslint-plugin): [switch-exhaustiveness-check] add requireDefaultForNonUnion option
  packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
  packages/eslint-plugin/tests/schema-snapshots/switch-exhaustiveness-check.shot
Labels: enhancement: plugin rule option, 1 approval

#7967 fix(typescript-estree): ensure backwards compat with pre-5.3 import attributes
  packages/typescript-estree/src/convert.ts
Labels: bug

#7968 feat: support TS 5.3
  .yarn/patches/typescript-npm-5.3.1-rc-6c4278ffd3.patch
  .yarn/patches/typescript-npm-5.4.0-dev.20231117-78a04a34c5.patch
  docs/maintenance/Dependency_Version_Upgrades.mdx
  docs/users/Dependency_Versions.mdx
  package.json
  packages/repo-tools/src/generate-lib.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
  packages/typescript-estree/tsconfig.build.json
  packages/typescript-estree/typings/typescript.d.ts
  yarn.lock
Labels: dependencies, New TypeScript Version

#7997 feat(typescript-estree): pass jsDocParsingMode everywhere
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
Labels: enhancement

#7999 fix: default to parse all JSDoc and provide options to configure it
  docs/packages/Parser.mdx
  docs/packages/TypeScript_ESTree.mdx
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/createIsolatedProgram.ts
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/src/create-program/createSourceFile.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/website-eslint/build.ts
  packages/website/src/components/linter/config.ts
Labels: bug

#7836 chore(website): fixed most no-unnecessary-condition complaints
  packages/website/plugins/generated-rule-docs.ts
  packages/website/src/components/ErrorsViewer.tsx
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/ast/DataRenderer.tsx
  packages/website/src/components/ast/tsUtils.ts
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/lib/jsonSchema.ts
  packages/website/src/components/lib/markdown.ts
  packages/website/src/components/typeDetails/TypeInfo.tsx
  packages/website/src/theme/CodeBlock/Content/String.tsx
Labels: 1 approval, repo maintenance
