Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-01, with the labels that each got.

#5704 fix(eslint-plugin): [ban-ts-comment] counts graphemes instead of `String.prototype.length`
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
  yarn.lock
Labels: awaiting response

#6211 feat(eslint-plugin): add `key-spacing` rule extension for interface & type declarations
  packages/eslint-plugin/docs/rules/key-spacing.md
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/key-spacing.ts
  packages/eslint-plugin/src/util/getESLintCoreRule.ts
  packages/eslint-plugin/src/util/getStringLength.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/tests/rules/key-spacing.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval

#6375 chore(typescript-estree): remove unnecessary this.inTypeMode field
  packages/typescript-estree/src/convert.ts
Labels: repo maintenance

#6365 test: verify that there are no errors on the website
  packages/website/tests/index.spec.ts
Labels: awaiting response

#5919 fix(eslint-plugin): [prefer-optional-chain] fixer produces wrong logic
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/base-cases.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
Labels: bug, awaiting response

#6209 docs(eslint-plugin): update site description of ban-types docs
  packages/eslint-plugin/docs/rules/ban-types.md
Labels: documentation

#6223 docs(eslint-plugin): corrected eslint-plugin README.md getting started link
  packages/eslint-plugin/README.md
Labels: documentation

#6236 docs: explained tsconfigRootDir in website
  docs/architecture/Parser.mdx
  docs/linting/Typed_Linting.md
Labels: documentation

#6249 docs: added Contributing > Discussions page
  .cspell.json
  docs/contributing/Discussions.md
  docs/maintenance/ISSUES.md
  packages/website/sidebars/sidebar.base.js
Labels: documentation

#6254 docs(website): added maintenance docs for rule feature requests
  docs/maintenance/ISSUES.md
Labels: documentation

#6327 chore(website): add links to and widen Silver Supporters
  packages/website/src/components/FinancialContributors/Sponsor.tsx
  packages/website/src/components/FinancialContributors/Sponsors/index.tsx
  packages/website/src/components/FinancialContributors/Sponsors/styles.module.css
  packages/website/src/components/FinancialContributors/index.tsx
  packages/website/src/components/FinancialContributors/styles.module.css
  packages/website/src/components/FinancialContributors/types.ts
Labels: repo maintenance

#6313 chore(website): mention 3 months SLA for issue and PR questions
  docs/contributing/Issues.mdx
  docs/contributing/Pull_Requests.mdx
Labels: repo maintenance

#6321 fix(ast-spec): a JSXEmptyExpression is not a possible JSXExpression
  packages/ast-spec/src/unions/JSXExpression.ts
Labels: bug

#6251 docs: describe update steps for ESLint, Node, and TypeScript
  docs/maintenance/Versioning.md
  docs/maintenance/versioning/dependant-version-upgrades.mdx
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/website/sidebars/sidebar.base.js
Labels: documentation, 1 approval

#6242 chore(typescript-estree): remove visitor-keys backwards compat export
  packages/parser/package.json
  packages/parser/src/parser.ts
  packages/typescript-estree/src/index.ts
Labels: breaking change, repo maintenance

#6311 chore(website): reorganized sidebar and header nav a bit
  docs/maintenance/ISSUES.md
  packages/website/docusaurusConfig.ts
  packages/website/sidebars/sidebar.base.js
Labels: 1 approval, repo maintenance

#6028 fix(eslint-plugin): [prefer-optional-chain] fix `ThisExpression` and `PrivateIdentifier` errors
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
Labels: bug

#6325 chore(website): consistent .mdx file naming
  .cspell.json
  .github/pull_request_template.md
  docs/Architecture.mdx
  docs/Custom_Rules.mdx
  docs/Getting_Started.mdx
  docs/Maintenance.mdx
  docs/architecture/ESLint_Plugin.mdx
  docs/architecture/ESLint_Plugin_TSLint.mdx
  docs/linting/CONFIGURATIONS.mdx
  docs/linting/Troubleshooting.mdx
  docs/linting/Typed_Linting.mdx
  docs/linting/troubleshooting/Formatting.mdx
  docs/linting/troubleshooting/Performance.md
  docs/linting/troubleshooting/TSLint.mdx
  docs/linting/typed-linting/Monorepos.mdx
  docs/maintenance/Branding.mdx
  docs/maintenance/Issues.mdx
  docs/maintenance/Pull_Requests.mdx
  docs/maintenance/Releases.mdx
  docs/maintenance/Versioning.mdx
  docs/maintenance/issues/Rule_Deprecations.mdx
  docs/maintenance/versioning/dependant-version-upgrades.mdx
  packages/experimental-utils/README.md
Labels: 1 approval, repo maintenance

#6228 chore: enable eqeqeq internally
  .eslintrc.js
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/src/rules/ban-types.ts
  packages/eslint-plugin/src/rules/comma-spacing.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/src/rules/no-loss-of-precision.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-non-null-asserted-nullish-coalescing.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/rules/prefer-function-type.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/rules/triple-slash-reference.ts
  packages/eslint-plugin/src/util/isNullLiteral.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
  packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
  packages/scope-manager/src/ScopeManager.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/src/referencer/PatternVisitor.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/typescript-estree/src/convert-comments.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/getModifiers.ts
  packages/typescript-estree/src/simple-traverse.ts
  packages/typescript-estree/tools/test-utils.ts
  packages/utils/src/eslint-utils/applyDefault.ts
  packages/utils/src/eslint-utils/nullThrows.ts
  packages/utils/tests/eslint-utils/nullThrows.test.ts
  packages/website/src/components/ast/serializer/serializer.ts
Labels: 1 approval, repo maintenance

#6384 fix(eslint-plugin): [sort-type-constituents] fixed behavior change
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/sort-type-constituents.test.ts
Labels: bug

#6376 feat(eslint-plugin): [naming-convention] improve performance by removing unnecessary selectors
  packages/eslint-plugin/src/rules/naming-convention-utils/types.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
Labels: performance

#6367 feat(typescript-estree): cache project glob resolution
  .cspell.json
  .eslintrc.js
  .gitignore
  docs/architecture/Parser.mdx
  docs/architecture/TypeScript-ESTree.mdx
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parseSettings/ExpiringCache.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parseSettings/resolveProjectList.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  yarn.lock
Labels: performance
