Repository typescript-eslint/typescript-eslint, pull requests merged in 2023-03, with the labels that each got.

#6536 chore(website): add mastodon link and icons to footer
  packages/website/docusaurusConfig.ts
  packages/website/src/css/custom.css
  packages/website/static/img/bug-report.svg
  packages/website/static/img/github-dark.svg
  packages/website/static/img/github.svg
  packages/website/static/img/mastodon.svg
  packages/website/static/img/stack-overflow.svg
  packages/website/static/img/twitter.svg
Labels: package: website

#6529 chore(website): add new action to playground to fix all eslint errors
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/createProvideCodeActions.ts
  packages/website/src/components/linter/WebLinter.ts
Labels: package: website, website: playground

#6516 chore(website): correct issues with scrollbars in playground
  packages/website/src/components/ErrorsViewer.module.css
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/ast/ASTViewer.module.css
Labels: package: website, website: playground

#6238 docs(website): blog post on consistent-type-(exports|imports)
  packages/eslint-plugin/docs/rules/consistent-type-exports.md
  packages/eslint-plugin/docs/rules/consistent-type-imports.md
  packages/website/blog/2023-02-24-consistent-type-exports-and-imports-why-and-how.md
Labels: documentation

#6553 docs(eslint-plugin): [no-empty-interface] correct typo in example
  packages/eslint-plugin/docs/rules/no-empty-interface.md
Labels: documentation

#6247 feat(typescript-estree): added allowInvalidAST option to not throw on invalid tokens
  docs/architecture/TypeScript-ESTree.mdx
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/export-missing-name/fixture.ts
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/export-missing-name/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/export-missing-name/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/export-missing-name/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/anonymous-class/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/ExportNamedDeclaration/fixtures/_error_/anonymous-class/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/_error_/decorator/fixture.ts
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/_error_/decorator/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/decorator/fixture.ts
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/decorator/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/decorator/fixture.ts
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/decorator/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/decorator/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/decorator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/decorator/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/decorator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-id-without-value/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-id-without-value/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/no-variables/fixture.ts
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/no-variables/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/no-variables/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/no-variables/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-enum-declaration/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-enum-declaration/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-interface-declaration/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-interface-declaration/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-variable/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-variable/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/solo-const/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/solo-const/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/statement/ThrowStatement/fixtures/_error_/missing-argument/fixture.ts
  packages/ast-spec/src/statement/ThrowStatement/fixtures/_error_/missing-argument/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/statement/ThrowStatement/fixtures/_error_/missing-argument/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/statement/ThrowStatement/fixtures/_error_/missing-argument/snapshots/3-Alignment-Error.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/ast-spec/tests/util/parsers/typescript-estree.ts
  packages/ast-spec/typings/global.d.ts
  packages/eslint-plugin/tests/rules/indent/indent.test.ts
  packages/parser/tests/lib/parser.ts
  packages/typescript-estree/src/ast-converter.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tests/lib/semantic-diagnostics-enabled.test.ts
  packages/website/src/components/linter/config.ts
Labels: breaking change

#6609 feat: remove moduleResolver API
  docs/architecture/Parser.mdx
  docs/architecture/TypeScript-ESTree.mdx
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/create-program/createDefaultProgram.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/src/parseSettings/index.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/parse.moduleResolver.default-program-error.test.ts
  packages/typescript-estree/tests/lib/parse.moduleResolver.default-program-success.test.ts
  packages/typescript-estree/tests/lib/parse.moduleResolver.placeholder-error.test.ts
  packages/typescript-estree/tests/lib/parse.moduleResolver.placeholder-success.test.ts
  packages/typescript-estree/tools/test-utils.ts
  packages/website/src/components/linter/config.ts
Labels: breaking change

#6594 feat(eslint-plugin): [no-unnecessary-cond] check logical assignments
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: enhancement

#6604 docs(eslint-plugin): [prefer-function-type] mention global augmentation edge case in docs
  packages/eslint-plugin/docs/rules/prefer-function-type.md
Labels: documentation

#6580 docs: fix typo in tslint docs
  docs/linting/troubleshooting/TSLint.mdx
Labels: documentation

#6524 chore(website): add ESQuery visualizer to playground
  packages/website-eslint/package.json
  packages/website-eslint/rollup.config.js
  packages/website-eslint/src/linter/linter.js
  packages/website-eslint/types/index.d.ts
  packages/website/package.json
  packages/website/src/components/ASTViewerESTree.tsx
  packages/website/src/components/ESQueryFilter.module.css
  packages/website/src/components/ESQueryFilter.tsx
  packages/website/src/components/ErrorsViewer.module.css
  packages/website/src/components/ErrorsViewer.tsx
  packages/website/src/components/OptionsSelector.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/config/ConfigEditor.module.css
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/editor/loadSandbox.ts
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/hooks/useFocus.ts
  packages/website/src/components/inputs/Text.module.css
  packages/website/src/components/inputs/Text.tsx
  packages/website/src/globals.d.ts
  yarn.lock
Labels: 1 approval, package: website, website: playground

#6569 fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] fixer should handle parentheses
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
Labels: bug, 1 approval

#6596 chore(website): insert generated content in the right position
  packages/website/plugins/generated-rule-docs.ts
Labels: 1 approval

#6597 fix(eslint-plugin): [no-confusing-void-expression] check sequence expressions for void is in last position
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/tests/rules/no-confusing-void-expression.test.ts
Labels: bug

#5327 feat(eslint-plugin): [lines-around-comment] add extension rule
  packages/eslint-plugin/docs/rules/lines-around-comment.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/lines-around-comment.ts
  packages/eslint-plugin/src/util/getESLintCoreRule.ts
  packages/eslint-plugin/tests/rules/lines-around-comment.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval, enhancement: new base rule extension, formatting

#6193 fix(eslint-plugin): [no-misused-promises] avoid unnecessary calls to getContextualType
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: awaiting response

#6616 chore: automatically cleanup caches when the relevant PR closes
  .github/workflows/cleanup-cache.yml
Labels: repo maintenance

#6639 docs(eslint-plugin): [await-thenable] fix typo
  packages/eslint-plugin/docs/rules/await-thenable.md
Labels: documentation

#6638 fix(eslint-plugin): [no-misused-promises] fix incorrect detection of void functions in JSX attributes
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: bug

#6613 feat(typescript-estree): throw errors when abstract property has initializer
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-accessor-with-value/fixture.ts
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-accessor-with-value/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-accessor-with-value/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-accessor-with-value/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-property-with-value/fixture.ts
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-property-with-value/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-property-with-value/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/modifier-abstract-property-with-value/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/modifier-abstract-with-value/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/modifier-abstract-with-value/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/modifier-abstract-with-value/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/modifier-abstract-with-value/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/modifier-abstract-with-value/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/element/AccessorProperty/fixtures/modifier-abstract-with-value/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/abstract-class-with-override-property/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/abstract-class-with-override-property/snapshots/3-Alignment-Error.shot
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/eslint-plugin/tests/rules/naming-convention/cases/property.test.ts
  packages/typescript-estree/src/convert.ts
Labels: enhancement

#6618 fix(eslint-plugin): [strict-boolean-expressions] handle truthy enums
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: bug

#6619 fix(eslint-plugin): [member-ordering] check order when optionalityOrder is present with no optional members
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-optionalMembers.test.ts
Labels: bug

#6645 fix(eslint-plugin): add TSPropertySignature with TSFunctionType annotation to typeMethod selector
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/method.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/naming-convention.test.ts
Labels: bug

#6662 chore: update to TypeScript 5.0.2
  package.json
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/config.ts
  packages/website/src/components/editor/useSandboxServices.ts
  patches/typescript+5.0.2.patch
  yarn.lock
Labels: dependencies

#6670 fix(typescript-estree): allow writing to deprecated node properties
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/tests/lib/convert.test.ts
Labels: bug

#4436 feat(eslint-plugin): [prefer-readonly-parameter-types] added an optional type allowlist
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
  packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/type-utils/package.json
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/type-utils/src/index.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
  yarn.lock
Labels: enhancement: plugin rule option, breaking change, 1 approval

#6672 fix(eslint-plugin): [strict-boolean-expression] support falsy and truthy literals simultaneously
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: bug

#6620 fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] simplify fixer and add support for double negation
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
Labels: bug

#6641 feat(eslint-plugin): [consistent-type-assertions] autofix angle bracket assertions to as
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Labels: enhancement, awaiting response

#6727 chore(website): migrate from lzstring.ts to lz-string package
  packages/website/package.json
  packages/website/plugins/generated-rule-docs.ts
  packages/website/src/components/hooks/useHashState.ts
  yarn.lock
Labels: website: playground

#5728 feat(eslint-plugin): add `no-duplicate-type-constituents` rule
  packages/eslint-plugin/docs/rules/no-duplicate-type-constituents.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts
  packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts
Labels: enhancement: new plugin rule, awaiting response

#6767 fix(eslint-plugin): correct crashes with getTypeArguments for ts < 3.7
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/src/rules/require-array-sort-compare.ts
  packages/type-utils/src/isTypeReadonly.ts
Labels: bug, package: eslint-plugin

#6768 chore(website): [playground] regression fix for parsing comments
  packages/website/src/components/linter/WebLinter.ts
Labels: website: playground

#6735 chore(website): [playground] add tabs to ast viewer and update design
  packages/website/src/components/ESQueryFilter.module.css
  packages/website/src/components/EditorTabs.tsx
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/Playground.module.css
  packages/website/src/components/Playground.tsx
  packages/website/src/components/config.ts
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/layout/EditorTabs.module.css
  packages/website/src/components/layout/EditorTabs.tsx
  packages/website/src/components/layout/Modal.module.css
  packages/website/src/components/layout/Modal.tsx
Labels: website: playground

#6738 chore(website): [playground] improve design of error viewer
  packages/website/src/components/ErrorsViewer.module.css
  packages/website/src/components/ErrorsViewer.tsx
  packages/website/src/components/layout/AlertBlock.tsx
Labels: website: playground

#6736 chore(website): [playground] update options selector
  packages/website/src/components/OptionsSelector.module.css
  packages/website/src/components/OptionsSelector.tsx
  packages/website/src/components/config/ConfigEditor.module.css
  packages/website/src/components/config/ConfigEditor.tsx
  packages/website/src/components/inputs/Dropdown.module.css
  packages/website/src/components/inputs/Dropdown.tsx
  packages/website/src/components/inputs/Text.module.css
  packages/website/src/components/inputs/Text.tsx
  packages/website/src/components/layout/ActionLabel.tsx
  packages/website/src/components/layout/InputLabel.module.css
  packages/website/src/components/layout/InputLabel.tsx
  packages/website/src/hooks/useClipboard.ts
  packages/website/src/hooks/useDebouncedToggle.ts
  packages/website/src/icons/copy.svg
Labels: website: playground

#6771 docs: update troubleshooting to include typescript project references not being supported yet
  docs/linting/Troubleshooting.mdx
Labels: awaiting response

#6779 chore(website): add stylelint and fix css issues
  packages/website/.stylelintrc.json
  packages/website/package.json
  packages/website/src/components/ESQueryFilter.module.css
  packages/website/src/components/Playground.module.css
  packages/website/src/components/RulesTable/styles.module.css
  packages/website/src/components/SplitPane/SplitPane.module.css
  packages/website/src/components/config/ConfigEditor.module.css
  packages/website/src/components/inputs/Tooltip.module.css
  packages/website/src/components/layout/Expander.module.css
  packages/website/src/components/layout/Loader.module.css
  packages/website/src/css/custom.css
  packages/website/src/css/prism.css
  packages/website/src/pages/styles.module.css
  packages/website/src/theme/CodeBlock/Content/styles.module.css
  packages/website/src/theme/MDXComponents/Feature.module.css
  yarn.lock
Labels: repo maintenance, package: website

#6716 chore(website): update build script to use esbuild instead of rollup
  .github/renovate.json5
  packages/scope-manager/package.json
  packages/typescript-estree/package.json
  packages/typescript-estree/src/use-at-your-own-risk.ts
  packages/visitor-keys/package.json
  packages/website-eslint/build.ts
  packages/website-eslint/package.json
  packages/website-eslint/rollup-plugin/replace.js
  packages/website-eslint/rollup.config.js
  packages/website-eslint/src/index.js
  packages/website-eslint/src/linter/linter.js
  packages/website-eslint/src/mock/empty.js
  packages/website-eslint/src/mock/eslint-rules.js
  packages/website-eslint/src/mock/eslint.js
  packages/website-eslint/src/mock/globby.js
  packages/website-eslint/src/mock/is-glob.js
  packages/website-eslint/src/mock/lru-cache.js
  packages/website-eslint/src/mock/semver.js
  packages/website-eslint/src/mock/util.js
  packages/website-eslint/tsconfig.json
  packages/website/src/components/linter/WebLinter.ts
  packages/website/src/components/linter/config.ts
  yarn.lock
Labels: website: playground

#6802 feat(typescript-estree): forbid members in Mapped Type
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/fixture.ts
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/fixture.ts
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/snapshots/3-Alignment-Error.shot
  packages/typescript-estree/src/convert.ts
Labels: enhancement
