Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-12, with the labels that each got.

#10304 fix(eslint-plugin): [promise-function-async] handle function overloading
  packages/eslint-plugin/src/rules/promise-function-async.ts
  packages/eslint-plugin/tests/rules/promise-function-async.test.ts
Labels: bug, 1 approval

#10374 fix(eslint-plugin): [no-deprecated] check if a JSX attribute is deprecated
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#10218 feat(eslint-plugin): [switch-exhaustiveness-check] add support for "no default" comment
  packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.mdx
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/switch-exhaustiveness-check.shot
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
  packages/eslint-plugin/tests/schema-snapshots/switch-exhaustiveness-check.shot
Labels: 1 approval

#10432 fix(eslint-plugin): [no-base-to-string] handle more robustly when multiple `toString()` declarations are present for a type
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: 1 approval

#10436 fix(eslint-plugin): [use-unknown-in-catch-callback-variable] only flag function literals
  packages/eslint-plugin/src/rules/use-unknown-in-catch-callback-variable.ts
  packages/eslint-plugin/tests/rules/use-unknown-in-catch-callback-variable.test.ts
Labels: 1 approval

#10419 chore: enforce repo nullish check style
  eslint.config.mjs
  packages/ast-spec/tests/util/serializers/Node.ts
  packages/eslint-plugin-internal/src/rules/eqeq-nullish.ts
  packages/eslint-plugin-internal/src/rules/index.ts
  packages/eslint-plugin-internal/tests/rules/eqeq-nullish.test.ts
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/parse-options.ts
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/src/rules/no-duplicate-enum-values.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-mixed-enums.ts
  packages/eslint-plugin/src/rules/no-restricted-types.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/src/rules/prefer-destructuring.ts
  packages/eslint-plugin/src/rules/prefer-function-type.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/eslint-plugin/src/util/getStaticStringValue.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
  packages/parser/src/parser.ts
  packages/rule-schema-to-typescript-types/src/generateObjectType.ts
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/src/utils/flat-config-schema.ts
  packages/rule-tester/src/utils/serialization.ts
  packages/scope-manager/src/analyze.ts
  packages/scope-manager/tests/test-utils/serializers/baseSerializer.ts
  packages/type-utils/src/containsAllTypesByName.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInFile.ts
  packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/getParsedConfigFile.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/typescript-estree/tests/test-utils/test-utils.ts
  packages/utils/src/eslint-utils/applyDefault.ts
  packages/website/plugins/generated-rule-docs/insertions/insertRuleOptions.ts
  packages/website/src/components/RulesTable/index.tsx
  packages/website/src/components/TypeScriptOverlap/index.tsx
  packages/website/src/components/ast/utils.ts
  tools/release/release.mts
Labels: repo maintenance

#10460 fix(eslint-plugin): handle string like index type
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#10472 fix(eslint-plugin): use consistent naming for asserting types and casting values
  packages/eslint-plugin/docs/rules/explicit-function-return-type.mdx
  packages/eslint-plugin/docs/rules/explicit-module-boundary-types.mdx
  packages/eslint-plugin/docs/rules/non-nullable-type-assertion-style.mdx
  packages/eslint-plugin/docs/rules/prefer-reduce-type-parameter.mdx
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
  packages/eslint-plugin/src/rules/no-unsafe-type-assertion.ts
  packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
  packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/explicit-function-return-type.shot
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/explicit-module-boundary-types.shot
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-reduce-type-parameter.shot
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/strict-boolean-expressions.shot
Labels: 1 approval

#10475 fix(scope-manager): visit params decorator before nest scope
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/tests/fixtures/decorators/parameter-property.ts.shot
  packages/scope-manager/tests/fixtures/decorators/parameter.ts
  packages/scope-manager/tests/fixtures/decorators/parameter.ts.shot
Labels: 1 approval

#10513 fix(typescript-eslint): export types so that declarations can be named for dts files
  packages/typescript-eslint/src/config-helper.ts
  packages/typescript-eslint/src/index.ts
Labels: bug, 1 approval

#10510 docs: switch playground to new CDN
  packages/website/src/components/editor/loadSandbox.ts
Labels: 1 approval

#10498 fix(eslint-plugin): [no-deprecated] not reporting usages of deprecated declared constants as object value
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#10494 fix(eslint-plugin): [prefer-reduce-type-parameter] don't report cases in which the fix results in a type error
  packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
  packages/eslint-plugin/tests/rules/prefer-reduce-type-parameter.test.ts
Labels: 1 approval

#10473 fix(eslint-plugin): [no-unnecessary-condition] don't flag values of an unconstrained or valid type parameter
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#10503 fix(eslint-plugin): [no-unnecessary-type-arguments] handle type/value context
  packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
Labels: 1 approval

#10512 fix(eslint-plugin): [consistent-type-assertions] allow default assertionStyle option
  packages/eslint-plugin/src/rules/consistent-type-assertions.ts
  packages/eslint-plugin/tests/schema-snapshots/consistent-type-assertions.shot
Labels: 1 approval

#10514 fix(eslint-plugin): [no-unnecessary-condition] handle noUncheckedIndexedAccess true
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#10106 feat(eslint-plugin): [strict-boolean-expressions] check array predicate functions' return statements
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/strict-boolean-expressions.shot
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: 1 approval

#10496 fix(eslint-plugin): add getConstraintInfo to handle generic constraints better
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/util/getConstraintInfo.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/needsToBeAwaited.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
  packages/eslint-plugin/tests/util/getConstraintInfo.test.ts
  packages/type-utils/src/getConstrainedTypeAtLocation.ts
  packages/type-utils/tests/getConstrainedTypeAtLocation.test.ts
Labels: 1 approval

#10522 fix(eslint-plugin): [array-type] autofix with conditional types needs parentheses
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: 1 approval

#10437 fix(eslint-plugin): [no-base-to-string] check array generic type
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: 1 approval

#10543 fix(eslint-plugin): [no-shadow] report correctly on parameters of functions declared with the `declare` keyword
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
Labels: 1 approval

#10574 docs: [prefer-nullish-coalescing] fix admonition
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
Labels: 1 approval

#10567 chore: upgrade to ts-api-utils 2.0
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/type-utils/package.json
  packages/type-utils/src/builtinSymbolLikes.ts
  packages/typescript-estree/package.json
  yarn.lock
Labels: 1 approval

#10548 fix(eslint-plugin): [strict-boolean-expressions] remove remaining (unsafe) autofixes
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: 1 approval
