Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-11, with the labels that each got.

#10250 feat(eslint-plugin): disable `no-class-assign` rule in `eslint-recommended` config
  packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
Labels: 1 approval

#10246 docs: enable `respectPrefersColorScheme`
  packages/website/docusaurus.config.mts
Labels: 1 approval

#9924 feat(eslint-plugin): [prefer-nullish-coalescing] add option `ignoreBooleanCoercion`
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-nullish-coalescing.shot
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/schema-snapshots/prefer-nullish-coalescing.shot
Labels: 1 approval

#10258 fix(types): parent property type annotation in the ImportAttribute node
  packages/types/src/ts-estree.ts
Labels: bug

#10261 fix(eslint-plugin): [no-deprecated] report on deprecated variables used inside dynamic imports
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#10259 fix(eslint-plugin): [no-deprecated] report when exported class implements/extends deprecated entity
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#10255 feat: add `options` property to `ImportExpression` node
  packages/ast-spec/src/expression/ImportExpression/spec.ts
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/dynamic-import-with-import-assertions/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/dynamic-import-with-import-assertions/snapshots/5-AST-Alignment-AST.shot
  packages/typescript-estree/src/convert.ts
  packages/visitor-keys/src/visitor-keys.ts
Labels: 1 approval

#10235 fix(eslint-plugin): [consistent-type-definitions] don't leave trailing parens when fixing type to interface
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
Labels: 1 approval

#10172 chore(website): account for `thanks.dev` donors in sponsors list
  knip.ts
  packages/website/data/sponsors.json
  packages/website/src/components/FinancialContributors/Sponsor.tsx
  packages/website/src/components/FinancialContributors/types.ts
  tools/scripts/generate-sponsors.mts
Labels: 1 approval

#10221 feat(eslint-plugin): [only-throw-error] add allow option
  docs/packages/type-utils/TypeOrValueSpecifier.mdx
  packages/eslint-plugin/docs/rules/only-throw-error.mdx
  packages/eslint-plugin/src/rules/only-throw-error.ts
  packages/eslint-plugin/tests/fixtures/errors.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.json
  packages/eslint-plugin/tests/rules/only-throw-error.test.ts
  packages/eslint-plugin/tests/schema-snapshots/only-throw-error.shot
Labels: 1 approval

#10232 fix(eslint-plugin): [switch-exhaustiveness-check] add support for covering a missing property with `undefined`
  packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
Labels: 1 approval

#10209 feat(eslint-plugin): [await-thenable] report unnecessary `await using` statements
  packages/eslint-plugin/docs/rules/await-thenable.mdx
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/util/getFixOrSuggest.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/await-thenable.shot
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/await-thenable.test.ts
Labels: awaiting response

#10216 fix(eslint-plugin): [no-misused-promises] improve report loc for methods
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: 1 approval

#10271 fix(scope-manager): fix asserted increments not being marked as write references
  packages/eslint-plugin/tests/eslint-rules/prefer-const.test.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/type-assertion/increment/angle-bracket-increment.ts
  packages/scope-manager/tests/fixtures/type-assertion/increment/angle-bracket-increment.ts.shot
  packages/scope-manager/tests/fixtures/type-assertion/increment/as-increment.ts
  packages/scope-manager/tests/fixtures/type-assertion/increment/as-increment.ts.shot
  packages/scope-manager/tests/fixtures/type-assertion/increment/non-null-increment.ts
  packages/scope-manager/tests/fixtures/type-assertion/increment/non-null-increment.ts.shot
Labels: 1 approval

#10192 feat(eslint-plugin): added related-getter-setter-pairs rule
  packages/eslint-plugin/docs/rules/related-getter-setter-pairs.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/configs/strict-type-checked-only.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/related-getter-setter-pairs.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/related-getter-setter-pairs.shot
  packages/eslint-plugin/tests/rules/related-getter-setter-pairs.test.ts
  packages/eslint-plugin/tests/schema-snapshots/related-getter-setter-pairs.shot
  packages/typescript-eslint/src/configs/all.ts
  packages/typescript-eslint/src/configs/disable-type-checked.ts
  packages/typescript-eslint/src/configs/strict-type-checked-only.ts
  packages/typescript-eslint/src/configs/strict-type-checked.ts
Labels: 1 approval

#10328 test: fix jest plugin usage in integration test
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/eslint.config.js
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/eslint.config.js
  packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v8.test.ts.snap
  packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v9.test.ts.snap
Labels: 1 approval

#10301 fix(eslint-plugin): [consistent-indexed-object-style] handle circular mapped types
  packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
  packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Labels: 1 approval

#10296 docs: include Bluesky profile in social links
  .cspell.json
  docs/contributing/Issues.mdx
  packages/website/docusaurus.config.mts
  packages/website/src/css/custom.css
  packages/website/static/img/bluesky.svg
Labels: 1 approval

#10051 feat(eslint-plugin): new rule `no-unsafe-type-assertion`
  packages/eslint-plugin/docs/rules/no-unsafe-type-assertion.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-type-assertion.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-type-assertion.shot
  packages/eslint-plugin/tests/rules/no-unsafe-type-assertion.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unsafe-type-assertion.shot
  packages/typescript-eslint/src/configs/all.ts
  packages/typescript-eslint/src/configs/disable-type-checked.ts
Labels: 1 approval

#9744 fix: add missing peer dependencies
  packages/type-utils/package.json
  packages/typescript-eslint/package.json
  packages/utils/package.json
  yarn.lock
Labels: 1 approval

#10333 feat(typescript-eslint): allow infinitely deep array nesting in config function and extends
  docs/getting-started/Quickstart.mdx
  docs/getting-started/Typed_Linting.mdx
  docs/packages/TypeScript_ESLint.mdx
  docs/troubleshooting/faqs/General.mdx
  docs/troubleshooting/typed-linting/Monorepos.mdx
  docs/troubleshooting/typed-linting/Performance.mdx
  docs/users/Shared_Configurations.mdx
  docs/users/What_About_Formatting.mdx
  eslint.config.mjs
  package.json
  packages/rule-schema-to-typescript-types/package.json
  packages/typescript-eslint/src/config-helper.ts
  packages/typescript-eslint/tests/config-helper.test.ts
  packages/typescript-eslint/tests/configs.test.ts
  typings/eslint-plugin-eslint-plugin.d.ts
  typings/eslint-plugin-jsx-a11y.d.ts
  typings/eslint-plugin-react.d.ts
  yarn.lock
Labels: enhancement, 1 approval

#10299 feat(eslint-plugin): [prefer-nullish-coalescing] fix detection of `ignoreConditionalTests` involving boolean `!` operator
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: bug, 1 approval

#10314 fix(eslint-plugin): [await-thenable, return-await] don't flag awaiting unconstrained type parameter as unnecessary
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/needsToBeAwaited.ts
  packages/eslint-plugin/tests/rules/await-thenable.test.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug

#10315 fix(eslint-plugin): [explicit-module-boundary-types] and [explicit-function-return-type] don't report on `as const satisfies`
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: bug, 1 approval

#10330 fix(eslint-plugin): report deprecations used in default export
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#10339 fix(utils): add defaultOptions to meta in rule
  packages/eslint-plugin/src/rules/consistent-return.ts
  packages/eslint-plugin/src/rules/dot-notation.ts
  packages/eslint-plugin/src/rules/init-declarations.ts
  packages/eslint-plugin/src/rules/max-params.ts
  packages/eslint-plugin/src/rules/no-dupe-class-members.ts
  packages/eslint-plugin/src/rules/no-empty-function.ts
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/src/rules/no-loop-func.ts
  packages/eslint-plugin/src/rules/no-loss-of-precision.ts
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/eslint-plugin/src/rules/prefer-destructuring.ts
  packages/utils/src/eslint-utils/RuleCreator.ts
  packages/utils/src/ts-eslint/Rule.ts
Labels: bug

#10349 docs: remove `@types/eslint__js` from quickstart step
  docs/getting-started/Quickstart.mdx
Labels: 1 approval

#10354 chore: bump eslint dependencies
  eslint.config.mjs
  package.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/tests/schema-snapshots/consistent-return.shot
  packages/eslint-plugin/tests/schema-snapshots/no-invalid-this.shot
  packages/eslint-plugin/tests/schema-snapshots/no-unused-expressions.shot
  packages/rule-tester/package.json
  packages/rule-tester/src/TestFramework.ts
  packages/typescript-estree/src/node-utils.ts
  packages/utils/src/ts-eslint/Linter.ts
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
  packages/website/package.json
  yarn.lock
Labels: repo maintenance

#10341 chore: update contributors
  CONTRIBUTORS.md
  tools/scripts/generate-contributors.mts
Labels: repo maintenance

#10312 feat(eslint-plugin): [max-params] add function overload and function type support
  packages/eslint-plugin/src/rules/max-params.ts
  packages/eslint-plugin/tests/rules/max-params.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval

#10287 feat(eslint-plugin): [no-base-to-string] check Array.prototype.join
  packages/eslint-plugin/docs/rules/no-base-to-string.mdx
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-base-to-string.shot
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: 1 approval

#10385 fix(typescript-estree): update conditions for unsupported version warning
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
Labels: 1 approval

#10386 test(typescript-estree): add test to ensure TS version range matches root version
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/tests/lib/tsVersionRangeSync.test.ts
Labels: tests

#10363 fix(eslint-plugin): [no-unnecessary-template-expressions] allow template expressions used to make trailing whitespace visible
  packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
  packages/eslint-plugin/tests/rules/no-useless-constructor.test.ts
Labels: 1 approval

#10401 fix(eslint-plugin): remove references to "extendDefaults" in no-restricted-types
  packages/eslint-plugin/docs/rules/no-restricted-types.mdx
  packages/eslint-plugin/src/rules/no-restricted-types.ts
Labels: 1 approval

#10428 docs: return-await doc page should say the rule is in the strict-type-checked ruleset, not recommended
  packages/website/src/theme/MDXComponents/RuleAttributes.tsx
Labels: 1 approval
