Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-03, with the labels that each got.

#8490 chore(website): include file extension to "Open in Playground" URLs
  packages/website/src/theme/CodeBlock/Content/String.tsx
  packages/website/src/theme/MDXComponents/TryInPlayground.tsx
Labels: 1 approval

#8263 fix(eslint-plugin): [member-ordering] report alphabetical sorting for all groups instead of just the first failing group
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-case-insensitive-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-natural-case-insensitive-order.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-natural-order.test.ts
Labels: 1 approval

#8575 fix(eslint-plugin): [no-useless-template-literals] detect TemplateLiteral
  packages/eslint-plugin/src/rules/no-useless-template-literals.ts
  packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
Labels: 1 approval

#8622 fix(typescript-eslint): set `sourceType: "module"` in base shared config
  eslint.config.mjs
  packages/typescript-eslint/src/configs/base.ts
Labels: bug

#8621 fix(typescript-eslint): export `ConfigWithExtends` type
  packages/typescript-eslint/src/config-helper.ts
  packages/typescript-eslint/src/index.ts
Labels: bug

#8634 docs(website): icons not being visible in dark mode
  packages/website/src/components/team/TeamBio.module.css
  packages/website/src/components/team/TeamBio.tsx
  packages/website/src/css/custom.css
  packages/website/static/img/www.svg
Labels: package: website

#8421 fix(eslint-plugin): [prefer-find] support ternary branches in prefer-find
  packages/eslint-plugin/src/rules/prefer-find.ts
  packages/eslint-plugin/tests/rules/prefer-find.test.ts
Labels: 1 approval

#8658 docs: [prefer-optional-chain] fix boolean option being specified incorrectly
  packages/eslint-plugin/docs/rules/prefer-optional-chain.md
Labels: documentation

#8308 fix(eslint-plugin): [consistent-type-imports] handle imports without specifiers
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
Labels: 1 approval

#8389 feat(eslint-plugin): [restrict-template-expressions] add `allowArray` option
  packages/eslint-plugin/docs/rules/restrict-template-expressions.md
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
  packages/eslint-plugin/tests/schema-snapshots/restrict-template-expressions.shot
Labels: 1 approval

#8671 fix: correct `engines.node` constraints in `package.json`
  packages/ast-spec/package.json
  packages/eslint-plugin/package.json
  packages/parser/package.json
  packages/rule-schema-to-typescript-types/package.json
  packages/rule-tester/package.json
  packages/scope-manager/package.json
  packages/type-utils/package.json
  packages/types/package.json
  packages/typescript-eslint/package.json
  packages/typescript-estree/package.json
  packages/utils/package.json
  packages/visitor-keys/package.json
  packages/website-eslint/package.json
Labels: bug

#8484 feat(utils): add parser name to thrown parser error message
  packages/utils/src/eslint-utils/getParserServices.ts
  packages/utils/tests/eslint-utils/getParserServices.test.ts
Labels: 1 approval

#8282 fix(eslint-plugin): [no-redundant-type-constituents] incorrectly marks & string as redundant
  packages/eslint-plugin/src/rules/no-redundant-type-constituents.ts
  packages/eslint-plugin/tests/rules/no-redundant-type-constituents.test.ts
Labels: bug

#8411 feat(typescript-estree): disallow switch statements with multiple default cases
  packages/ast-spec/src/statement/SwitchStatement/fixtures/_error_/multiple-default-cases/fixture.ts
  packages/ast-spec/src/statement/SwitchStatement/fixtures/_error_/multiple-default-cases/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/statement/SwitchStatement/fixtures/_error_/multiple-default-cases/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/statement/SwitchStatement/fixtures/_error_/multiple-default-cases/snapshots/3-Alignment-Error.shot
  packages/typescript-estree/src/convert.ts
Labels: 1 approval

#8364 feat(eslint-plugin): add meta.docs.recommended setting for strict config options
  packages/eslint-plugin/src/configs/strict-type-checked-only.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/configs/strict.ts
  packages/eslint-plugin/src/rules/ban-ts-comment.ts
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/restrict-plus-operands.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/configs.test.ts
  packages/repo-tools/src/generate-configs.mts
  packages/repo-tools/src/postinstall.mts
  packages/rule-tester/src/utils/config-validator.ts
  packages/typescript-eslint/src/configs/strict-type-checked-only.ts
  packages/typescript-eslint/src/configs/strict-type-checked.ts
  packages/typescript-eslint/src/configs/strict.ts
  packages/typescript-eslint/tests/configs.test.ts
  packages/utils/src/eslint-utils/RuleCreator.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/website/plugins/generated-rule-docs/utils.ts
  packages/website/src/components/RulesTable/index.tsx
  packages/website/src/hooks/useClipboard.ts
  packages/website/src/theme/MDXComponents/RuleAttributes.tsx
Labels: 1 approval

#8383 feat(eslint-plugin): add rule `use-unknown-in-catch-callback-variables`
  packages/eslint-plugin/docs/rules/use-unknown-in-catch-callback-variable.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/configs/strict-type-checked-only.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/src/rules/use-unknown-in-catch-callback-variable.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/use-unknown-in-catch-callback-variable.test.ts
  packages/eslint-plugin/tests/schema-snapshots/use-unknown-in-catch-callback-variable.shot
  packages/eslint-plugin/tools/generate-breaking-changes.mts
  packages/repo-tools/src/generate-configs.mts
  packages/repo-tools/src/generate-contributors.mts
  packages/repo-tools/src/generate-lib.mts
  packages/repo-tools/src/generate-sponsors.mts
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-eslint/src/configs/all.ts
  packages/typescript-eslint/src/configs/disable-type-checked.ts
  packages/typescript-eslint/src/configs/strict-type-checked-only.ts
  packages/typescript-eslint/src/configs/strict-type-checked.ts
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/tools/generate-website-dts.ts
Labels: enhancement: new plugin rule, 1 approval

#8591 fix(eslint-plugin): [no-unnecessary-qualifier] handle merge namespace with enum
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-qualifier.test.ts
Labels: 1 approval

#8668 fix(eslint-plugin): [no-unused-expressions] false negatives when using assertions
  packages/eslint-plugin/src/rules/no-unused-expressions.ts
  packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
Labels: 1 approval

#8508 fix(eslint-plugin): [explicit-function-return-type, explicit-module-boundary-types] improved checking for allowHigherOrderFunctions option
  packages/eslint-plugin/src/rules/explicit-function-return-type.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
  packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Labels: 1 approval

#8412 fix(eslint-plugin): [class-literal-property-style] ignore property assigned in constructor
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/prefer-for-of.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/isAssignee.ts
  packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
Labels: 1 approval

#8558 fix(eslint-plugin): [no-unnecessary-type-assertion] fix false negative for const variable declarations
  packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.mdx
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-array-constructor.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/typescript-estree/tests/lib/persistentParse.test.ts
Labels: 1 approval

#8725 chore(website): fix broken deprecated warning
  packages/website/plugins/generated-rule-docs/insertions/insertFormattingNotice.ts
  packages/website/src/theme/MDXComponents/index.tsx
Labels: package: website

#8738 fix(typescript-eslint): declare peer dependency on `utils` to ensure npm correctly installs dependencies
  packages/typescript-eslint/package.json
  yarn.lock
Labels: bug

#8736 fix(website): fix infinite rendering when hash changed
  packages/website/src/pages/play.tsx
Labels: website: playground

#8750 fix(website): make 404 page good again
  packages/website/src/theme/NotFound/Content/index.tsx
  packages/website/src/theme/NotFound/Content/styles.module.css
  packages/website/src/theme/NotFound/index.tsx
Labels: awaiting response

#8734 docs: restrict-template-expressions - remove mention of numbers being allowed
  packages/eslint-plugin/docs/rules/restrict-template-expressions.mdx
Labels: documentation

#8335 feat(eslint-plugin): [consistent-type-imports] ignore files with decorators, experimentalDecorators, and emitDecoratorMetadata
  docs/packages/Parser.mdx
  packages/eslint-plugin/docs/rules/consistent-type-imports.mdx
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
  packages/parser/src/parser.ts
  packages/rule-tester/package.json
  packages/scope-manager/src/ScopeManager.ts
  packages/scope-manager/src/analyze.ts
  packages/scope-manager/src/referencer/ClassVisitor.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/eslint-scope/references.test.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/accessor-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/accessor-deco.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-deco.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-return-generic.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/method-return-generic.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-both.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-both.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-inner.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-inner.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-outer.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-outer.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/parameters-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/parameters-deco.ts.shot
  packages/scope-manager/tests/fixtures/class/emit-metadata/property-deco.ts
  packages/scope-manager/tests/fixtures/class/emit-metadata/property-deco.ts.shot
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/createParserServices.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  packages/website/blog/2024-03-25-changes-to-consistent-type-imports-with-decorators.md
  packages/website/src/components/linter/createParser.ts
  yarn.lock
Labels: enhancement

#8758 fix(eslint-plugin): [no-floating-promises] handle TaggedTemplateExpression
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: 1 approval
