Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-06, with the labels that each got.

#9026 feat(rule-tester): port `checkDuplicateTestCases` from ESLint
  packages/eslint-plugin/tests/dedupeTestCases.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
  packages/eslint-plugin/tests/rules/func-call-spacing.test.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/createTestCases.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/rule-tester/package.json
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/src/utils/serialization.ts
  packages/rule-tester/tests/eslint-base/eslint-base.test.js
  yarn.lock
Labels: enhancement, 1 approval

#9196 docs: add example with PascalCase function components
  packages/eslint-plugin/docs/rules/naming-convention.mdx
Labels: 1 approval

#9197 docs: explicitly mention unbound-method limitation with thisArg
  packages/eslint-plugin/docs/rules/unbound-method.mdx
Labels: 1 approval

#9195 docs: improve description for no-dynamic-delete
  packages/eslint-plugin/docs/rules/no-dynamic-delete.mdx
Labels: 1 approval

#9198 docs: mention related ESLint rules in no-unused-vars page
  packages/eslint-plugin/docs/rules/no-unused-vars.mdx
Labels: 1 approval

#9041 docs(website): reduce Contributor_Tiers page's table vertical Padding
  docs/maintenance/Contributor_Tiers.mdx
  packages/website/src/css/custom.css
Labels: documentation, awaiting response

#8686 chore(website): simplify playground logic
  packages/website/src/components/Playground.tsx
Labels: website: playground

#9186 feat(eslint-plugin): [no-floating-promises] add option 'allowForKnownSafePromises'
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.mdx
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-floating-promises.shot
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Labels: 1 approval

#9200 docs: clarify what require-await does
  packages/eslint-plugin/docs/rules/require-await.mdx
  packages/eslint-plugin/src/rules/require-await.ts
Labels: 1 approval

#9226 feat(typescript-estree): require `import = require()` argument to be a string literal
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/fixture.ts
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/fixture.ts
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/special/TSExternalModuleReference/spec.ts
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/tests/rules/no-require-imports.test.ts
  packages/typescript-estree/src/convert.ts
Labels: AST

#9225 feat(typescript-estree): forbid `.body`, `.async`, `.generator` on `declare function`
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/async/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/async/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/declare-with-body/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/declare-with-body/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-ambient/fixture.ts
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-ambient/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-ambient/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-ambient/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-overload/fixture.ts
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-overload/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-overload/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator-overload/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator/fixture.ts
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/generator/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/fixture.ts
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-ambient/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/fixture.ts
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/async-overload/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/generator/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/generator/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/generator/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/generator/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/generator/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/spec.ts
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/eslint-plugin/tests/rules/consistent-return.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/naming-convention.test.ts
  packages/typescript-estree/src/convert.ts
Labels: AST

#9231 fix(ast-spec): function-call-like callee should be Expression not LeftHandSideExpression
  packages/ast-spec/src/base/UnaryExpressionBase.ts
  packages/ast-spec/src/expression/CallExpression/spec.ts
  packages/ast-spec/src/expression/ClassExpression/spec.ts
  packages/ast-spec/src/expression/NewExpression/spec.ts
  packages/ast-spec/src/expression/TaggedTemplateExpression/spec.ts
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
Labels: AST

#9238 docs: auto-generate support h2 below all blog posts
  packages/website/blog/2022-09-18-automated-rule-docs-with-docusaurus-and-remark.md
  packages/website/blog/2023-02-24-consistent-type-exports-and-imports-why-and-how.md
  packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
  packages/website/blog/2023-07-09-announcing-typescript-eslint-v6.md
  packages/website/blog/2023-09-18-parser-options-project-true.md
  packages/website/blog/2023-12-25-deprecating-formatting-rules.md
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
  packages/website/docusaurus.config.mts
  packages/website/plugins/blog-footer.ts
  packages/website/plugins/generated-rule-docs/RuleDocsPage.ts
  packages/website/plugins/generated-rule-docs/addESLintHashToCodeBlocksMeta.ts
  packages/website/plugins/generated-rule-docs/createRuleDocsPage.ts
  packages/website/plugins/generated-rule-docs/index.ts
  packages/website/plugins/generated-rule-docs/insertions/insertBaseRuleReferences.ts
  packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
  packages/website/plugins/generated-rule-docs/insertions/insertResources.ts
  packages/website/plugins/generated-rule-docs/insertions/insertSpecialCaseOptions.ts
  packages/website/plugins/generated-rule-docs/insertions/insertWhenNotToUseIt.ts
  packages/website/plugins/utils/nodes.ts
  packages/website/plugins/utils/rules.ts
Labels: documentation, 1 approval

#9207 feat(eslint-plugin): remove no-useless-template-literals
  packages/eslint-plugin/docs/rules/no-unnecessary-template-expression.mdx
  packages/eslint-plugin/docs/rules/no-useless-template-literals.mdx
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-useless-template-literals.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-useless-template-literals.shot
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-useless-template-literals.shot
  packages/typescript-eslint/src/configs/disable-type-checked.ts
Labels: 1 approval

#8893 fix(eslint-plugin): [init-declarations] refine report locations
  packages/eslint-plugin/src/rules/init-declarations.ts
  packages/eslint-plugin/tests/rules/init-declarations.test.ts
Labels: enhancement, 1 approval

#9239 test(eslint-plugin): add docs test for Correct and Incorrect blocks
  packages/eslint-plugin/tests/docs.test.ts
Labels: tests, 1 approval

#9249 docs: note the stylistic configs as sticking around past formatting rules
  docs/troubleshooting/Formatting.mdx
  packages/website/blog/2023-12-25-deprecating-formatting-rules.md
Labels: 1 approval

#9251 docs(eslint-plugin): [no-misused-promises] replace third-party EventEmitter example with native document
  packages/eslint-plugin/docs/rules/no-misused-promises.mdx
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-misused-promises.shot
Labels: 1 approval

#9256 docs: correct tsconfig.eslint.json link to be permalink
  docs/troubleshooting/FAQ.mdx
Labels: 1 approval

#9260 docs(eslint-plugin): [prefer-readonly-parameter-types] mention limitations
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.mdx
Labels: 1 approval

#9257 docs: mention non-semver guarantees in Shared Configs docs
  docs/users/Shared_Configurations.mdx
Labels: 1 approval

#9274 docs: mention TSEnumBody breaking change in v8 beta post
  docs/maintenance/Releases.mdx
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
Labels: 1 approval

#9271 chore(website): align file names to RuleTester requirements
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/linter/bridge.ts
  packages/website/src/components/linter/createLinter.ts
  packages/website/src/components/linter/createParser.ts
  packages/website/src/components/linter/utils.ts
Labels: 1 approval

#9246 docs: mention testing changes and keeping PRs up-to-date in PR docs
  docs/contributing/Local_Development.mdx
  docs/contributing/Pull_Requests.mdx
Labels: 1 approval

#8304 fix(eslint-plugin): [no-unsafe-assignment] be more specific about error types
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-assignment.shot
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
Labels: 1 approval

#9253 docs(eslint-plugin): [sort-type-constituents] deprecate the rule
  packages/eslint-plugin/docs/rules/sort-type-constituents.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/sort-type-constituents.ts
  packages/typescript-eslint/src/configs/all.ts
Labels: 1 approval

#9233 feat(parser, typescript-estree): export withoutProjectParserOptions utility
  docs/packages/Parser.mdx
  packages/parser/src/index.ts
  packages/typescript-estree/src/index.ts
  packages/typescript-estree/src/withoutProjectParserOptions.ts
  packages/typescript-estree/tests/lib/withoutProjectParserOptions.test.ts
Labels: 1 approval

#9167 fix(eslint-plugin): [no-magic-numbers] fix implementation of the `ignore` option
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
  packages/eslint-plugin/typings/eslint-rules.d.ts
Labels: 1 approval

#9258 docs: mention rule scripts under Local Development
  docs/contributing/Local_Development.mdx
  package.json
  packages/eslint-plugin/package.json
Labels: 1 approval

#9261 chore: enable eslint-plugin/no-property-in-node internally
  .yarn/patches/eslint-plugin-eslint-plugin-npm-5.5.1-4206c2506d.patch
  eslint.config.mjs
  package.json
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/default-param-last.ts
  packages/eslint-plugin/src/rules/indent.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/src/rules/no-inferrable-types.ts
  packages/eslint-plugin/src/rules/no-misused-new.ts
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/src/rules/prefer-as-const.ts
  packages/eslint-plugin/src/rules/prefer-destructuring.ts
  yarn.lock
Labels: 1 approval

#9234 feat(eslint-plugin): [no-floating-promises] add 'allowForKnownSafeCalls' option
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-floating-promises.shot
Labels: 1 approval

#9287 feat(typescript-estree): also remove projectService in withoutProjectParserOptions
  packages/typescript-estree/src/withoutProjectParserOptions.ts
  packages/typescript-estree/tests/lib/withoutProjectParserOptions.test.ts
Labels: 1 approval

#9280 feat(eslint-plugin): [no-dynamic-delete] allow all string literals as index
  packages/eslint-plugin/docs/rules/no-dynamic-delete.mdx
  packages/eslint-plugin/src/rules/no-dynamic-delete.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-dynamic-delete.shot
  packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
Labels: 1 approval

#9318 fix(types): allow ProjectServiceOptions for projectService
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/parser-options.ts
Labels: 1 approval

#9102 feat(eslint-plugin): replace ban-types with no-restricted-types, no-unsafe-function-type, no-wrapper-object-types
  docs/maintenance/Issues.mdx
  packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md
  packages/eslint-plugin/docs/rules/ban-types.md
  packages/eslint-plugin/docs/rules/ban-types.mdx
  packages/eslint-plugin/docs/rules/no-restricted-types.mdx
  packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
  packages/eslint-plugin/docs/rules/no-wrapper-object-types.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/recommended-type-checked.ts
  packages/eslint-plugin/src/configs/recommended.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/configs/strict.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-implied-eval.ts
  packages/eslint-plugin/src/rules/no-restricted-types.ts
  packages/eslint-plugin/src/rules/no-unsafe-function-type.ts
  packages/eslint-plugin/src/rules/no-wrapper-object-types.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/scopeUtils.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/ban-types.shot
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-function-type.shot
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-wrapper-object-types.shot
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/ban-types.test.ts
  packages/eslint-plugin/tests/rules/no-restricted-types.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-function-type.test.ts
  packages/eslint-plugin/tests/rules/no-wrapper-object-types.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-restricted-types.shot
  packages/eslint-plugin/tests/schema-snapshots/no-unsafe-function-type.shot
  packages/eslint-plugin/tests/schema-snapshots/no-wrapper-object-types.shot
  packages/scope-manager/tests/test-utils/serializers/baseSerializer.ts
  packages/typescript-eslint/src/configs/all.ts
  packages/typescript-eslint/src/configs/recommended-type-checked.ts
  packages/typescript-eslint/src/configs/recommended.ts
  packages/typescript-eslint/src/configs/strict-type-checked.ts
  packages/typescript-eslint/src/configs/strict.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
  packages/website/plugins/generated-rule-docs/index.ts
  packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
  packages/website/plugins/generated-rule-docs/insertions/insertSpecialCaseOptions.ts
Labels: breaking change

#9044 fix(eslint-plugin): [return-await] support explicit resource management
  packages/eslint-plugin/docs/rules/return-await.mdx
  packages/eslint-plugin/src/rules/return-await.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/return-await.shot
  packages/eslint-plugin/tests/rules/return-await.test.ts
Labels: bug, 1 approval

#9255 test(type-utils): add tests for getTypeName
  packages/type-utils/tests/getTypeName.test.ts
Labels: 1 approval

#9365 docs: update main with v8 blog post changes
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
Labels: 1 approval

#9294 docs: add minimal docs page for type-utils package
  docs/packages/Type_Utils.mdx
  packages/type-utils/src/builtinSymbolLikes.ts
  packages/website/sidebars/sidebar.base.js
Labels: 1 approval

#9367 fix(eslint-plugin): [no-extraneous-class] handle abstract members
  packages/eslint-plugin/docs/rules/no-extraneous-class.mdx
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-extraneous-class.shot
  packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
Labels: bug

#9336 fix(typescript-estree): only run projectService setHostConfiguration when needed
  .cspell.json
  docs/packages/Parser.mdx
  docs/packages/TypeScript_ESTree.mdx
  docs/troubleshooting/FAQ.mdx
  docs/troubleshooting/Performance.mdx
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Labels: 1 approval

#9211 feat(ast-spec): tighter types and documentation for declaration/*
  packages/ast-spec/src/base/FunctionBase.ts
  packages/ast-spec/src/declaration/ClassDeclaration/spec.ts
  packages/ast-spec/src/declaration/ExportAllDeclaration/spec.ts
  packages/ast-spec/src/declaration/ExportDefaultDeclaration/spec.ts
  packages/ast-spec/src/declaration/ExportNamedDeclaration/spec.ts
  packages/ast-spec/src/declaration/FunctionDeclaration/spec.ts
  packages/ast-spec/src/declaration/ImportDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSImportEqualsDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSModuleDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSNamespaceExportDeclaration/spec.ts
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/spec.ts
  packages/ast-spec/src/unions/DeclarationStatement.ts
  packages/eslint-plugin/src/rules/consistent-type-definitions.ts
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/typescript-estree/src/convert.ts
Labels: awaiting response, 1 approval

#9378 fix(eslint-plugin): [prefer-nullish-coalescing] handle intersected primitive types
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Labels: 1 approval

#9411 fix(eslint-plugin): [no-invalid-this] support AccessorProperty
  packages/eslint-plugin/src/rules/no-invalid-this.ts
  packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
  packages/utils/src/ts-eslint/Rule.ts
Labels: bug, 1 approval

#9024 docs: split troubleshooting into granular sections
  .github/replies.yml
  docs/getting-started/Legacy_ESLint_Setup.mdx
  docs/getting-started/Quickstart.mdx
  docs/getting-started/Typed_Linting.mdx
  docs/maintenance/Issues.mdx
  docs/packages/ESLint_Plugin_TSLint.mdx
  docs/troubleshooting/FAQ.mdx
  docs/troubleshooting/faqs/ESLint.mdx
  docs/troubleshooting/faqs/Frameworks.mdx
  docs/troubleshooting/faqs/General.mdx
  docs/troubleshooting/faqs/JavaScript.mdx
  docs/troubleshooting/faqs/TypeScript.mdx
  docs/troubleshooting/typed-linting/Monorepos.mdx
  docs/troubleshooting/typed-linting/Performance.mdx
  docs/troubleshooting/typed-linting/index.mdx
  docs/users/Shared_Configurations.mdx
  docs/users/What_About_Formatting.mdx
  docs/users/What_About_TSLint.mdx
  docs/users/index.mdx
  netlify.toml
  packages/eslint-plugin/docs/rules/README.md
  packages/eslint-plugin/docs/rules/no-extra-semi.mdx
  packages/eslint-plugin/docs/rules/no-type-alias.mdx
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/validateDefaultProjectForFilesGlob.ts
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
  packages/website/blog/2023-09-18-parser-options-project-true.md
  packages/website/blog/2023-12-25-deprecating-formatting-rules.md
  packages/website/docusaurus.config.mts
  packages/website/plugins/generated-rule-docs/insertions/insertWhenNotToUseIt.ts
  packages/website/sidebars/sidebar.base.js
Labels: documentation, awaiting response

#9324 feat(eslint-plugin): [no-unused-vars] add `reportUnusedIgnorePattern` option
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unused-vars.shot
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/src/variable/index.ts
  packages/scope-manager/tests/fixtures/ts-enum/external-ref.ts.shot
  packages/scope-manager/tests/fixtures/ts-enum/literal-member-ref.ts.shot
  packages/scope-manager/tests/fixtures/ts-enum/literal-member.ts.shot
  packages/scope-manager/tests/fixtures/ts-enum/member-ref.ts.shot
  packages/scope-manager/tests/fixtures/ts-enum/scope.ts.shot
  packages/scope-manager/tests/fixtures/ts-enum/self-ref.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/signatures/method-computed-name2.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/signatures/property-computed-name2.ts.shot
  packages/utils/src/ts-eslint/Scope.ts
Labels: enhancement, 1 approval

#9427 test(type-utils): skip mysteriously failing type unit tests
  packages/type-utils/tests/getTypeName.test.ts
  packages/type-utils/tests/typeFlagUtils.test.ts
Labels: 1 approval

#9325 feat(eslint-plugin): [no-unused-vars] support `ignoreClassWithStaticInitBlock`
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unused-vars.shot
Labels: enhancement, 1 approval

#9326 feat(eslint-plugin): [no-unused-vars] handle comma operator for assignments, treat for-of the same as for-in
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
Labels: enhancement, 1 approval

#8752 feat(eslint-plugin): [array-type] detect `Readonly<string[]>` case
  packages/eslint-plugin/docs/rules/array-type.mdx
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/array-type.shot
  packages/eslint-plugin/tests/rules/array-type.test.ts
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/src/types/InvalidTestCase.ts
  packages/rule-tester/src/types/ValidTestCase.ts
  packages/rule-tester/src/types/index.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/website/plugins/generated-rule-docs/RuleDocsPage.ts
Labels: enhancement, 1 approval

#8173 feat(eslint-plugin): [no-unnecessary-type-parameters] initial implementation
  eslint.config.mjs
  packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-type-parameters.shot
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-type-parameters.shot
  packages/repo-tools/src/generate-contributors.mts
  packages/scope-manager/tests/test-utils/getSpecificNode.ts
  packages/typescript-eslint/src/configs/all.ts
  packages/typescript-eslint/src/configs/disable-type-checked.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/convert.test.ts
  packages/typescript-estree/tests/test-utils/test-utils.ts
  packages/utils/src/ast-utils/helpers.ts
  packages/utils/src/eslint-utils/deepMerge.ts
  packages/website/src/globals.d.ts
Labels: enhancement: new plugin rule, 1 approval, team assigned

#9444 feat(type-utils): remove getTokenAtPosition
  packages/type-utils/src/getTokenAtPosition.ts
  packages/type-utils/src/index.ts
Labels: breaking change, 1 approval

#9330 feat(eslint-plugin): [no-unused-vars] report if var used only in typeof
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/src/util/isTypeImport.ts
  packages/eslint-plugin/src/util/referenceContainsTypeQuery.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/utils/src/ts-eslint/Linter.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/utils/src/ts-eslint/SourceCode.ts
  packages/utils/src/ts-eslint/eslint/FlatESLint.ts
  packages/utils/src/ts-eslint/eslint/LegacyESLint.ts
Labels: 1 approval

#9385 test(type-utils): add tests for isSymbolFromDefaultLibrary
  packages/type-utils/tests/isSymbolFromDefaultLibrary.test.ts
Labels: 1 approval

#9429 docs: add Performance FAQ about slow TypeScript types
  docs/troubleshooting/typed-linting/Performance.mdx
Labels: 1 approval

#9442 chore: help fix Codecov uploads by bumping to v4.5.0
  .github/workflows/ci.yml
Labels: 1 approval
