Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-09, with the labels that each got.

#9881 chore(eslint-plugin-internal): noUnnecessaryNoFormat
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
  packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
  packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
  packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
  packages/eslint-plugin/tests/rules/return-await.test.ts
  packages/eslint-plugin/tests/rules/typedef.test.ts
Labels: 1 approval

#9892 docs: add Troubleshooting entry for debugging slow lint rules
  docs/troubleshooting/typed-linting/Performance.mdx
Labels: 1 approval

#9640 chore: enable unicorn/no-array-reduce
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/parse-options.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/tests/configs.test.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
  packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/parser/src/parser.ts
  packages/typescript-eslint/tests/configs.test.ts
  packages/typescript-estree/src/parseSettings/resolveProjectList.ts
  packages/utils/src/eslint-utils/deepMerge.ts
  packages/website/src/components/lib/jsonSchema.ts
  tools/scripts/generate-configs.mts
Labels: 1 approval

#9479 feat(eslint-plugin): [no-duplicate-type-constituents] prevent unnecessary `| undefined` for optional parameters
  packages/eslint-plugin/docs/rules/no-duplicate-type-constituents.mdx
  packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts
  packages/eslint-plugin/src/rules/prefer-find.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-duplicate-type-constituents.shot
  packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts
Labels: 1 approval

#9915 chore: enable `unicorn/no-length-as-slice-end`
  eslint.config.mjs
  package.json
  packages/website/src/components/ast/utils.ts
  yarn.lock
Labels: 1 approval

#9898 fix(eslint-plugin): [no-unnecessary-type-assertion] fix TSNonNullExpression fixer
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: 1 approval

#9834 chore: enable unicorn/prefer-spread
  eslint.config.mjs
  packages/ast-spec/tests/fixtures.test.ts
  packages/ast-spec/tests/util/serializers/Node.ts
  packages/eslint-plugin/src/rules/consistent-type-exports.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/no-shadow.ts
  packages/eslint-plugin/src/rules/prefer-function-type.ts
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/rule-schema-to-typescript-types/src/generateType.ts
  packages/rule-schema-to-typescript-types/src/optimizeAST.ts
  packages/rule-schema-to-typescript-types/src/printAST.ts
  packages/rule-tester/src/utils/flat-config-schema.ts
  packages/scope-manager/src/ScopeManager.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/create-program/createProjectProgramError.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/getModifiers.ts
  packages/typescript-estree/src/parseSettings/resolveProjectList.ts
  packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/utils/src/eslint-utils/deepMerge.ts
  packages/website-eslint/src/mock/path.js
  packages/website/src/components/config/ConfigTypeScript.tsx
  packages/website/src/components/editor/LoadedEditor.tsx
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/lib/jsonSchema.ts
  packages/website/src/components/linter/createLinter.ts
  packages/website/src/components/linter/createParser.ts
  packages/website/src/theme/NotFound/Content/index.tsx
  tools/scripts/generate-lib.mts
Labels: 1 approval

#9932 chore: enable `unicorn/prefer-array-some`
  eslint.config.mjs
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/website/tools/typedoc-plugin-no-inherit-fork.mjs
Labels: 1 approval

#9927 chore: add blog/authors.yml for Docusaurus
  packages/website/blog/2022-09-18-automated-rule-docs-with-docusaurus-and-remark.md
  packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
  packages/website/blog/2023-02-24-consistent-type-exports-and-imports-why-and-how.md
  packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
  packages/website/blog/2023-07-09-announcing-typescript-eslint-v6.md
  packages/website/blog/2023-09-18-parser-options-project-true.md
  packages/website/blog/2023-12-25-deprecating-formatting-rules.md
  packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
  packages/website/blog/2024-03-25-changes-to-consistent-type-imports-with-decorators.md
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
  packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
  packages/website/blog/authors.yml
Labels: 1 approval

#9919 chore: also test rule-tester in CI
  .github/workflows/ci.yml
Labels: 1 approval

#9914 docs: mark allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing options as deprecated
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
  packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
Labels: 1 approval

#9920 feat(eslint-plugin): [no-unsafe-argument] differentiate error types
  packages/eslint-plugin/docs/rules/no-unsafe-argument.mdx
  packages/eslint-plugin/src/rules/no-unsafe-argument.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-argument.shot
  packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
Labels: 1 approval

#9951 fix(eslint-plugin): [no-misused-promises] handle static method
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: 1 approval

#9953 docs: [no-floating-promises] add MDN link regarding void operator
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
Labels: 1 approval

#9948 chore: enable `eslint-plugin-regexp`
  eslint.config.mjs
  package.json
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/rule-tester/src/utils/flat-config-schema.ts
  packages/rule-tester/src/utils/interpolate.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/website-eslint/src/mock/path.js
  yarn.lock
Labels: 1 approval

#9931 chore: use mdast-util-from-markdown's fromMarkdown in website
  packages/website/package.json
  packages/website/plugins/generated-rule-docs/RuleDocsPage.ts
  packages/website/plugins/generated-rule-docs/index.ts
  packages/website/plugins/generated-rule-docs/insertions/insertBaseRuleReferences.ts
  packages/website/plugins/generated-rule-docs/insertions/insertFormattingNotice.ts
  packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
  packages/website/plugins/generated-rule-docs/insertions/insertResources.ts
  packages/website/plugins/generated-rule-docs/insertions/insertRuleDescription.ts
  packages/website/plugins/generated-rule-docs/insertions/insertWhenNotToUseIt.ts
  yarn.lock
Labels: 1 approval

#9958 chore: pin eslint version in `@types/eslint@v8` integration test
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/package.json
Labels: 1 approval

#9937 feat(type-utils): isNullableType add Void logic
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/type-utils/src/predicates.ts
Labels: 1 approval

#9959 docs: clean up remaining allowDefaultProject(ForFiles) vestiges
  docs/developers/Custom_Rules.mdx
  docs/packages/Rule_Tester.mdx
Labels: 1 approval

#9979 chore: allow selecting eslint-plugin in 'Another Package' issues
  .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
Labels: 1 approval

#9978 fix(eslint-plugin): [no-deprecated] report on deprecated variables used in destructuring assignment
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#9977 fix(eslint-plugin): [no-deprecated] report on deprecated properties with function-like types
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
  packages/utils/tests/ts-eslint/ESLint.test.ts
Labels: 1 approval

#9820 docs: add note about typescript-eslint as peer dependency
  docs/developers/ESLint_Plugins.mdx
Labels: awaiting response

#9989 fix(typescript-estree): don't throw on missing tsconfig.json by default in project service
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/tests/lib/createProjectService.test.ts
Labels: 1 approval

#9964 feat(typescript-estree): disable plugin loading by default in project service
  docs/packages/Parser.mdx
  docs/packages/TypeScript_ESTree.mdx
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/tests/lib/createProjectService.test.ts
Labels: 1 approval

#9912 feat(eslint-plugin): [no-unnecessary-condition] check switch cases
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#9981 test(eslint-plugin): [no-unnecessary-type-parameters] add tests with intrinsic `NoInfer`
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: 1 approval

#8556 feat: add `allow` option for `restrict-template-expressions`
  packages/eslint-plugin/docs/rules/restrict-template-expressions.mdx
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/restrict-template-expressions.shot
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
  packages/eslint-plugin/tests/schema-snapshots/restrict-template-expressions.shot
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/type-utils/src/isTypeReadonly.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Labels: 1 approval

#9992 fix(utils): add missing entries to the RuleListener selectors list
  knip.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/utils/tests/ts-eslint/Rule.type-test.ts
Labels: 1 approval

#10018 docs: fix typo for `only-throw-error` rule
  packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md
Labels: 1 approval

#10021 docs: misnamed `no-deprecation`/`no-deprecated` in CHANGELOG.md
  CHANGELOG.md
Labels: 1 approval

#10004 fix(eslint-plugin): properly coerce all types to string in `getStaticMemberAccessValue`
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/class-methods-use-this.ts
  packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
  packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts
Labels: 1 approval

#9987 fix(eslint-plugin): [no-deprecated] report on imported deprecated variables
  packages/eslint-plugin/src/rules/no-deprecated.ts
  packages/eslint-plugin/tests/fixtures/deprecated.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.json
  packages/eslint-plugin/tests/fixtures/tsconfig.moduleResolution-node16.json
  packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Labels: 1 approval

#9994 fix(eslint-plugin): [no-confusing-non-null-assertion] check !in and !instanceof
  packages/eslint-plugin/docs/rules/no-confusing-non-null-assertion.mdx
  packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-confusing-non-null-assertion.shot
  packages/eslint-plugin/tests/rules/no-confusing-non-null-assertion.test.ts
Labels: enhancement, 1 approval

#10010 feat(eslint-plugin): [no-unsafe-call] check calls of Function
  packages/eslint-plugin/docs/rules/no-unsafe-call.mdx
  packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-call.shot
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-function-type.test.ts
  packages/website/src/components/lib/parseConfig.ts
Labels: enhancement, 1 approval

#9975 docs: [no-unnecessary-type-parameters] add FAQ section
  packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: documentation

#10045 docs: [no-duplicate-type-constituents] clarify relation to exactOptionalPropertyTypes
  packages/eslint-plugin/docs/rules/no-duplicate-type-constituents.mdx
Labels: 1 approval

#10044 fix(eslint-plugin): [no-unnecessary-template-expression] should underline template syntax with squiggly lines
  packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
  packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
  packages/eslint-plugin/src/util/rangeToLoc.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-template-expression.shot
  packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
Labels: 1 approval

#10026 fix(type-utils): check for type parameters on `isBuiltinSymbolLikeRecurser()`
  packages/eslint-plugin/tests/rules/only-throw-error.test.ts
  packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts
  packages/type-utils/src/builtinSymbolLikes.ts
Labels: 1 approval

#10042 fix(eslint-plugin): [no-misused-promises] check contextual type
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: 1 approval

#10009 feat(eslint-plugin): [no-unnecessary-condition] add checkTypePredicates
  eslint.config.mjs
  packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/src/util/assertionFunctionUtils.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-condition.shot
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-condition.shot
  packages/type-utils/src/getTypeName.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/typescript-estree/tests/lib/source-files.test.ts
  packages/typescript-estree/tests/test-utils/test-utils.ts
  packages/website/src/components/typeDetails/SimplifiedTreeView.tsx
Labels: enhancement, 1 approval

#10070 fix: remove `export type *` in d.ts to support TS<5.0
  eslint.config.mjs
  packages/ast-spec/src/declaration/spec.ts
  packages/ast-spec/src/element/spec.ts
  packages/ast-spec/src/expression/AssignmentExpression/spec.ts
  packages/ast-spec/src/expression/BinaryExpression/spec.ts
  packages/ast-spec/src/expression/literal/spec.ts
  packages/ast-spec/src/expression/spec.ts
  packages/ast-spec/src/index.ts
  packages/ast-spec/src/jsx/spec.ts
  packages/ast-spec/src/parameter/spec.ts
  packages/ast-spec/src/special/spec.ts
  packages/ast-spec/src/statement/spec.ts
  packages/ast-spec/src/token/PunctuatorToken/spec.ts
  packages/ast-spec/src/token/spec.ts
  packages/ast-spec/src/type/spec.ts
  packages/eslint-plugin/src/util/index.ts
  packages/scope-manager/src/definition/index.ts
  packages/scope-manager/src/scope/index.ts
  packages/types/src/index.ts
  packages/typescript-estree/src/ts-estree/index.ts
  packages/utils/src/eslint-utils/index.ts
  packages/utils/src/index.ts
  packages/utils/src/ts-eslint/index.ts
Labels: 1 approval

#10008 feat(eslint-plugin): [return-await] check for-await loop iteree
  packages/eslint-plugin/docs/rules/await-thenable.mdx
  packages/eslint-plugin/src/rules/await-thenable.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/await-thenable.shot
  packages/eslint-plugin/tests/rules/await-thenable.test.ts
Labels: enhancement
