Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-01, with the labels that each got.

#7202 feat(typescript-estree): throw on invalid update expressions
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/call-expr/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/call-expr/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/call-expr/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/call-expr/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/literal/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/literal/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/literal/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/literal/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain2/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain2/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain2/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain2/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain3/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain3/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain3/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/optional-chain3/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/paren-expr/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/paren-expr/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/paren-expr/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/_error_/paren-expr/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/fixture.ts
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/1-Babel-AST.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/2-Babel-Tokens.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/tests/fixtures-with-differences-ast.shot
  packages/ast-spec/tests/fixtures-with-differences-tokens.shot
  packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
  packages/eslint-plugin/tests/rules/unbound-method.test.ts
  packages/eslint-plugin/tests/util/getWrappingFixer.test.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
Labels: enhancement, 1 approval

#7710 feat(eslint-plugin): [no-var-requires, no-require-imports] allow option
  packages/eslint-plugin/docs/rules/no-require-imports.md
  packages/eslint-plugin/docs/rules/no-var-requires.md
  packages/eslint-plugin/src/rules/no-require-imports.ts
  packages/eslint-plugin/src/rules/no-var-requires.ts
  packages/eslint-plugin/tests/rules/no-require-imports.test.ts
  packages/eslint-plugin/tests/rules/no-var-requires.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-require-imports.shot
  packages/eslint-plugin/tests/schema-snapshots/no-var-requires.shot
Labels: enhancement: plugin rule option, accepting prs

#8194 chore: use nx release
  .github/workflows/ci.yml
  CHANGELOG.md
  docs/Packages.mdx
  docs/maintenance/Releases.mdx
  lerna.json
  nx.json
  package.json
  packages/ast-spec/CHANGELOG.md
  packages/ast-spec/project.json
  packages/eslint-plugin-internal/CHANGELOG.md
  packages/eslint-plugin-internal/project.json
  packages/eslint-plugin-tslint/CHANGELOG.md
  packages/eslint-plugin-tslint/project.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/project.json
  packages/integration-tests/CHANGELOG.md
  packages/integration-tests/project.json
  packages/parser/CHANGELOG.md
  packages/parser/project.json
  packages/repo-tools/CHANGELOG.md
  packages/repo-tools/package.json
  packages/repo-tools/project.json
  packages/repo-tools/src/apply-canary-version.mts
  packages/rule-schema-to-typescript-types/CHANGELOG.md
  packages/rule-schema-to-typescript-types/project.json
  packages/rule-tester/CHANGELOG.md
  packages/rule-tester/project.json
  packages/scope-manager/CHANGELOG.md
  packages/scope-manager/project.json
  packages/type-utils/CHANGELOG.md
  packages/type-utils/project.json
  packages/types/CHANGELOG.md
  packages/types/project.json
  packages/typescript-estree/CHANGELOG.md
  packages/typescript-estree/project.json
  packages/utils/CHANGELOG.md
  packages/utils/project.json
  packages/visitor-keys/CHANGELOG.md
  packages/visitor-keys/project.json
  packages/website-eslint/CHANGELOG.md
  packages/website-eslint/project.json
  packages/website/CHANGELOG.md
  packages/website/project.json
  tools/release/changelog-renderer.js
  tools/release/release.ts
  yarn.lock
Labels: awaiting response

#8065 feat(eslint-plugin): [no-useless-template-literals] add fix suggestions
  .cspell.json
  packages/eslint-plugin/src/rules/no-useless-template-literals.ts
  packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
Labels: awaiting response

#8193 fix(typescript-estree): add JSDocParsingMode enum merge for typescript/lib/tsserverlibrary
  packages/typescript-estree/src/parseSettings/index.ts
Labels: bug

#7649 fix(typescript-estree): disallow `using` as the variable keyword for `for..in` loops
  packages/ast-spec/src/statement/ForInStatement/fixtures/_error_/using-initializer/fixture.ts
  packages/ast-spec/src/statement/ForInStatement/fixtures/_error_/using-initializer/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/statement/ForInStatement/fixtures/_error_/using-initializer/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/statement/ForInStatement/fixtures/_error_/using-initializer/snapshots/3-Alignment-Error.shot
  packages/typescript-estree/src/convert.ts
Labels: bug

#8089 fix(eslint-plugin): [no-unnecesary-type-assertion] treat unknown/any as nullable
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/type-utils/src/predicates.ts
Labels: bug

#8181 fix(typescript-estree): fix incorrect backwards-compat augmentation in TS 5.3
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/ts-estree/ts-nodes.ts
Labels: bug

#8237 fix(type-utils): preventing isUnsafeAssignment infinite recursive calls
  packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
  packages/type-utils/src/isUnsafeAssignment.ts
  packages/type-utils/tests/isUnsafeAssignment.test.ts
Labels: 1 approval

#8235 fix(eslint-plugin): [no-unnecessary-condition] fix false positive for type variable
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#8190 docs: add `import/no-unresolved` to perf troubleshooting docs
  docs/linting/troubleshooting/Performance.mdx
Labels: documentation

#8248 feat(eslint-plugin): [member-ordering] allow easy reuse of the default ordering
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/tests/rules/member-ordering.test.ts
Labels: enhancement

#8306 docs: show all articles in sidebar, and a missing truncate
  packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
  packages/website/blog/2023-02-24-consistent-type-exports-and-imports-why-and-how.md
  packages/website/docusaurusConfig.ts
Labels: documentation

#7955 chore: enable prefer-nullish-coalescing internally
  .eslintrc.js
  packages/eslint-plugin/src/rules/padding-line-between-statements.ts
  packages/eslint-plugin/src/rules/unified-signatures.ts
  packages/rule-tester/src/utils/getRuleOptionsSchema.ts
Labels: 1 approval, repo maintenance

#8295 fix(eslint-plugin): [no-useless-template-literals] report Infinity & NaN
  packages/eslint-plugin/src/rules/no-useless-template-literals.ts
  packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
Labels: 1 approval

#8300 fix(eslint-plugin): [prefer-readonly] disable checking accessors
  packages/eslint-plugin/src/rules/prefer-readonly.ts
  packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
Labels: awaiting response

#8265 fix(eslint-plugin): [no-unused-vars] don't report on types referenced in export assignment expression
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/scope-manager/src/referencer/ExportVisitor.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/scope-manager/tests/fixtures/export/equals1.ts.shot
  packages/scope-manager/tests/fixtures/export/equals3-type.ts
  packages/scope-manager/tests/fixtures/export/equals3-type.ts.shot
Labels: 1 approval

#8142 test(eslint-plugin): assert that `ts`/`tsx` code blocks in docs are syntactically valid
  packages/eslint-plugin/docs/rules/ban-tslint-comment.md
  packages/eslint-plugin/docs/rules/consistent-type-assertions.md
  packages/eslint-plugin/docs/rules/explicit-function-return-type.md
  packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
  packages/eslint-plugin/docs/rules/member-ordering.md
  packages/eslint-plugin/docs/rules/no-empty-function.md
  packages/eslint-plugin/docs/rules/no-for-in-array.md
  packages/eslint-plugin/docs/rules/no-this-alias.md
  packages/eslint-plugin/docs/rules/no-type-alias.md
  packages/eslint-plugin/docs/rules/no-unnecessary-type-arguments.md
  packages/eslint-plugin/docs/rules/no-unnecessary-type-constraint.md
  packages/eslint-plugin/docs/rules/prefer-enum-initializers.md
  packages/eslint-plugin/docs/rules/prefer-for-of.md
  packages/eslint-plugin/docs/rules/space-before-blocks.md
  packages/eslint-plugin/docs/rules/typedef.md
  packages/eslint-plugin/tests/docs.test.ts
Labels: 1 approval

#8167 chore: unpin primary node version in ci
  .github/workflows/ci.yml
Labels: repo maintenance
