Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-07, with the labels that each got.

#9304 fix(eslint-plugin): [no-unsafe-call] differentiate a types-error any from a true any
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
Labels: 1 approval

#9443 feat(eslint-plugin): back-port new rules around empty object types from v8
  packages/eslint-plugin/docs/rules/no-empty-object-type.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-empty-object-type.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-empty-object-type.shot
  packages/eslint-plugin/tests/rules/no-empty-object-type.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-empty-object-type.shot
  packages/typescript-eslint/src/configs/all.ts
Labels: 1 approval

#9086 feat(rule-tester): stricter rule test validations
  packages/eslint-plugin/tests/rules/no-empty-object-type.test.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
  packages/eslint-plugin/tests/rules/prefer-as-const.test.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/tests/eslint-base/eslint-base.test.js
  packages/rule-tester/tests/eslint-base/fixtures/suggestions.js
Labels: enhancement, 1 approval

#9473 feat(eslint-plugin): [no-unnecessary-type-parameters] port from v8 to v7
  eslint.config.mjs
  packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-type-parameters.shot
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-type-parameters.shot
  packages/repo-tools/src/generate-contributors.mts
  packages/scope-manager/tests/test-utils/getSpecificNode.ts
  packages/typescript-eslint/src/configs/all.ts
  packages/typescript-eslint/src/configs/disable-type-checked.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/test-utils/test-utils.ts
  packages/utils/src/ast-utils/helpers.ts
  packages/utils/src/eslint-utils/deepMerge.ts
  packages/website/src/globals.d.ts
Labels: 1 approval

#9483 docs: tseslint.config takes a spread argument, not an array
  docs/packages/TypeScript_ESLint.mdx
Labels: 1 approval

#9487 feat(ast-spec): add parent property to AccessorProperty node types
  packages/types/src/ts-estree.ts
Labels: 1 approval

#8903 feat(eslint-plugin): [no-unnecessary-parameter-property-assignment] add new rule
  packages/eslint-plugin/docs/rules/no-unnecessary-parameter-property-assignment.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-parameter-property-assignment.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-parameter-property-assignment.shot
  packages/eslint-plugin/tests/rules/no-unnecessary-parameter-property-assignment.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-parameter-property-assignment.shot
  packages/typescript-eslint/src/configs/all.ts
Labels: enhancement: new plugin rule, 1 approval

#9119 chore: use eslint 9 internally
  .github/workflows/ci.yml
  eslint.config.mjs
  package.json
  packages/eslint-plugin/rules.d.ts
  packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/base-cases.ts
  packages/eslint-plugin/tests/schema-snapshots/no-restricted-imports.shot
  packages/integration-tests/fixtures/markdown/.eslintrc.js
  packages/integration-tests/fixtures/markdown/eslint.config.js
  packages/integration-tests/fixtures/markdown/package.json
  packages/integration-tests/fixtures/recommended-does-not-require-program/eslint.config.js
  packages/integration-tests/fixtures/recommended-does-not-require-program/package.json
  packages/integration-tests/fixtures/vue-jsx/.eslintrc.js
  packages/integration-tests/fixtures/vue-jsx/eslint.config.js
  packages/integration-tests/fixtures/vue-jsx/package.json
  packages/integration-tests/fixtures/vue-sfc/.eslintrc.js
  packages/integration-tests/fixtures/vue-sfc/eslint.config.js
  packages/integration-tests/fixtures/vue-sfc/package.json
  packages/integration-tests/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
  packages/integration-tests/tests/flat-config-types.test.ts
  packages/integration-tests/tools/integration-test-base.ts
  packages/website-eslint/build.ts
  packages/website/src/hooks/useClipboard.ts
  packages/website/src/theme/MDXComponents/RuleAttributes.tsx
  typings/eslint-plugin-deprecation.d.ts
  typings/eslint__compat.d.ts
  yarn.lock
Labels: 1 approval

#9302 docs: add snapshot-related info sections to the Pull Requests documentation
  docs/contributing/Pull_Requests.mdx
Labels: 1 approval

#9478 feat(eslint-plugin): add support for nested namespaces to unsafe-member-access
  packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
  packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
Labels: 1 approval

#9263 feat(eslint-plugin): [no-floating-promises] add checkThenables option
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-floating-promises.shot
Labels: 1 approval

#9492 fix(eslint-plugin): [restrict-template-expressions] don't report tuples if `allowArray` option is enabled
  packages/eslint-plugin/src/rules/restrict-template-expressions.ts
  packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
Labels: 1 approval

#9363 docs: [no-wrapper-object-types] clean up a bit of phrasing
  packages/eslint-plugin/docs/rules/no-wrapper-object-types.mdx
Labels: 1 approval

#9530 fix(eslint-plugin): [no-unnecessary-type-parameters] descend into all parts of mapped types in no-unnecessary-type-parameters
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: 1 approval

#9559 feat(eslint-plugin): [no-floating-promises] disable checkThenables by default for v8
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: 1 approval

#9560 feat: stricter parent types for the AST
  packages/ast-spec/src/element/TSEnumMember/spec.ts
  packages/ast-spec/src/special/TSEnumBody/spec.ts
  packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/src/rules/class-methods-use-this.ts
  packages/eslint-plugin/src/rules/method-signature-style.ts
  packages/eslint-plugin/src/rules/no-extraneous-class.ts
  packages/eslint-plugin/src/rules/no-misused-new.ts
  packages/eslint-plugin/src/rules/no-restricted-imports.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
  packages/eslint-plugin/src/rules/no-useless-constructor.ts
  packages/types/src/ts-estree.ts
Labels: 1 approval

#9562 docs: show importing configs in shared configs page
  docs/users/Shared_Configurations.mdx
Labels: documentation, 1 approval

#9553 chore: enable no-useless-computed-key
  eslint.config.mjs
  packages/eslint-plugin/src/rules/prefer-find.ts
Labels: 1 approval

#9539 chore: enable prefer-rest-params
  eslint.config.mjs
  packages/website-eslint/src/mock/path.js
Labels: 1 approval

#9552 chore: enable no-void
  eslint.config.mjs
  packages/rule-tester/src/RuleTester.ts
  packages/website/src/hooks/useClipboard.ts
Labels: 1 approval

#9043 fix(eslint-plugin): [no-floating-promises] check top-level type assertions (and more)
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: bug, 1 approval

#9502 docs: mention trying major version betas on plugins
  docs/maintenance/Releases.mdx
Labels: 1 approval

#9577 fix(typescript-estree): don't infer single-run when --fix is in proces.argv
  packages/typescript-estree/src/parseSettings/inferSingleRun.ts
  packages/typescript-estree/tests/lib/inferSingleRun.test.ts
Labels: 1 approval

#9500 fix(type-utils): also check declared modules for package names in TypeOrValueSpecifier
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/type-utils/src/typeOrValueSpecifiers/specifierNameMatches.ts
  packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInFile.ts
  packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInLib.ts
  packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Labels: bug, 1 approval

#9507 feat(eslint-plugin): backport no-unsafe-function type, no-wrapper-object-types from v8 to v7
  packages/eslint-plugin/docs/rules/ban-types.mdx
  packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
  packages/eslint-plugin/docs/rules/no-wrapper-object-types.mdx
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unsafe-function-type.ts
  packages/eslint-plugin/src/rules/no-wrapper-object-types.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/scopeUtils.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-function-type.shot
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-wrapper-object-types.shot
  packages/eslint-plugin/tests/rules/no-unsafe-function-type.test.ts
  packages/eslint-plugin/tests/rules/no-wrapper-object-types.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-unsafe-function-type.shot
  packages/eslint-plugin/tests/schema-snapshots/no-wrapper-object-types.shot
  packages/typescript-eslint/src/configs/all.ts
Labels: 1 approval

#9593 chore(website): correct version to be v8, not latest merged v7
  packages/website/docusaurus.config.mts
  packages/website/src/components/OptionsSelector.tsx
  packages/website/webpack.plugin.js
Labels: 1 approval

#9074 fix(eslint-plugin): [strict-boolean-expressions] consider assertion function argument a boolean context
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/strict-boolean-expressions.shot
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: bug, 1 approval

#8688 fix(eslint-plugin): [no-unnecessary-template-expression] do not render escaped strings in autofixes
  packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
Labels: bug, 1 approval

#9586 fix(typescript-estree): disable includePackageJsonAutoImports in ProjectService
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/tests/lib/createProjectService.test.ts
Labels: 1 approval

#9585 docs: clarify projectService out-of-project remediation steps
  docs/packages/Parser.mdx
  docs/troubleshooting/typed-linting/index.mdx
Labels: 1 approval

#8322 feat: speed up non-type-aware linting with project service
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/parser.ts
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Labels: team assigned

#9551 chore: enable no-var
  eslint.config.mjs
  packages/website-eslint/src/mock/path.js
Labels: 1 approval

#9602 fix(eslint-plugin): [no-unnecessary-condition] false positive on optional private field
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#9598 fix(website): expose ATA types to eslint instance
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/vendor/sandbox.d.ts
  packages/website/src/vendor/typescript-vfs.d.ts
Labels: 1 approval

#9604 feat(eslint-plugin): [return-await] add return-await to strict-type-checked preset
  packages/eslint-plugin/src/configs/strict-type-checked-only.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/rules/return-await.ts
  packages/typescript-eslint/src/configs/strict-type-checked-only.ts
  packages/typescript-eslint/src/configs/strict-type-checked.ts
  packages/utils/src/ts-eslint/Rule.ts
Labels: 1 approval

#9532 fix(eslint-plugin): [no-unused-vars] incorporate upstream changes around caught errors report messages
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
Labels: 1 approval

#9622 test: add integration test against @types/eslint v9
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/dirname.cjs
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/eslint.config.js
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/package.json
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/dirname.cjs
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/eslint.config.js
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/package.json
  packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v8.test.ts.snap
  packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v9.test.ts.snap
  packages/integration-tests/tests/flat-config-types-@types__eslint-v8.test.ts
  packages/integration-tests/tests/flat-config-types-@types__eslint-v9.test.ts
Labels: tests, 1 approval

#9306 fix(typescript-estree): adds support for project services using extended config files
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/src/create-program/getParsedConfigFile.ts
  packages/typescript-estree/src/create-program/useProvidedPrograms.ts
  packages/typescript-estree/tests/lib/createProjectService.test.ts
  packages/typescript-estree/tests/lib/getParsedConfigFile.test.ts
Labels: 1 approval

#9656 fix(eslint-plugin): [no-misused-promises] perf: avoid getting types of variables/functions if the annotated type is obviously not a function
  eslint.config.mjs
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Labels: 1 approval, performance

#9614 docs: switch Typed Linting docs to project service
  docs/getting-started/Typed_Linting.mdx
  docs/troubleshooting/faqs/Frameworks.mdx
  docs/troubleshooting/typed-linting/Monorepos.mdx
  docs/troubleshooting/typed-linting/Performance.mdx
  docs/troubleshooting/typed-linting/index.mdx
Labels: 1 approval

#9633 feat(type-utils): support intersection types in TypeOrValueSpecifier
  packages/type-utils/src/typeOrValueSpecifiers/specifierNameMatches.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Labels: 1 approval

#9660 fix(eslint-plugin): [no-unnecessary-type-assertion] prevent runtime error when asserting a variable declared in default TS lib
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: 1 approval

#9600 fix(eslint-plugin): [no-duplicate-type-constituents] shouldn't report on error types
  packages/eslint-plugin/docs/rules/no-duplicate-type-constituents.mdx
  packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-duplicate-type-constituents.shot
  packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts
Labels: 1 approval

#9611 docs: remove unnecessary v8 links
  packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
  packages/eslint-plugin/docs/rules/no-wrapper-object-types.mdx
Labels: 1 approval

#9662 feat(eslint-plugin): [no-unnecessary-type-parameters] promote to strict
  packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
  packages/eslint-plugin/src/configs/strict-type-checked-only.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/typescript-eslint/src/configs/strict-type-checked-only.ts
  packages/typescript-eslint/src/configs/strict-type-checked.ts
Labels: 1 approval

#9297 fix(eslint-plugin): [strict-boolean-expressions] support branded booleans
  packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Labels: 1 approval

#9612 docs: link no-duplicate-type-constituents and no-redundant-type-constituents to each other
  packages/eslint-plugin/docs/rules/no-duplicate-type-constituents.mdx
  packages/eslint-plugin/docs/rules/no-redundant-type-constituents.mdx
Labels: 1 approval

#9659 chore: use parserOptions.projectService internally
  eslint.config.mjs
  package.json
  packages/eslint-plugin/tsconfig.json
  yarn.lock
Labels: 1 approval

#9675 fix(typescript-estree): factor tsconfigRootDir into allowDefaultProject
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Labels: 1 approval
