Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-08, with the labels that each got.

#9694 fix(eslint-plugin): [no-unused-vars] ignore imports used only as types
  packages/eslint-plugin/src/rules/no-unused-vars.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Labels: 1 approval

#9687 chore: enable unicorn/no-useless-spread
  eslint.config.mjs
  packages/eslint-plugin/src/rules/naming-convention-utils/schema.ts
Labels: 1 approval

#9657 fix(utils): correct types to align with @types/eslint v9
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/package.json
  packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/package.json
  packages/integration-tests/tests/flat-config-types-@types__eslint-v8.test.ts
  packages/integration-tests/tests/flat-config-types-@types__eslint-v9.test.ts
  packages/utils/src/ts-eslint/Config.ts
Labels: bug, 1 approval

#9702 docs: [strict-boolean-expressions] fix nullable number/string example
  packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/strict-boolean-expressions.shot
Labels: documentation, 1 approval

#9703 feat(eslint-plugin): [no-floating-promises] enable "add await" suggestion if ignoreVoid is true
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: 1 approval

#9727 chore: update husky v9 and prepare scripts for v10
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  package.json
  tools/scripts/postinstall.mts
  yarn.lock
Labels: 1 approval

#9747 chore: remove v8 mentions from docs and ci.yml
  .github/workflows/ci.yml
  .github/workflows/close-v8-issues.yml
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
  packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
  packages/website/webpack.plugin.js
Labels: 1 approval

#9745 fix(website): tsconfig is blank
  packages/website/src/components/hooks/useHashState.ts
Labels: 1 approval

#9658 chore: enable prefer-regexp-test
  eslint.config.mjs
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/parser/tests/test-utils/test-utils.ts
  packages/typescript-estree/tests/test-utils/test-utils.ts
Labels: 1 approval

#9738 fix(eslint-plugin): [no-unnecessary-type-parameters] skip checking function bodies for AST references
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: 1 approval

#9775 fix(eslint-plugin): [member-ordering] get accessor member name & take into account `abstract` and decorator
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/src/util/misc.ts
  packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
Labels: 1 approval

#8693 feat(eslint-plugin): [no-unsafe-return] check promise any
  packages/eslint-plugin/docs/rules/no-unsafe-return.mdx
  packages/eslint-plugin/src/rules/no-unsafe-return.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-return.shot
  packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
  packages/eslint-plugin/typings/typescript.d.ts
  packages/type-utils/src/predicates.ts
  packages/type-utils/typings/typescript.d.ts
Labels: enhancement, 1 approval

#9597 fix(eslint-plugin): [prefer-optional-chain] wrong parenthesis fix output
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain.ts
  packages/eslint-plugin/src/util/getFixOrSuggest.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
Labels: bug, 1 approval

#8765 feat(eslint-plugin): [no-misused-promises] check subtype methods against heritage type methods
  packages/eslint-plugin/docs/rules/no-misused-promises.mdx
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-misused-promises.shot
  packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
  packages/eslint-plugin/tests/schema-snapshots/no-misused-promises.shot
Labels: enhancement, 1 approval

#9737 fix(eslint-plugin): [no-unnecessary-type-parameters] clarify message
  packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-type-parameters.shot
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: 1 approval

#9791 chore: remove repetitive words
  packages/eslint-plugin/docs/rules/no-unsafe-return.mdx
  packages/eslint-plugin/docs/rules/no-use-before-define.mdx
  packages/eslint-plugin/src/rules/init-declarations.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/typescript-estree/src/semantic-or-syntactic-errors.ts
Labels: 1 approval

#9742 chore: enable `unicorn/prefer-node-protocol`
  eslint.config.mjs
  packages/ast-spec/tests/fixtures.test.ts
  packages/eslint-plugin-internal/src/rules/no-relative-paths-to-internal-packages.ts
  packages/eslint-plugin-internal/tests/RuleTester.ts
  packages/eslint-plugin-internal/tests/rules/no-relative-paths-to-internal-packages.test.ts
  packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
  packages/eslint-plugin/tests/RuleTester.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/index.test.ts
  packages/eslint-plugin/tests/rules/index.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
  packages/integration-tests/tools/pack-packages.ts
  packages/parser/tests/lib/parser.test.ts
  packages/parser/tests/lib/services.test.ts
  packages/scope-manager/tests/fixtures.test.ts
  packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInFile.ts
  packages/type-utils/tests/TypeOrValueSpecifier.test.ts
  packages/type-utils/tests/getTypeName.test.ts
  packages/type-utils/tests/isSymbolFromDefaultLibrary.test.ts
  packages/type-utils/tests/isTypeReadonly.test.ts
  packages/type-utils/tests/isUnsafeAssignment.test.ts
  packages/type-utils/tests/typeFlagUtils.test.ts
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-estree/src/create-program/createProjectProgram.ts
  packages/typescript-estree/src/create-program/describeFilePath.ts
  packages/typescript-estree/src/create-program/getParsedConfigFile.ts
  packages/typescript-estree/src/create-program/getScriptKind.ts
  packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
  packages/typescript-estree/src/create-program/shared.ts
  packages/typescript-estree/src/create-program/useProvidedPrograms.ts
  packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
  packages/typescript-estree/src/parseSettings/inferSingleRun.ts
  packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
  packages/typescript-estree/tests/lib/inferSingleRun.test.ts
  packages/typescript-estree/tests/lib/parse.project-true.test.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/typescript-estree/tests/lib/persistentParse.test.ts
  packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
  packages/typescript-estree/tests/lib/semanticInfo.test.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
  packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
  packages/website/plugins/utils/rules.ts
  packages/website/webpack.plugin.js
  tools/scripts/generate-sponsors.mts
Labels: 1 approval

#9784 docs: fix outdated project setting
  docs/packages/TypeScript_ESLint.mdx
Labels: 1 approval

#9812 docs: next page navigation link pointing to current page
  docs/troubleshooting/faqs/General.mdx
Labels: documentation

#9789 docs: add 'Breaking Changes' section to 8.0.0 changelog entry
  CHANGELOG.md
Labels: 1 approval

#9711 test(type-utils): add tests for containsAllTypesByName
  packages/type-utils/tests/containsAllTypesByName.test.ts
Labels: 1 approval

#9059 fix(eslint-plugin): [use-unknown-in-catch-callback-variable] flag second argument of `.then`
  packages/eslint-plugin/docs/rules/use-unknown-in-catch-callback-variable.mdx
  packages/eslint-plugin/src/rules/use-unknown-in-catch-callback-variable.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/use-unknown-in-catch-callback-variable.shot
  packages/eslint-plugin/tests/rules/use-unknown-in-catch-callback-variable.test.ts
Labels: bug, 1 approval

#9209 fix(eslint-plugin): [no-unnecessary-type-assertion] conflict with TS for variables used before assignment
  packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.json
  packages/eslint-plugin/tests/fixtures/var-declaration.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Labels: bug, 1 approval

#9513 fix(eslint-plugin): delete [] in message if ReadOnly<string[]> is detected
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
Labels: bug, 1 approval

#9555 fix(eslint-plugin): [no-redundant-type-constituents] differentiate a types-error any from a true any
  packages/eslint-plugin/src/rules/no-redundant-type-constituents.ts
  packages/eslint-plugin/tests/rules/no-redundant-type-constituents.test.ts
Labels: 1 approval

#9718 feat(eslint-plugin): add suggestion to `require-await` to remove `async` keyword
  packages/eslint-plugin/src/rules/require-await.ts
  packages/eslint-plugin/src/util/index.ts
  packages/eslint-plugin/src/util/isStartOfExpressionStatement.ts
  packages/eslint-plugin/src/util/needsPrecedingSemiColon.ts
  packages/eslint-plugin/tests/rules/require-await.test.ts
Labels: enhancement, 1 approval

#9740 fix(eslint-plugin): [no-unnecessary-type-parameters] check mapped constraint types if necessary
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: 1 approval

#9757 chore: clean up generate-sponsors
  tools/scripts/generate-sponsors.mts
  tsconfig.json
Labels: 1 approval

#9798 chore: enable unicorn/prefer-string-replace-all
  eslint.config.mjs
  packages/ast-spec/tests/fixtures.test.ts
  packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
  packages/eslint-plugin/src/rules/enum-utils/shared.ts
  packages/eslint-plugin/src/rules/member-ordering.ts
  packages/eslint-plugin/src/rules/naming-convention-utils/shared.ts
  packages/eslint-plugin/src/rules/no-invalid-void-type.ts
  packages/eslint-plugin/src/rules/no-restricted-types.ts
  packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
  packages/eslint-plugin/src/rules/prefer-includes.ts
  packages/eslint-plugin/src/util/escapeRegExp.ts
  packages/eslint-plugin/tests/docs.test.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/createTestCases.ts
  packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
  packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
  packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
  packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
  packages/integration-tests/tools/integration-test-base.ts
  packages/rule-schema-to-typescript-types/src/generateUnionType.ts
  packages/rule-tester/src/utils/config-validator.ts
  packages/rule-tester/src/utils/validationHelpers.ts
  packages/types/tools/copy-ast-spec.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/node-utils.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  packages/website-eslint/build.ts
  packages/website/src/components/editor/createProvideTwoslashInlay.ts
  packages/website/src/components/linter/utils.ts
  packages/website/src/pages/index.tsx
  packages/website/tools/generate-website-dts.ts
  tools/scripts/generate-lib.mts
Labels: 1 approval

#9777 fix(eslint-plugin): [no-unsafe-enum-comparison] add logic to see through intersections
  packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Labels: 1 approval

#9819 chore: fix `prefer-node-protocol` lint failure on main
  packages/type-utils/tests/containsAllTypesByName.test.ts
Labels: 1 approval

#8673 fix(eslint-plugin): [no-unnecessary-template-expression] add missing parentheses in autofix
  packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
Labels: bug, 1 approval

#9816 chore: enable object-shorthand
  eslint.config.mjs
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
  packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
  packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
  packages/eslint-plugin/src/rules/no-unsafe-call.ts
  packages/eslint-plugin/tests/rules/naming-convention/cases/createTestCases.ts
  packages/rule-tester/src/utils/validationHelpers.ts
  packages/typescript-estree/src/convert.ts
  packages/typescript-estree/src/parseSettings/createParseSettings.ts
  packages/website-eslint/src/mock/assert.js
  packages/website-eslint/src/mock/path.js
  packages/website/sidebars/sidebar.rules.js
  packages/website/src/components/ast/DataRenderer.tsx
  packages/website/src/components/lib/jsonSchema.ts
  packages/website/src/components/linter/createLinter.ts
  packages/website/src/components/linter/createParser.ts
  packages/website/src/components/linter/utils.ts
Labels: 1 approval

#9741 fix(eslint-plugin): [no-unnecessary-type-parameters] check mapped alias type arguments
  packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Labels: 1 approval

#9698 chore: enabled eslint-plugin-perfectionist on utils
  eslint.config.mjs
  package.json
  packages/utils/src/ast-utils/eslint-utils/PatternMatcher.ts
  packages/utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
  packages/utils/src/ast-utils/eslint-utils/astUtilities.ts
  packages/utils/src/ast-utils/eslint-utils/predicates.ts
  packages/utils/src/ast-utils/helpers.ts
  packages/utils/src/ast-utils/predicates.ts
  packages/utils/src/eslint-utils/InferTypesFromRule.ts
  packages/utils/src/eslint-utils/RuleCreator.ts
  packages/utils/src/eslint-utils/getParserServices.ts
  packages/utils/src/eslint-utils/index.ts
  packages/utils/src/json-schema.ts
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/ESLint.ts
  packages/utils/src/ts-eslint/Linter.ts
  packages/utils/src/ts-eslint/Parser.ts
  packages/utils/src/ts-eslint/Processor.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/utils/src/ts-eslint/RuleTester.ts
  packages/utils/src/ts-eslint/SourceCode.ts
  packages/utils/src/ts-eslint/eslint/ESLintShared.ts
  packages/utils/src/ts-eslint/eslint/FlatESLint.ts
  packages/utils/src/ts-estree.ts
  yarn.lock
Labels: 1 approval

#9839 chore(website): allow markdown in titles
  knip.ts
  packages/website/package.json
  packages/website/src/theme/BlogPostItem/Header/Title/index.tsx
  packages/website/src/theme/BlogPostItem/Header/Title/styles.module.css
  packages/website/src/theme/BlogSidebar/Content/index.tsx
  packages/website/src/theme/BlogSidebar/Content/styles.module.css
  yarn.lock
Labels: 1 approval

#9841 chore: enable eslint-plugin-perfectionist on visitor-keys package
  eslint.config.mjs
  packages/visitor-keys/src/get-keys.ts
  packages/visitor-keys/src/visitor-keys.ts
Labels: 1 approval

#9862 docs: add FAQs > TypeScript entry on comment directives
  docs/troubleshooting/faqs/TypeScript.mdx
Labels: 1 approval

#9840 chore: enable eslint-plugin-perfectionist on website packages
  eslint.config.mjs
  packages/website/src/components/ast/selectedRange.ts
  packages/website/src/components/ast/tsUtils.ts
  packages/website/src/components/ast/utils.ts
  packages/website/src/components/editor/createProvideCodeActions.ts
  packages/website/src/components/editor/createProvideTwoslashInlay.ts
  packages/website/src/components/editor/loadSandbox.ts
  packages/website/src/components/editor/types.ts
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/lib/createCompilerOptions.ts
  packages/website/src/components/lib/createEventsBinder.ts
  packages/website/src/components/lib/jsonSchema.ts
  packages/website/src/components/lib/markdown.ts
  packages/website/src/components/lib/parseConfig.ts
  packages/website/src/components/lib/scroll-into.ts
  packages/website/src/components/linter/bridge.ts
  packages/website/src/components/linter/config.ts
  packages/website/src/components/linter/createLinter.ts
  packages/website/src/components/linter/createParser.ts
  packages/website/src/components/linter/types.ts
  packages/website/src/components/linter/utils.ts
  packages/website/src/components/options.ts
  packages/website/src/components/types.ts
  packages/website/src/globals.d.ts
  packages/website/src/hooks/useBool.ts
  packages/website/src/hooks/useHistorySelector.ts
  packages/website/src/hooks/useRulesMeta.ts
Labels: 1 approval

#9870 docs(eslint-plugin): [restrict-template-expressions] add explanation for allowNumber
  packages/eslint-plugin/docs/rules/restrict-template-expressions.mdx
Labels: 1 approval

#9844 chore: enable eslint-plugin-perfectionist on integration-tests package
  eslint.config.mjs
  packages/integration-tests/tools/integration-test-base.ts
  packages/integration-tests/tools/pack-packages.ts
Labels: 1 approval

#9788 fix(utils): add `TSDeclareFunction` to `functionTypeTypes`
  packages/eslint-plugin/src/rules/no-redundant-type-constituents.ts
  packages/eslint-plugin/tests/rules/no-redundant-type-constituents.test.ts
  packages/utils/src/ast-utils/predicates.ts
Labels: 1 approval

#9845 chore: enable eslint-plugin-perfectionist on parser package
  eslint.config.mjs
  packages/parser/src/index.ts
  packages/parser/src/parser.ts
  packages/parser/tests/lib/parser.test.ts
  packages/parser/tests/lib/services.test.ts
  packages/parser/tests/lib/tsx.test.ts
  packages/parser/tests/test-utils/test-utils.ts
  packages/parser/tests/test-utils/ts-error-serializer.ts
Labels: 1 approval

#9847 chore: enable eslint-plugin-perfectionist on rule-tester package
  eslint.config.mjs
  packages/rule-tester/src/RuleTester.ts
  packages/rule-tester/src/TestFramework.ts
  packages/rule-tester/src/index.ts
  packages/rule-tester/src/types/DependencyConstraint.ts
  packages/rule-tester/src/types/InvalidTestCase.ts
  packages/rule-tester/src/types/ValidTestCase.ts
  packages/rule-tester/src/types/index.ts
  packages/rule-tester/src/utils/ajv.ts
  packages/rule-tester/src/utils/config-validator.ts
  packages/rule-tester/src/utils/deprecation-warnings.ts
  packages/rule-tester/src/utils/flat-config-schema.ts
  packages/rule-tester/src/utils/getRuleOptionsSchema.ts
  packages/rule-tester/src/utils/hasOwnProperty.ts
  packages/rule-tester/src/utils/validationHelpers.ts
  packages/rule-tester/tests/RuleTester.test.ts
  packages/rule-tester/tests/flat-config-schema.test.ts
Labels: 1 approval

#9851 chore: enable eslint-plugin-perfectionist on typescript-eslint package
  eslint.config.mjs
  packages/typescript-eslint/src/index.ts
  packages/typescript-eslint/tests/configs.test.ts
Labels: 1 approval

#9830 chore: enable unicorn/no-lonely-if
  eslint.config.mjs
  packages/eslint-plugin/src/rules/consistent-type-imports.ts
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/src/rules/no-empty-interface.ts
  packages/eslint-plugin/src/rules/no-magic-numbers.ts
  packages/eslint-plugin/src/rules/no-misused-new.ts
  packages/eslint-plugin/src/rules/no-misused-promises.ts
  packages/eslint-plugin/src/rules/no-type-alias.ts
  packages/eslint-plugin/src/rules/no-unnecessary-parameter-property-assignment.ts
  packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/eslint-plugin/src/util/getWrappingFixer.ts
  packages/rule-tester/src/utils/serialization.ts
  packages/typescript-estree/src/convert.ts
  packages/website/src/components/ast/selectedRange.ts
  packages/website/src/components/ast/tsUtils.ts
  packages/website/tools/typedoc-plugin-no-inherit-fork.mjs
Labels: 1 approval

#9835 docs: replace most references to "project: true" with "projectService: true"
  docs/getting-started/Typed_Linting.mdx
  docs/packages/TypeScript_ESLint.mdx
  docs/troubleshooting/faqs/General.mdx
  docs/users/Shared_Configurations.mdx
Labels: documentation, 1 approval

#9632 fix(ast-spec): use `Expression` in argument of `ThrowStatement`
  eslint.config.mjs
  nx.json
  packages/ast-spec/src/statement/ThrowStatement/spec.ts
  packages/eslint-plugin/src/rules/only-throw-error.ts
  packages/scope-manager/tsconfig.build.json
  packages/scope-manager/tsconfig.spec.json
Labels: bug

#9518 feat(typescript-estree): replace `globby` w/ `fast-glob`
  packages/typescript-estree/package.json
  packages/typescript-estree/src/parseSettings/resolveProjectList.ts
  packages/typescript-estree/tests/lib/parse.test.ts
  yarn.lock
Labels: 1 approval

#9821 chore: enable sonarjs/no-duplicated-branches
  eslint.config.mjs
  package.json
  packages/ast-spec/tests/util/serializers/string.ts
  packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
  packages/eslint-plugin/src/rules/no-non-null-assertion.ts
  packages/scope-manager/src/referencer/Referencer.ts
  yarn.lock
Labels: 1 approval

#9853 feat(typescript-estree): reload project service once when file config isn't found
  packages/typescript-estree/src/create-program/createProjectService.ts
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Labels: 1 approval

#9864 docs: add 'Rule Not Found' FAQ for Local Linking
  docs/contributing/local-development/Local_Linking.mdx
Labels: 1 approval

#9872 docs: added more no-restricted-syntax FAQ examples
  docs/troubleshooting/faqs/General.mdx
Labels: 1 approval

#9871 docs: add more project service docs and FAQs
  docs/packages/Parser.mdx
  docs/troubleshooting/typed-linting/index.mdx
  packages/typescript-estree/tests/lib/createProjectService.test.ts
  packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
  packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
  packages/website/src/css/custom.css
Labels: 1 approval

#9865 docs: add global variable rule disabling FAQ for ESLint
  docs/troubleshooting/faqs/ESLint.mdx
  packages/eslint-plugin/docs/rules/no-namespace.mdx
Labels: 1 approval

#9874 docs: mention RuleTester static properties
  docs/packages/Rule_Tester.mdx
Labels: 1 approval

#9873 docs: add website-eslint README.md
  packages/website-eslint/README.md
  packages/website/README.md
Labels: documentation, 1 approval

#9883 chore: disable eslint-plugin-perfectionist on enums
  eslint.config.mjs
Labels: 1 approval

#9877 feat(typescript-estree): make withoutProjectParserOptions generic
  packages/typescript-estree/src/withoutProjectParserOptions.ts
  packages/typescript-estree/tests/lib/withoutProjectParserOptions.test.ts
Labels: 1 approval

#9875 docs: add dedicated TypeOrValueSpecifier docs page
  .cspell.json
  docs/packages/type-utils/TypeOrValueSpecifier.mdx
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
  packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.mdx
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-readonly-parameter-types.shot
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
  packages/type-utils/src/TypeOrValueSpecifier.ts
  packages/website/sidebars/sidebar.base.js
  packages/website/src/css/custom.css
Labels: 1 approval

#9795 docs: added note on async generator support in require-await
  packages/eslint-plugin/docs/rules/require-await.mdx
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/require-await.shot
Labels: documentation, 1 approval
