Repository typescript-eslint/typescript-eslint, pull requests merged in 2024-02, with the labels that each got.

#8057 docs: add /maintenance/team page
  .cspell.json
  docs/maintenance/Team.mdx
  package.json
  packages/website-eslint/package.json
  packages/website/sidebars/sidebar.base.js
  packages/website/src/components/team/TeamBio.module.css
  packages/website/src/components/team/TeamBio.tsx
  packages/website/src/components/team/TeamBioDivider.module.css
  packages/website/src/components/team/TeamBioDivider.tsx
  packages/website/src/components/team/TeamBioList.module.css
  packages/website/src/components/team/TeamBioList.tsx
  packages/website/static/img/team/armano2.jpg
  packages/website/static/img/team/bradzacher.jpg
  packages/website/static/img/team/jameshenry.jpg
  packages/website/static/img/team/josh-cena.jpg
  packages/website/static/img/team/joshuakgoldberg.jpg
  packages/website/static/img/www.svg
  yarn.lock
Labels: 1 approval, package: website

#8329 chore: move generate-configs to repo-tools
  package.json
  packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
  packages/eslint-plugin/package.json
  packages/repo-tools/package.json
  packages/repo-tools/src/generate-configs.mts
  packages/repo-tools/src/generate-contributors.mts
  packages/repo-tools/src/generate-lib.mts
  packages/repo-tools/src/generate-sponsors.mts
  packages/repo-tools/src/paths.mts
  packages/repo-tools/tsconfig.json
Labels: repo maintenance

#8296 chore: add `typescript-eslint` package scaffold
  .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
  .github/workflows/ci.yml
  .github/workflows/semantic-pr-titles.yml
  package.json
  packages/typescript-eslint/LICENCE
  packages/typescript-eslint/README.md
  packages/typescript-eslint/package.json
  packages/typescript-eslint/project.json
  packages/typescript-eslint/src/index.ts
  packages/typescript-eslint/tsconfig.build.json
  packages/typescript-eslint/tsconfig.json
  yarn.lock
Labels: repo maintenance

#8249 fix(eslint-plugin): [no-unnecessary-condition] handle left-hand optional with exactOptionalPropertyTypes option
  packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
  packages/eslint-plugin/tests/fixtures/tsconfig.exactOptionalPropertyTypes.json
  packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Labels: 1 approval

#8338 chore: bump eslint versions
  nx.json
  package.json
  packages/eslint-plugin/tests/schema-snapshots/lines-between-class-members.shot
  packages/eslint-plugin/tests/schema-snapshots/no-restricted-imports.shot
  yarn.lock
Labels: dependencies, repo maintenance

#8277 fix(eslint-plugin): [class-literal-property-style] allow getter when same key setter exists
  packages/eslint-plugin/src/rules/class-literal-property-style.ts
  packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
Labels: 1 approval

#8344 feat(utils): improve eslint types
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/Linter.ts
  packages/utils/src/ts-eslint/Parser.ts
  packages/utils/src/ts-eslint/Rule.ts
Labels: enhancement

#8331 feat: export plugin metadata
  packages/eslint-plugin-internal/src/index.ts
  packages/eslint-plugin-internal/src/rules/index.ts
  packages/eslint-plugin-tslint/src/index.ts
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/base.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/configs/eslint-recommended.ts
  packages/eslint-plugin/src/configs/recommended-type-checked.ts
  packages/eslint-plugin/src/configs/recommended.ts
  packages/eslint-plugin/src/configs/strict-type-checked.ts
  packages/eslint-plugin/src/configs/strict.ts
  packages/eslint-plugin/src/configs/stylistic-type-checked.ts
  packages/eslint-plugin/src/configs/stylistic.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/repo-tools/src/generate-configs.mts
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/Linter.ts
Labels: enhancement

#8216 feat(eslint-plugin): add rule prefer-find
  packages/eslint-plugin/docs/rules/prefer-find.md
  packages/eslint-plugin/src/configs/all.ts
  packages/eslint-plugin/src/configs/disable-type-checked.ts
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/prefer-find.ts
  packages/eslint-plugin/tests/rules/prefer-find.test.ts
  packages/eslint-plugin/tests/schema-snapshots/prefer-find.shot
  packages/utils/src/eslint-utils/nullThrows.ts
Labels: enhancement: new plugin rule, 1 approval

#8260 fix(rule-tester): fix a phantom dependency on the "semver" package
  packages/rule-tester/src/types/DependencyConstraint.ts
Labels: 1 approval

#8339 feat: allow `parserOptions.project: false`
  docs/packages/Parser.mdx
  docs/packages/TypeScript_ESTree.mdx
  packages/types/src/parser-options.ts
  packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
  packages/typescript-estree/src/parser-options.ts
  packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
Labels: enhancement

#8390 fix(eslint-plugin): [prefer-find] stop throwing type errors when converting symbols to numbers
  packages/eslint-plugin/src/rules/prefer-find.ts
  packages/eslint-plugin/tests/rules/prefer-find.test.ts
Labels: 1 approval

#8399 feat(utils): revert removal of backwards-compat functions
  packages/utils/src/eslint-utils/context.ts
Labels: enhancement

#8400 docs: blog post for v7
  docs/packages/TypeScript_ESLint.mdx
  packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
  packages/website/docusaurusConfig.ts
Labels: documentation

#8297 feat(website): add ESQuery filter to URL state
  packages/website/src/components/ESQueryFilter.tsx
  packages/website/src/components/Playground.tsx
  packages/website/src/components/hooks/useHashState.ts
  packages/website/src/components/types.ts
Labels: 1 approval

#8448 docs: fix missing bracket in Typed_Linting.mdx
  docs/linting/Typed_Linting.mdx
Labels: documentation

#8460 fix: fix tsconfig-less check errors, fix `@types/eslint` incompatibilities, add tests
  eslint.config.mjs
  packages/integration-tests/fixtures/flat-config-types/dirname.cjs
  packages/integration-tests/fixtures/flat-config-types/eslint.config.js
  packages/integration-tests/fixtures/flat-config-types/package.json
  packages/integration-tests/tests/__snapshots__/eslint-v8.test.ts.snap
  packages/integration-tests/tests/__snapshots__/flat-config-types.test.ts.snap
  packages/integration-tests/tests/__snapshots__/markdown.test.ts.snap
  packages/integration-tests/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
  packages/integration-tests/tests/__snapshots__/typescript-and-tslint-plugins-together.test.ts.snap
  packages/integration-tests/tests/__snapshots__/vue-jsx.test.ts.snap
  packages/integration-tests/tests/__snapshots__/vue-sfc.test.ts.snap
  packages/integration-tests/tests/eslint-v8.test.ts
  packages/integration-tests/tests/flat-config-types.test.ts
  packages/integration-tests/tests/markdown.test.ts
  packages/integration-tests/tests/recommended-does-not-require-program.test.ts
  packages/integration-tests/tests/typescript-and-tslint-plugins-together.test.ts
  packages/integration-tests/tests/vue-jsx.test.ts
  packages/integration-tests/tests/vue-sfc.test.ts
  packages/integration-tests/tools/integration-test-base.ts
  packages/scope-manager/package.json
  packages/types/package.json
  packages/types/src/parser-options.ts
  packages/typescript-eslint/package.json
  packages/typescript-eslint/src/config-helper.ts
  packages/typescript-eslint/src/index.ts
  packages/typescript-estree/package.json
  packages/utils/package.json
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/Parser.ts
  packages/utils/src/ts-eslint/Processor.ts
  packages/utils/src/ts-eslint/Rule.ts
  packages/visitor-keys/package.json
Labels: bug

#8468 docs: fix invalid relative link in getting started page details section
  docs/Getting_Started.mdx
Labels: documentation

#8489 docs: describe when to use `evaluating community engagement` and `wontfix` labels in Issue Flow
  docs/maintenance/Issues.mdx
Labels: 1 approval

#8526 docs: no-unused-vars demonstrate TypeScript style exemptions
  packages/eslint-plugin/docs/rules/no-unused-vars.md
Labels: documentation

#8366 chore: extract eslint-plugin-tslint to new repository
  .eslintrc.js
  .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
  .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
  .github/workflows/ci.yml
  .github/workflows/semantic-pr-titles.yml
  .vscode/launch.json
  docs/packages/ESLint_Plugin_TSLint.mdx
  docs/users/Versioning.mdx
  package.json
  packages/eslint-plugin-tslint/CHANGELOG.md
  packages/eslint-plugin-tslint/LICENSE
  packages/eslint-plugin-tslint/README.md
  packages/eslint-plugin-tslint/jest.config.js
  packages/eslint-plugin-tslint/package.json
  packages/eslint-plugin-tslint/project.json
  packages/eslint-plugin-tslint/src/custom-linter.ts
  packages/eslint-plugin-tslint/src/index.ts
  packages/eslint-plugin-tslint/src/rules/config.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/1.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/2.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/3.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/4.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/5.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/6.ts
  packages/eslint-plugin-tslint/tests/fixtures/fixture-project/tsconfig.json
  packages/eslint-plugin-tslint/tests/fixtures/test-project/extra.ts
  packages/eslint-plugin-tslint/tests/fixtures/test-project/file-spec.ts
  packages/eslint-plugin-tslint/tests/fixtures/test-project/file.ts
  packages/eslint-plugin-tslint/tests/fixtures/test-project/source.ts
  packages/eslint-plugin-tslint/tests/fixtures/test-project/tsconfig-files.json
  packages/eslint-plugin-tslint/tests/fixtures/test-project/tsconfig.json
  packages/eslint-plugin-tslint/tests/fixtures/test-project/tslint.json
  packages/eslint-plugin-tslint/tests/fixtures/test-tslint-rules-directory/alwaysFailRule.js
  packages/eslint-plugin-tslint/tests/index.spec.ts
  packages/eslint-plugin-tslint/tsconfig.build.json
  packages/eslint-plugin-tslint/tsconfig.json
  packages/integration-tests/fixtures/typescript-and-tslint-plugins-together/.eslintrc.js
  packages/integration-tests/fixtures/typescript-and-tslint-plugins-together/index.ts
  packages/integration-tests/fixtures/typescript-and-tslint-plugins-together/package.json
  packages/integration-tests/fixtures/typescript-and-tslint-plugins-together/tsconfig.json
  packages/integration-tests/tools/integration-test-base.ts
  yarn.lock
Labels: repo maintenance

#8474 fix(eslint-plugin): [no-use-before-define] fix false positive type reference in as, satisfies
  packages/eslint-plugin/src/rules/no-use-before-define.ts
  packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
Labels: 1 approval

#8567 fix(typescript-eslint): apply `ignores` to all extended configs passed to `config` helper function
  packages/typescript-eslint/src/config-helper.ts
  packages/typescript-eslint/tests/configs.test.ts
Labels: bug
