Repository typescript-eslint/typescript-eslint, pull requests merged in 2025-06, with the labels that each got.

#11251 fix: exclude docs/ directory from eslint-plugin package
  packages/eslint-plugin/package.json
Labels: 1 approval

#11279 fix(visitor-keys): fix visitor keys order
  packages/scope-manager/tests/fixtures/type-declaration/index-access2.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/index-access3.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/mapped-named.ts.shot
  packages/scope-manager/tests/fixtures/type-declaration/mapped.ts.shot
  packages/visitor-keys/src/visitor-keys.ts
Labels: 1 approval

#11283 fix(typescript-estree): change the token type of `null` from `Keyword` to `Null`
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/null-and-undefined-type-annotations/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/null-and-undefined-type-annotations/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/object-with-escaped-properties/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/typed-keyword-null/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/union-intersection/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/union-intersection/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/types/fixtures/conditional-with-null/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/types/fixtures/conditional-with-null/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/types/fixtures/nested-types/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/types/fixtures/union-intersection/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/legacy-fixtures/types/fixtures/union-intersection/snapshots/6-AST-Alignment-Tokens.shot
  packages/ast-spec/tests/fixtures-with-differences-tokens.shot
  packages/typescript-estree/src/node-utils.ts
Labels: AST

#11268 docs: rename "directive comments" to "comment directives"
  packages/eslint-plugin/docs/rules/ban-ts-comment.mdx
  packages/eslint-plugin/src/util/astUtils.ts
  packages/scope-manager/src/variable/ESLintScopeVariable.ts
  packages/utils/src/ts-eslint/Config.ts
  packages/utils/src/ts-eslint/eslint/ESLintShared.ts
Labels: 1 approval

#11299 fix(typescript-estree): align constructor literal with eslint
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/fixture.ts
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/4-Babel-Tokens.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/fixture.ts
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/2-TSESTree-Tokens.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/3-Babel-AST.shot
  packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/4-Babel-Tokens.shot
  packages/typescript-estree/src/convert.ts
Labels: awaiting response

#11280 chore(eslint-plugin): switch auto-generated test cases to hand-written in no-base-to-string.test.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: 1 approval

#11286 chore: speed up semantic-breaking-change-pr.yml
  .github/actions/breaking-pr-check/action.yml
  .github/actions/breaking-pr-check/index.js
  .github/workflows/semantic-breaking-change-pr-test.yml
  package.json
  yarn.lock
Labels: 1 approval

#11198 fix(website): acquired types are shown in the editor but not reflected in linting
  packages/website/src/components/editor/useSandboxServices.ts
  packages/website/src/components/linter/bridge.ts
  packages/website/src/components/linter/createLinter.ts
  packages/website/src/components/linter/createParser.ts
  packages/website/src/components/linter/types.ts
Labels: 1 approval

#11315 docs: remove legacy note about __dirname
  docs/getting-started/Typed_Linting.mdx
Labels: 1 approval

#11338 chore(rule-tester): correct typo in test
  packages/rule-tester/tests/RuleTester.test.ts
Labels: 1 approval

#11341 chore: replace custom CONTRIBUTORS.md with GitHub's graphs/contributors
  .cspell.json
  .prettierignore
  CONTRIBUTORS.md
  README.md
  package.json
  tools/scripts/generate-contributors.mts
Labels: 1 approval

#11335 docs: mention ESLint's defineConfig()
  docs/getting-started/Quickstart.mdx
  docs/packages/TypeScript_ESLint.mdx
Labels: 1 approval
