Repository typescript-eslint/typescript-eslint, pull requests merged in 2025-09, with the labels that each got.

#11531 feat: deprecate tseslint.config()
  docs/getting-started/Quickstart.mdx
  docs/getting-started/Typed_Linting.mdx
  docs/packages/TypeScript_ESLint.mdx
  docs/troubleshooting/faqs/ESLint.mdx
  docs/troubleshooting/faqs/Frameworks.mdx
  docs/troubleshooting/faqs/General.mdx
  docs/troubleshooting/typed-linting/Monorepos.mdx
  docs/troubleshooting/typed-linting/Performance.mdx
  docs/troubleshooting/typed-linting/index.mdx
  docs/users/Shared_Configurations.mdx
  docs/users/What_About_Formatting.mdx
  eslint.config.mjs
  packages/typescript-eslint/src/config-helper.ts
  packages/typescript-eslint/tests/config-helper.test.ts
  packages/typescript-eslint/tests/type-compatibility.test-d.ts
Labels: 1 approval

#11497 feat(typescript-estree): forbid invalid keys in `EnumMember`
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/with-member-one/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/declaration/TSEnumDeclaration/fixtures/with-member-one/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/bigint-name/fixture.ts
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/bigint-name/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/bigint-name/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/bigint-name/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/computed-string-name/fixture.ts
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/computed-string-name/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/computed-string-name/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/computed-string-name/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/number-name/fixture.ts
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/number-name/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/number-name/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/element/TSEnumMember/fixtures/_error_/number-name/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/element/TSEnumMember/spec.ts
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/export-named-enum-computed-number/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/export-named-enum-computed-number/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/export-named-enum-computed-string/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/export-named-enum-computed-string/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/export-named-enum-computed-var-ref/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/_error_/export-named-enum-computed-var-ref/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/const-enum/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/const-enum/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-declare-const-named-enum/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-declare-const-named-enum/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-declare-named-enum/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-declare-named-enum/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-named-enum/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/basics/fixtures/export-named-enum/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/src/legacy-fixtures/declare/fixtures/enum/snapshots/1-TSESTree-AST.shot
  packages/ast-spec/src/legacy-fixtures/declare/fixtures/enum/snapshots/5-AST-Alignment-AST.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/eslint-plugin/src/rules/naming-convention.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
  packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
  packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
  packages/scope-manager/src/referencer/Referencer.ts
  packages/types/src/ts-estree.ts
  packages/typescript-estree/src/convert.ts
Labels: 1 approval, AST

#11469 fix(scope-manager): exclude Program from DefinitionBase node types
  packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
  packages/eslint-plugin/src/util/collectUnusedVariables.ts
  packages/scope-manager/src/definition/DefinitionBase.ts
  packages/scope-manager/src/definition/ImplicitGlobalVariableDefinition.ts
  packages/scope-manager/src/referencer/Reference.ts
  packages/types/src/ts-estree.ts
  packages/utils/src/ts-estree.ts
Labels: 1 approval

#11537 fix(typescript-estree): match filenames starting with a period when using glob in allowDefaultProject
  packages/typescript-estree/src/useProgramFromProjectService.ts
  packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Labels: 1 approval

#11430 fix(eslint-plugin): [no-floating-promises] allowForKnownSafeCalls now supports function names (fixes #11423)
  packages/eslint-plugin/docs/rules/no-floating-promises.mdx
  packages/eslint-plugin/src/rules/no-floating-promises.ts
  packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
  packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Labels: 1 approval

#11563 feat(typescript-estree): disallow empty type parameter/argument lists
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-extends-type-param/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-extends-type-param/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param-with-comment/fixture.ts
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param-with-comment/snapshots/1-Babel-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param-with-comment/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param-with-comment/snapshots/2-Alignment-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param-with-comment/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param-with-comment/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/ClassDeclaration/fixtures/_error_/missing-type-param/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/FunctionDeclaration/fixtures/_error_/missing-type-param/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/FunctionDeclaration/fixtures/_error_/missing-type-param/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/missing-type-param/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSDeclareFunction/fixtures/_error_/missing-type-param/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/missing-type-param/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSInterfaceDeclaration/fixtures/_error_/missing-type-param/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/missing-type-parameter/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/declaration/TSTypeAliasDeclaration/fixtures/_error_/missing-type-parameter/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression-with-comment/fixture.ts
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression-with-comment/snapshots/1-Babel-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression-with-comment/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression-with-comment/snapshots/2-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression-with-comment/snapshots/2-Babel-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression-with-comment/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-call-expression/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-new-expression/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments-in-new-expression/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-arguments/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-arrow-function/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-arrow-function/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-constructor/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-constructor/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-function-expression/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-function-expression/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-method-signature/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-method-signature/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-method/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters-in-method/snapshots/3-Alignment-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters/snapshots/1-TSESTree-Error.shot
  packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/empty-type-parameters/snapshots/3-Alignment-Error.shot
  packages/ast-spec/tests/fixtures-with-differences-errors.shot
  packages/eslint-plugin/src/rules/array-type.ts
  packages/eslint-plugin/tests/rules/array-type.test.ts
  packages/eslint-plugin/tests/rules/method-signature-style.test.ts
  packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
  packages/typescript-estree/src/convert.ts
Labels: AST

#11594 chore(typescript-estree): simplify `convertImportAttributes`
  packages/typescript-estree/src/convert.ts
Labels: 1 approval

#11592 chore(typescript-estree): add `Converter#convertChildren()`
  packages/typescript-estree/src/convert.ts
Labels: 1 approval

#11599 fix(eslint-plugin): [no-unsafe-enum-comparison] support unions of literals
  packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
  packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Labels: bug, 1 approval

#11645 chore(website): lint for missing `g` flag
  eslint.config.mjs
  packages/website/src/components/editor/createProvideTwoslashInlay.ts
Labels: 1 approval

#11617 fix(eslint-plugin): [no-base-to-string] check if superclass is ignored
  packages/eslint-plugin/src/rules/no-base-to-string.ts
  packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Labels: 1 approval

#11616 feat(eslint-plugin): expose rule name via RuleModule interface
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
  packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
  packages/rule-tester/tests/RuleTester.test.ts
  packages/rule-tester/tests/filename.test.ts
  packages/utils/src/eslint-utils/RuleCreator.ts
  packages/utils/src/ts-eslint/Rule.ts
Labels: 1 approval
